### ISSUE TITLE
proposal: contrib/database/sql: add Option to prevent starting new traces

### ISSUE THREAD

**Issue by j-sv** [DataDog/dd-trace-go#1014]
When using the package for adding traces to an HTTP server it allows for disabling traces for certain requests. This means no span will exist in the context being passed to the request handler. If this ends up in the contrib/database/sql package it ends up creating a span that is not connected to any request span, leading to a lot of dangling database traces.

E.g., we disable all traces for the healthcheck endpoint of our API, which leads to quite a lot of unnecessary traces for Ping calls to the database being created.

**Comment by knusbaum** [comment]
Hi @j-sv,
Thanks for the issue and PR.

It's a valid use case to trace sql calls without parent spans, and we don't want to break the integration for anyone using it that way.

If we want to implement this, we should add an `Option` that sets this behavior. It should not be the default.

**Comment by j-sv** [comment]
Thanks for the input! I've updated the PR to add an `Option` to enable the check, with the default being the current behavior.
