### ISSUE TITLE
WithIgnoreRequest not respected with WrapHandler

### ISSUE THREAD

**Issue by tobstarr** [DataDog/dd-trace-go#1018]
When passing `WithIgnoreRequest` to `WrapHandler` the ignore function is not called at all. This is due the fact that it is only called in `func (mux *ServeMux) ServeHTTP` and `WrapHandler` directly goes to `TraceAndServe`. 

Is there a specific reason for this?

**Comment by knusbaum** [comment]
@tobstarr This looks to me like an oversight in the implementation.

We'd be happy to accept a PR to fix this, or I'll put it in my queue.
