### ISSUE TITLE
proposal: allow configuration of Trace Agent URL with DD_TRACE_AGENT_URL

### ISSUE THREAD

**Issue by PonzaMatteo** [DataDog/dd-trace-go#1023]
# Problem Statement
Other SDKs (like the js and python one) allow to configure the trace agent URL using the env variable `DD_TRACE_AGENT_URL` while the Go SDK only allows using the combination of `DD_AGENT_HOST` + `DD_TRACE_AGENT_PORT`, this results in the following issues for our needs:
- [the hardcoded protocol](https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/tracer/transport.go#L105) is `HTTP`, but we would need to utilize `HTTPS`
- it's not possible to omit the port in the agent URL since if left empty it defaults to `8126` 

# Proposed Solution
Allow using `DD_TRACE_AGENT_URL` to override the combination of the other two variables.

**Comment by zlcaique** [comment]
`func WithAgentAddr(addr string)` does this?
https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1@v1.26.0/ddtrace/tracer

**Comment by hush-hush** [comment]
This would also solve the issue of customer not being able to configure both a DogStatsD client and the tracer on the same host when using UDS:

ref: https://github.com/DataDog/datadog-go/issues/201

**Comment by knusbaum** [comment]
I think `DD_TRACE_AGENT_URL` would be a more useful and consistent option than the current host + port combination for all the reasons mentioned here. 

I think in addition to introducing `DD_TRACE_AGENT_URL` and having it override the other existing environment variables, we should deprecate the old ones and discourage their use.

**Comment by adawalli** [comment]
The fact that this is hard-coded goes against the defaults that are now used in the helm chart for agent deploys: https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml#L355

8126 is not even exposed by default anymore - the Unix socket is used!
