### ISSUE TITLE
contrib/google.golang.org/grpc: Client service name doesn't respect global service name

### ISSUE THREAD

**Issue by jaltavilla** [DataDog/dd-trace-go#1040]
When making a gRPC request, the global tracer's service name is not used. This appears to be deliberate; the `clientServiceName` function differs from the `serverServiceName` function by just that.  (see https://github.com/DataDog/dd-trace-go/blob/154367045f5cea6dfa80d0bf72f49702250fa1cc/contrib/google.golang.org/grpc/option.go#L44).

Not having the client service name be that of the calling service seems to be subtly wrong.  When viewing the traces the default value of "grpc.client" appears as a separate service. This results in things like the service map not showing dependencies directly, and the span looking like it's in a different service than the time was actually in.

I can work around this by passing in the service name option myself when creating the client, but this is an interface breaking change in our code. I propose that the client should use the global service name if present.

**Comment by knusbaum** [comment]
@jaltavilla We have seen requests to have the client use the server's service name regularly and understand the use case.
 Please see our FAQ about this: https://github.com/DataDog/dd-trace-go/blob/v1/FAQ.md#why-do-client-integration-spans-not-use-the-global-service-name
 
 Unfortunately this is a product-level decision and not a change we can make ATM, but please feel free to reach out to Datadog support to request this.
