### ISSUE TITLE
Is there a way to get the Active Root Span from the Tracer?

### ISSUE THREAD

**Issue by nick-behrens** [DataDog/dd-trace-go#1041]
Hi, 
In the Ruby Datadog trace gem, there is a method that can be used to get the [current root span](https://github.com/DataDog/dd-trace-rb/blob/v0.53.0/lib/ddtrace/tracer.rb#L348-L350). Can this functionality be added to the Go version of the tracer?

Currently, I have (I think) hacked around this by defining a wrapper and doing something like this.
```go
type contextKey struct{}

var (
  activeRootSpan  = contextKey{}
)

// StartSpan starts a new span and attaches it to the given context.
//  If a span is already started, it makes the span a child of the currently active span.
//  If the tracer is not started it returns a Noop tracer.Span. 
func StartSpan(ctx context.Context, spanName string) (context.Context, tracer.Span) {
  var startedSpan tracer.Span
  if span, ok := tracer.SpanFromContext(ctx); ok {
    startedSpan = tracer.StartSpan(spanName, tracer.ChildOf(span.Context()),
	    tracer.ResourceName(spanName))
  } else {
    startedSpan = tracer.StartSpan(spanName, tracer.ResourceName(spanName))
    // Store the root span on the context so we can reference it later.
    ctx = context.WithValue(ctx, activeRootSpan, startedSpan)
  }
  
  ctxWithSpan := tracer.ContextWithSpan(ctx, startedSpan)
  
  return ctxWithSpan, startedSpan
}

// GetActiveRootSpan returns the current active root span if found. 
//  The bool return indicates if an active root span was found or not.
func GetActiveRootSpan(ctx context.Context) (tracer.Span, bool) {
  var span tracer.Span
  if span, ok := tracer.SpanFromContext(ctx); ok {
    v := ctx.Value(activeRootSpan)
    
    if span, ok = v.(tracer.Span); ok {
      return span, true
    }
  }
  
  return span, false
}
```

This solution isn't the best and requires my project to always use my wrapper to get a span.

Ideally I would like to get the root span using something like this, but I'm not sure if it can be done:
```go
tracer.RootSpanFromContext(ctx)
```

I saw there was a related issue in the JS tracer but I couldn't figure out if it was possible in Go: https://github.com/DataDog/dd-trace-js/issues/725

Thanks!

**Comment by gbbr** [comment]
Hey there! 👋🏻 

The only way to obtain a span within a context in Go, is by using the `context` and maintaining a reference to it throughout. We already have this type of functionality by means of [SpanFromContext](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer#SpanFromContext) and [StartSpanFromContext](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer#StartSpanFromContext). Those two functions seem to be doing what you're after. Have you considered using them?

**Comment by nick-behrens** [comment]
Thanks for getting back to me quickly @gbbr! We actually are using `SpanFromContext` but I think `StartSpanFromContext` could save me some boilerplate, thanks for the suggestion. 

I think I'm going use `StartSpanFromContext` to start nested spans and store the root one myself so I can reference it later.
