### ISSUE TITLE
contrib/database/sql: error for named parameters when using mssql driver for sqltrace

### ISSUE THREAD

**Issue by marilangaas** [DataDog/dd-trace-go#1043]
We are trying to add dd-trace-go for tracing our sql queries. We are using the [database/sql package](https://pkg.go.dev/database/sql) and the driver is https://github.com/denisenkom/go-mssqldb. 

When importing the driver as a blank identifier and not using tracing, i.e. 

```
import (
      _ "github.com/denisenkom/go-mssqldb"
)
...

db, err := sql.Open("sqlserver", s.Config.ConnectionString)
```

it works fine, but when switching this out with

```
import (
       mssql "github.com/denisenkom/go-mssqldb"
)
...

sqltrace.Register("sqlserver", &mssql.Driver{})
db, err := sqltrace.Open("sqlserver", s.Config.ConnectionString)
```

the following error occurs:

```
Received unexpected error: sql: driver does not support the use of Named Parameters
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x159f86d]
```

We use `QueryRowContext` and `ExecContext` in our queries and it seems like the error is connected to what happens to `queryerCtx`. When using dd-trace-go it is set with a value for `Conn` and `traceParams`, while for database/sql it is nil, so it seems like the sql tracing package does not replicate the behavior of database/sql when it comes to the mssql-driver. Does anyone know how to resolve this problem?

**Comment by knusbaum** [comment]
Hi, @marilangaas. 

This looks like a potential bug in our sql tracing. In order to solve it, it would be extremely helpful to have a simple, compilable reproduction case along with library versions, etc.

We'll work on investigating this issue.

**Comment by marilangaas** [comment]
Hi! 
Thanks for your answer!

I have made a simple reproduction in this repo: https://github.com/marilangaas/dd_mssql_example. 

We are using the same versions for the packages as listed in the `go.mod` file. 
go version go1.17.2
