### ISSUE TITLE
contrib/internal/httputil: can we make it public?

### ISSUE THREAD

**Issue by soh335** [DataDog/dd-trace-go#1047]
Hi, I think `contrib/internal/httputil` is very useful to adapt tracing for any go server application.So I hope it make public.

For example, if user use minor web framework, sometime difficult to adapt datadog tracing to it. 
Off course user can send p-r to this repository adding to contrib, but  I feel it its not practical for everything.

Other case, it's our case, currently we use [julienschmidt/httprouter](https://github.com/julienschmidt/httprouter) And [hitch](https://github.com/nbio/hitch).
Already httprouter is adapted to datadog trace at [here](https://github.com/DataDog/dd-trace-go/blob/v1/contrib/julienschmidt/httprouter/httprouter.go). And Hitch use httprouter interna directly, so difficult to swap to contrib.

httprouter is very common library, so I think it is not rare case. So if `contrib/internal/httputil` is public, we can care these case without hacky forkor adding minor contrib. 

How do you think ?

Thanks.

**Comment by gbbr** [comment]
I think that's a good idea. I don't see any issues with it. Since it's strongly related to the `net/http` package, I'd say `contrib/net/http` is the best place for it.

**Comment by soh335** [comment]
@gbbr Thanks ! Can I contribute ?

**Comment by knusbaum** [comment]
@soh335 Contributions are very welcome, thanks!

Since this proposal is accepted and we basically know what we're going to do, please take a look at the [Contribution Guidelines](https://github.com/DataDog/dd-trace-go/blob/v1/CONTRIBUTING.md) and open a PR when you're ready.

**Comment by soh335** [comment]
@gbbr @knusbaum Should I merge `contrib/internal/httputil` to `contrib/net/http` ? or move to `contrib/net/http/httputil` ?
If the first one, some contrib package use `net/http` and `contrib/internal/httputil`, so I want to know what alias name for `contrib/net/http` is good.

**Comment by soh335** [comment]
@gbbr @knusbaum how about ?

**Comment by gbbr** [comment]
I'd vote for keeping it in `net/http`.
