### ISSUE TITLE
gRPC `peer.address` in traces

### ISSUE THREAD

**Issue by ishworg** [DataDog/dd-trace-go#1067]
Can someone tell me what that value should be?

Should we expect the value to be HTTP/1.1'esq `X-Real-IP` / `X-Forwarded-For` or should should it be `127.0.0.1:<ephemeral_source_port>` ?

I am seeing the latter in my traces which is _definitely_ not what we are after :) 

![image](https://user-images.githubusercontent.com/31202986/143564824-71722d6d-6d2e-4312-9b36-09d01e87fc44.png)

If I put a k8s ingress controller in front (nginx), I see the value of `peer.address` as the k8s worker node hosting the Nginx ingress which also not what we are after :)

![image](https://user-images.githubusercontent.com/31202986/143565062-d77faae0-b6c9-41dc-8bd6-1c7219c13fc3.png)

We are not doing anything special in the gRPC server - just creating traces and sending them away to datadog agent.
We would like to get the IP of the `X-Real` or `XFF` in there. How to cook this fish? Thank you!

**Comment by Julio-Guerra** [comment]
Hello @ishworg,

Our gRPC tracing doesn't add this span tag. But it is indeed the peer TCP address connecting to your service.

Regarding the actual client IP address taken from IP headers, this is something Application Security (AppSec) adds to the traces.

If you are interested by this, I will be working on adding AppSec to our gRPC tracing in the next two weeks to come. Once ready, it will report the IP headers only when an attack is found and Datadog's backend enriches the traces with `actor.ip` automatically. We are not planning to do this in the Go library for now.

If you want it all the time, regardless of AppSec, I suggest you to simply add a tag to your gRPC span via an interceptor, based on the IP headers you want.

**Comment by knusbaum** [comment]
@ishworg I am closing this as solved. If you have further questions about this, please feel free to reopen this or open a new issue.
