### ISSUE TITLE
Wrong response writer is being returned in func wrapResponseWriter

### ISSUE THREAD

**Issue by renanrt** [DataDog/dd-trace-go#1076]
Hello friends,

We currently have a specific type that implements `http.ResponseWriter`.

As a result, [this](https://github.com/DataDog/dd-trace-go/blob/9046c68111f5fb69400bfa5912412eb65ef8883b/contrib/internal/httputil/trace_gen.go#L24) func returns our own type instead of the traced response writer ([this](https://github.com/DataDog/dd-trace-go/blob/9046c68111f5fb69400bfa5912412eb65ef8883b/contrib/internal/httputil/trace.go#L62)).

If the type doesn't match any of `(Flusher, Pusher, CloseNotifier, Hijacker)` - can we return the traced response writer instead?

I have PR ready if you guys approve it.

**Comment by Julio-Guerra** [comment]
Hey @renanrt,

Sorry about that. It's a problem that got introduced in my last changes of it and the default return value should be the monitored writer `mw` indeed.

Happy to review your PR if it's ready 👍

**Comment by renanrt** [comment]
https://github.com/DataDog/dd-trace-go/pull/1078

**Comment by knusbaum** [comment]
Fixed in #1078
