### ISSUE TITLE
Missing container id with cgroup v2 + docker 20.10 and up

### ISSUE THREAD

**Issue by Julio-Guerra** [DataDog/dd-trace-go#1088]
See https://github.com/DataDog/dd-trace-rb/issues/1810
The system tests are covering this, but don't fail on our CI because docker isn't so up to date.
Running them locally make this [system test](https://github.com/DataDog/system-tests/blob/0137770c4549d5e392da3767b93cb3df04ba93d7/tests/test_data_integrity.py#L17) fail.

**Comment by knusbaum** [comment]
Acked and scheduled.

**Comment by knusbaum** [comment]
See: https://github.com/DataDog/datadog-agent/pull/11584

**Comment by katiehockman** [comment]
@knusbaum should this be closed?

**Comment by knusbaum** [comment]
Yes, I believe so.
