### ISSUE TITLE
proposal: extend contrib/gocql/gocql to support more gocql operations (Scanner and Batch)

### ISSUE THREAD

**Issue by jack-at-circle** [DataDog/dd-trace-go#1099]
I've started using cassandra databases more and wanted to add tracing to my queries. The `contrib/gocql/gocql` package supports some operations but it does not provide enough features to trace all the gocql operations. Particularly: the package does not support tracing calls to `ExecuteBatch` or using a `Scanner` derived from the `Iter` struct (calling `Scanner.Err` does not close the `Iter` trace). There may be other operations that the `contrib/gocql/gocql` does not support.

**Comment by jack-at-circle** [comment]
I implemented a wrapper that gives some of the functionality that I needed, but I'd rather use the maintained package than my wrapper. I can open a draft pr at some point soon with the changes I made, at least as a starting point for this work... I'll go read the contributing guidelines first : )

**Comment by jack-at-circle** [comment]
@gbbr I opened a pr with changes that add initial batch and scanner support: https://github.com/DataDog/dd-trace-go/pull/1111

**Comment by gbbr** [comment]
That was quick & pro. Thanks a lot 🙂
