### ISSUE TITLE
proposal: contrib: add integration for github.com/gogearbox/gearbox

### ISSUE THREAD

**Issue by fenriz07** [DataDog/dd-trace-go#1119]
Hi.

I hope that all team are good. Happy new year. I open this issue with to Idea to make a contrib package for suport apm in gearbox web framework: You can see the web framework in this link: [gearbox](https://github.com/gogearbox/gearbox)

The idea is will make a middleware for open the tracer when some handler was invoke.

PR: [1116](https://github.com/DataDog/dd-trace-go/pull/1116)

Regards.

**Comment by zarirhamza** [comment]
Hello! We're closing this issue due to it becoming stale, but if you want to come back to this in the future, feel free to open another issue! Thank you!
