### ISSUE TITLE
contrib/sqltraced: statement getting span from the wrong context

### ISSUE THREAD

**Issue by gsblue** [DataDog/dd-trace-go#113]
Noticed `tracedStmt` https://github.com/DataDog/dd-trace-go/blob/master/tracer/contrib/sqltraced/sqltraced.go#L324 is getting span from statement's context which gets used to prepare the driver statement. 

I believe it should be using the context passed into `ExecuteContext` or `QueryContext` method, as prepared statements may be used for multiple requests.

**Comment by gbbr** [comment]
You are right, addressing this in #167. Sorry for the delayed response.
