### ISSUE TITLE
Version 1.35.0 does not respect `DD_AGENT_HOST` var for feature loading

### ISSUE THREAD

**Issue by markgmilner** [DataDog/dd-trace-go#1132]
We noticed that in the new version (1.35.0) that we get a new error message when only setting the agent host address via the `DD_AGENT_HOST` environment variable:

```
2022/01/19 18:19:13 Datadog Tracer v1.35.0 ERROR: Loading features: Get "http://localhost:8126/info": dial tcp 127.0.0.1:8126: connect: connection refused (occurred: 19 Jan 22 18:18 UTC)
```
For clarity, we are setting the `DD_AGENT_HOST` to an ip other than localhost.

It looks like the call to get info does not respect the `DD_AGENT_HOST` variable, and only works when the tracer uses the `withAgentAddr` start option.

It looks like this is coming from changes to the `ddtrace/tracer/option.go` file in the following pr:
https://github.com/DataDog/dd-trace-go/pull/1048

I imagine this will break features for clients that set the agent address only using the environment variable and not with the `withAgentAddr` start option.

**Comment by gbbr** [comment]
I think this was just fixed in https://github.com/DataDog/dd-trace-go/pull/1126. Can you confirm? If so, please close the issue and we will be releasing this soon. If it's more urgent and blocking you, please let me know.

**Comment by JHartman5** [comment]
I had the same issue; I tested https://github.com/DataDog/dd-trace-go/pull/1126 and it worked perfectly for me (in fact, I had more or less the same change queued up in a local fork before I found this issue).

Do you have some idea when this will make its way into a release?

**Comment by gbbr** [comment]
Thanks for confirming! The release should be out soon. We have started the process. I predict 1-2 weeks.

I'm going to close the issue since it is fixed, but if there are any further concerns please feel free to continue commenting.
