### ISSUE TITLE
On including ddtrace library, Go Services Bazel build fails

### ISSUE THREAD

**Issue by vhganga** [DataDog/dd-trace-go#1147]
**Describe what happened:**
We are trying to add DataDog Custom Metrics by referring to https://docs.datadoghq.com/tracing/setup_overview/setup/go/?tab=containers for the Golang Microservices by including following code snippet with import as mentioned in first line

import ( "gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer" )

	tracer.Start(
		tracer.WithEnv("prod"),
		tracer.WithService("test-go"),
		tracer.WithServiceVersion("abc123"),
	)
 
I have added ddtrace library dependency in go_deps.bzl as following 

    go_repository(
        name = "in_gopkg_datadog_dd_trace_go_v1",
        importpath = "gopkg.in/DataDog/dd-trace-go.v1",
        sum = "h1:7/gxjN9TuCrGlMEISIk9I9NHeqm+xDXP2C6qw450D2w=",
        version = "v1.35.0",
    )

I am getting build error as following: 

RROR: /private/var/tmp/_bazel_gangavh/b7b51011abc161034e1e1e818ba502ef/external/com_github_datadog_sketches_go/ddsketch/store/BUILD.bazel:3:11: GoCompilePkg external/com_github_datadog_sketches_go/ddsketch/store/store.a failed: (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_arm64 -src external/com_github_datadog_sketches_go/ddsketch/store/bin.go -src ... (remaining 21 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: missing strict dependencies:
        /private/var/tmp/_bazel_gangavh/b7b51011abc161034e1e1e818ba502ef/sandbox/darwin-sandbox/661/execroot/ss_mservices/external/com_github_datadog_sketches_go/ddsketch/store/dense_store.go: import of "github.com/DataDog/sketches-go/ddsketch/pb/sketchpb"
        /private/var/tmp/_bazel_gangavh/b7b51011abc161034e1e1e818ba502ef/sandbox/darwin-sandbox/661/execroot/ss_mservices/external/com_github_datadog_sketches_go/ddsketch/store/store.go: import of "github.com/DataDog/sketches-go/ddsketch/pb/sketchpb"

 I do see URL github.com/DataDog/sketches-go/ddsketch/pb/sketchpb not reachable
 
**Describe what you expected:**

Build should complete without errors.

**Steps to reproduce the issue:**

**Comment by vhganga** [comment]
Hi All, after including sketches_go library dependency, we get different error as following:
ERROR: /private/var/tmp/_bazel_gangavh/b7b51011abc161034e1e1e818ba502ef/external/com_github_datadog_sketches_go/ddsketch/mapping/BUILD.bazel:3:11: GoCompilePkg external/com_github_datadog_sketches_go/ddsketch/mapping/mapping.a failed: (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_arm64 -src external/com_github_datadog_sketches_go/ddsketch/mapping/bit_operation_helper.go -src ... (remaining 21 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: missing strict dependencies:
        /private/var/tmp/_bazel_gangavh/b7b51011abc161034e1e1e818ba502ef/sandbox/darwin-sandbox/3772/execroot/ss_mservices/external/com_github_datadog_sketches_go/ddsketch/mapping/cubically_interpolated_mapping.go: import of "github.com/DataDog/sketches-go/ddsketch/pb/sketchpb"
        /private/var/tmp/_bazel_gangavh/b7b51011abc161034e1e1e818ba502ef/sandbox/darwin-sandbox/3772/execroot/ss_mservices/external/com_github_datadog_sketches_go/ddsketch/mapping/index_mapping.go: import of "github.com/DataDog/sketches-go/ddsketch/pb/sketchpb"
        /private/var/tmp/_bazel_gangavh/b7b51011abc161034e1e1e818ba502ef/sandbox/darwin-sandbox/3772/execroot/ss_mservices/external/com_github_datadog_sketches_go/ddsketch/mapping/linearly_interpolated_mapping.go: import of "github.com/DataDog/sketches-go/ddsketch/pb/sketchpb"
        /private/var/tmp/_bazel_gangavh/b7b51011abc161034e1e1e818ba502ef/sandbox/darwin-sandbox/3772/execroot/ss_mservices/external/com_github_datadog_sketches_go/ddsketch/mapping/logarithmic_mapping.go: import of "github.com/DataDog/sketches-go/ddsketch/pb/sketchpb"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
INFO: Elapsed time: 67.021s, Critical Path: 24.60s
INFO: 1132 processes: 124 internal, 1008 darwin-sandbox.
FAILED: Build did NOT complete successfully

**Comment by jacobfoard** [comment]
I'm able to use bazel with the tracer, I just needed to disable the automatic proto building since the `*.pb.go` files are committed to the repo.

```bzl
    go_repository(
        name = "com_github_datadog_sketches_go",
        build_file_proto_mode = "disable",
        importpath = "github.com/DataDog/sketches-go",
        sum = "h1:VOaiZiifXh4VRoOz3ZNoFQAPRAZpppH1FPvcarsvBqg=",
        version = "v1.3.0",
    )
```

**Comment by vhganga** [comment]
Thank you @jacobfoard , I am getting build error as following:
imports "github.com/DataDog/sketches-go/ddsketch/pb/sketchpb" which matches multiple rules: //ddsketch/pb/sketchpb and //ddsketch/pb:sketchpb. # gazelle:resolve may be used to disambiguate
