### ISSUE TITLE
proposal: contrib/net/http: make roundTripper propagation (inject, extract) optional

### ISSUE THREAD

**Issue by rangelrealecb** [DataDog/dd-trace-go#1166]
I need to make an http call to a vendor, and I would like to trace this call (and its parameters), but using the current roundTripper would "leak" the trace_id / parent_id as headers, as they are inject automatically on the call.

I propose adding an option (true by default):

```go
func RTWithPropagation(propagation bool) RoundTripperOption {
	return func(cfg *roundTripperConfig) {
		cfg.propagation = propagation
	}
}
```

and check this before injecting

```go
        if rt.cfg.propagation {
	    err = tracer.Inject(span.Context(), tracer.HTTPHeadersCarrier(req.Header))
            ...
        }
```

I can submit a PR if it's ok.

**Comment by dianashevchenko** [comment]
Hi @rangelrealecb , sure, feel free to submit a PR. We'll do our best to review it in timely manner 🙌
