### ISSUE TITLE
service.name tag should not replace service

### ISSUE THREAD

**Issue by theory** [DataDog/dd-trace-go#1173]
I set up these two environment variables:

```
DD_SERVICE=greet-howdy
DD_TAGS="service.namespace:greet,service.name:howdy"
```

And was surprised to find that my traces all had `service:howdy` instead of `service:greet-howdy`, and that `service.name` did not exist. Seems as though the `service.name` tag replaces the `service` tag, even if the `service` tag is set separately.

ISTM that `service.name` should not replace an explicit setting of `service`, and that even if it sets `service` it should still be included as a tag.

I suggest the expected service setting, given various `DD_SERVICE` AND `DD_TAGS` configs, be as follows:

DD_SERVICE |     DD_TAGS      | service
-----------|------------------|---------
 howdy     |                  | howdy
 howdy     | service.name:bye | howdy
  &nbsp;         | service.name:bye | bye

**Comment by dianashevchenko** [comment]
@theory I have to confirm that this is expected behaviour, and as of now we do not plan to change the logic to accept `service.name` as a tag

**Comment by theory** [comment]
I would like to argue that `service.name` should not replace `service`. That just seems weird. Perhaps there is a reason for it, in which case some documentation would be welcome. Thanks!
