### ISSUE TITLE
proposal: contrib/gofiber/fiber.v2: make resource name use route instead of current path

### ISSUE THREAD

**Issue by AsgerNoer** [DataDog/dd-trace-go#1197]
## Issue
With the current implementation in the fiber middleware the resource name is set by the following logic that results in very obfuscated endpoint tracing in the Datadog client. The current implementation is alright for static paths, but when path parameters is included, it gets messy.

https://github.com/DataDog/dd-trace-go/blob/85593c8fdac6ecbdcf8b4554eb06c57e9329ff44/contrib/gofiber/fiber.v2/fiber.go#L51-L56

### Example
Let's say that you have a resource on `https://example.com/users/:userID/orders/:orderID`. Then with every new user results in a new endpoint.

| Name | Requests |
| ---     |---   |
|POST /users/1/orders/1| 1|
|POST /users/1/orders/2| 1|
|POST /users/1/orders/3| 1|
|POST /users/2/orders/1| 1|
|...|...|

## Proposal
My proposal is that this logic should be changed to use the routing path instead of the current path. This would result in a much easier overview. It could even be extended with an _option function_ in to automatically set the url path parameters as span tags.

```go
route := c.Route()

// Setting the route path as resource name
resourceName := c.Method() + " " + route.Path
span.SetTag(ext.ResourceName, resourceName)

// Dynamically set the span tags based on the route parameters
if cfg.withUrlParamsSpanTags {
	for _, parameter := range route.Params {
		span.SetTag(parameter, c.Params(parameter))
	}
}
```

### Output
With this change the above example would result in the following where you can filter on the span tags

| Name | Requests |
| ---     |---   |
|POST /users/:userID/orders/:orderID| 4|
|...|...|

**Comment by AsgerNoer** [comment]
For backwards compatibility the changed resource naming logic could be wrapped in a config flag/option function, so it'll default to the old way of naming resources but with the option of using the route name generation.

**Comment by knusbaum** [comment]
@AsgerNoer Yes, we should include the route, not the actual path. That's how we do other HTTP integrations and we should do the same here.

**Comment by AsgerNoer** [comment]
@knusbaum I've opened a PR with a fix, also including the path parameter extraction.
