### ISSUE TITLE
undefined: metadata.FromContext

### ISSUE THREAD

**Issue by jontonsoup** [DataDog/dd-trace-go#120]
Hi friends, 

I am getting this error: 

```
github.com/DataDog/dd-trace-go/tracer/contrib/tracegrpc/grpc.go:112:15: undefined: metadata.FromContext
```

Seems like the dependancies have changed?

**Comment by palazzem** [comment]
Hello @jontonsoup! I think a breaking change was introduced in `grpc` library (tracking issue was: https://github.com/grpc/grpc-go/issues/1178). We've fixed our compatibility with their latest versions with this commit: https://github.com/DataDog/dd-trace-go/commit/69df0044e0523188dcf62fbf38041e4bb466cf77

Do you confirm that with the latest version (0.5.1) this is happening again? Anyway one issue we're tracking is having a stable compatibility matrix. In that way we're sure to provide a wide compatibility to our contrib library.
