### ISSUE TITLE
contrib/gorm.io/gorm.v1 - Duplicate traces

### ISSUE THREAD

**Issue by andysnowden** [DataDog/dd-trace-go#1216]
Been looking into the gorm v2 tracing and it seems every SQL query via GORM generates two mostly duplicate traces.  This even happens using the library example.  Is this the intended behavior?

```go
	// Register augments the provided driver with tracing, enabling it to be loaded by gormtrace.Open.
	sqltrace.Register("pgx", &stdlib.Driver{}, sqltrace.WithServiceName("my-service"))
	sqlDb, err := sqltrace.Open("pgx", "postgres://dbuser:dbpass@localhost/testdb?sslmode=disable")
	if err != nil {
		log.Fatal(err)
	}

	db, err := gormtrace.Open(postgres.New(postgres.Config{Conn: sqlDb}), &gorm.Config{})
	if err != nil {
		log.Fatal(err)
	}
```

![0ZJIGcs](https://user-images.githubusercontent.com/43858400/157987863-8a7c14ed-b8da-4795-9d24-469fac5a858b.png)

Are gorm and pgx each providing a trace? if so can I disable one or the other?

**Comment by dominicfollett** [comment]
I am noticing the same thing in my traces. I tried to adjust by removing sqltrace altogether, but I don't know yet if it will impact the quality of my tracing. E.g.

```
DB, err = gormtrace.Open(postgres.New(postgres.Config{DSN: dsn}), &gorm.Config{})
```

I still see the `gorm.query` trace. But without the parent `pgx.query` trace. Hope this helps.
