### ISSUE TITLE
go-chi unknown revision v4.0.0-rc1

### ISSUE THREAD

**Issue by chchgb** [DataDog/dd-trace-go#1220]
in go.mod, it require github.com/go-chi/chi/v4 v4.0.0-rc1

but I met blow issue, who can help me to handle it. thx~

go list -m: github.com/go-chi/chi/v4@v4.0.0-rc1: invalid version: unknown revision v4.0.0-rc1
go list -m: gopkg.in/DataDog/dd-trace-go.v1@v1.37.0 requires
	github.com/go-chi/chi/v4@v4.0.0-rc1: reading github.com/go-chi/chi/go.mod at revision v4.0.0-rc1: unknown revision v4.0.0-rc1

**Comment by Julio-Guerra** [comment]
Sounds good to me. Let me open a PR for that.

**Comment by jontonsoup** [comment]
is this fix live? it appears v1 is broken right now

**Comment by Hellzy** [comment]
@jontonsoup could you please try and check if it appears broken using the [latest](https://github.com/DataDog/dd-trace-go/releases/tag/v1.38.0-rc.2) dd-trace release candidate? (v1.38.0-rc.2)?

**Comment by jontonsoup** [comment]
it is fixed. Thanks!

**Comment by kodams** [comment]
Hi, @Hellzy 

`replace` of go.mod only works at local when `go get` is used.
I have to append `replace` in all vertical dependency repos.
(In other words, I have many microservices and a central framework used this....)

Do you have a plan for an upgrade to v1.37.2 for fixed it?

**Comment by Hellzy** [comment]
Hi @kodams, do those repos use a specific version or do they fetch the latest?
If it's the later, v1.38.0 has been released and includes the fix we discussed above.
Also ping @jontonsoup, you should be fine getting rid of the specific RC and using the latest release now.

**Comment by kodams** [comment]
Hi, @Hellzy. Sorry for the late.

These repos use `DataDog/dd-trace-go.v1 v1.37.0`. But the version is depend by `go-chi/chi/v4.0.0-rc1`.
I want to use the version if I can.
