### ISSUE TITLE
Nil transport should default to http.DefaultTransport

### ISSUE THREAD

**Issue by dillonstreator** [DataDog/dd-trace-go#1223]
If a nil transport is provided, could we default to the http.DefaultTransport for the base?

https://github.com/DataDog/dd-trace-go/blob/b5c1e8daa1b66e09249245c728bb0459ad7ef645/contrib/net/http/roundtripper.go#L88-L91

**Comment by ajgajg1134** [comment]
Hello! Can you explain a bit more what your use case here is?
