### ISSUE TITLE
Feature Request: Add req.RequestID to aws tracer tag

### ISSUE THREAD

**Issue by yulius-take2** [DataDog/dd-trace-go#1258]
In the code referenced here, add the aws request id
https://github.com/DataDog/dd-trace-go/blob/c92a84c045f7837b5bbdd34dc96a40ed4915c46c/contrib/aws/aws-sdk-go/aws/aws.go#L80

`span.SetTag(tagAWSRequestID, req.RequestID),`

where `tagAWSRequstID` is defined as `aws.request_id`

**Comment by ajgajg1134** [comment]
This seems like a perfectly fine change to me! If you'd like to put up a PR with these change we'll try to review it quickly. Otherwise I'll add it to our enhancement backlog, Thanks!

**Comment by yulius-take2** [comment]
here's the pull request
https://github.com/DataDog/dd-trace-go/pull/1266/files

**Comment by zarirhamza** [comment]
Closed due to merged PR. If there are related problems, please open a separate issue.
