### ISSUE TITLE
Synthetic Test cannot see the APM trace

### ISSUE THREAD

**Issue by juran-compass** [DataDog/dd-trace-go#1270]
Hi there,

I use `gopkg.in/DataDog/dd-trace-go.v1 v1.27.1` and go version is 1.15
When I did synthetic testing, it cannot link any trace on it.
<img width="1083" alt="Screen Shot 2022-05-02 at 10 31 15 AM" src="https://user-images.githubusercontent.com/57373941/166295919-67669de7-ab1b-4bc6-95a1-3e204ef511f5.png">
Does anyone know why?

Thanks
Ran

**Comment by mackjmr** [comment]
Hey [@juran-compass](https://github.com/juran-compass), there was an issue where the tracer mishandled the `x-datadog-parent-id` header set by synthetics.
A fix was shipped in tracer v.1.39. Please see: [#1285](https://github.com/DataDog/dd-trace-go/pull/1285). 
Can you upgrade to v.1.39 and confirm this solves your issue ?

**Comment by ajgajg1134** [comment]
Hello 👋  We're going to close this for inactivity.

If you're still having issues with this feel free to open an issue with [Datadog Support](https://www.datadoghq.com/support/) (or if you've identified a bug in dd-trace-go, re-open this issue!)
