### ISSUE TITLE
When DD_AGENT_HOST is set, tracer ignores `WithAgentAddr` start option

### ISSUE THREAD

**Issue by alexbolgov** [DataDog/dd-trace-go#1280]
Hello!

`WithAgentAddr` is supposed to set agent address, but environment variable `DD_AGENT_HOST` takes precedence and `WithAgentAddr` option is ignored

This behaviour is not consistent with behaviour of other pairs of environment variables and `StartOptions`: for most (if not all) pairs of `StartOption` + `env`, the `StartOption` takes precedence.

A proposed change is to let `WithAgentAddr` to take precedence over `DD_AGENT_HOST`

**Comment by dianashevchenko** [comment]
@alexbolgov it was addressed in #1232, will be in the next release 🙌
