### ISSUE TITLE
proposal: Add http.host in HTTP client tracing

### ISSUE THREAD

**Issue by lamanotrama** [DataDog/dd-trace-go#1289]
As well as HTTP server.
- https://github.com/DataDog/dd-trace-go/issues/646

req.URL.Path is currently tagged in the span of requests from clients, but req.URL.Host is not.
Of course I know that this information can be injected with the WithBefore option, but I think it would be more convenient if it were always given by default.

**Comment by zarirhamza** [comment]
This issue has been solved via [#2016](https://github.com/DataDog/dd-trace-go/pull/2016). The PR adds both host and port tags for the entire `net/http` integration. Feel free to reopen another issue if there are further concerns.

**Comment by lamanotrama** [comment]
Thank you!
