### ISSUE TITLE
question: Distributed tracing with NATS (Kafka, etc)

### ISSUE THREAD

**Issue by SympleSynz** [DataDog/dd-trace-go#1299]
Hello,

I'm working on a project where we use NATS to pass events between services.  For instance: 
- Service A publishes an event to NATS
- Service B is a subscriber/consumer of that specific event and picks up the event and processes it

When we were using Zipkin, we were able to extract the `TraceId` and add it as a string field on the NATS payload. We would then json.marshal the payload, publish it to NATS, and the subscriber on the other end would reattach the `traceId` to the go context.

Is there a way to do the same thing with DD Tracing?  Is there a way to break down the `SpanContext` so that I can rebuild it in the other service?  I looked at `Inject` and `Extract`, but the documentation and examples only talk about using http headers.

**Comment by SympleSynz** [comment]
This was super helpful feedback @ajgajg1134 Thank you.  After talking to the team, we'll attempt to go with your suggestion and implement a special carrier.
Yes, https://github.com/nats-io/nats.go is the library we are using.

**Comment by darccio** [comment]
`dd-trace-go` doesn't have native integration for NATS, but the workaround detailed before still works. If somebody needs to implement this, they can use this example from Orchestrion as inspiration: https://github.com/DataDog/orchestrion/blob/main/internal/traceutil/natscarrier.go
