### ISSUE TITLE
Request: example for custom tags for `contrib/gorm.io`

### ISSUE THREAD

**Issue by duxing** [DataDog/dd-trace-go#1308]
hi DataDog team,

`dd-trace-go` supports [`gorm@v1`](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/contrib/jinzhu/gorm) and [`gorm@v2`](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1@v1.38.1/contrib/gorm.io/gorm.v1) and I'm comparing the DataDog instrumentation implementation for both versions, trying to understand what would be the impact of upgrading my services from `gorm@v1` to `gorm@v2`.

one thing I noticed is: instrumentation lib for `gorm@v1` comes with an option to add custom tag: [`WithCustomTag`](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/contrib/jinzhu/gorm#WithCustomTag), and I don't see an equivalent option in `gorm@v2` ([reference](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1@v1.38.1/contrib/gorm.io/gorm.v1))

would it be possible for you to share an example of how to add custom tags using `dd-trace-go` for `gorm@v2`?  if it's not supported yet, would it be possible to add to `dd-trace-go/contrib/gorm.io`?

Thanks in advance!

**Comment by duxing** [comment]
seems like gorm@v2 instrumentation doesn't have that option available: [reference](https://github.com/DataDog/dd-trace-go/blob/v1/contrib/gorm.io/gorm.v1/gorm.go#L113)

(equivalent of `gorm@v1` [implementation](https://github.com/DataDog/dd-trace-go/blob/v1/contrib/jinzhu/gorm/gorm.go#L132) is missing)

[`contrib/database/sql`] contains a method for specifying span tags: 
https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/contrib/database/sql#WithSpanTags. I guess that's an option?

**Comment by zarirhamza** [comment]
Closed due to merged PR #1359. If there are related problems, please open a separate issue.
