### ISSUE TITLE
contrib/database/sql: Add WithErrorCheck option

### ISSUE THREAD

**Issue by soh335** [DataDog/dd-trace-go#1314]
Hi, it is same feature with https://github.com/DataDog/dd-trace-go/issues/805.
Sometime, we need to ignore specific error from contrib/database/sql.

In our case, need to ignore insert error like that `Error 1062: Duplicate entry 'xxx' for key 'PRIMARY'`.

So need `WithErrorCheck` option. How about ?

**Comment by gbbr** [comment]
Fine by me!

**Comment by soh335** [comment]
@gbbr Thank you for quick response. Ready to review p-r https://github.com/DataDog/dd-trace-go/pull/1315 👍
