### ISSUE TITLE
contrib/gofiber/fiber.v2: Flaky TestCustomError

### ISSUE THREAD

**Issue by nsrip-dd** [DataDog/dd-trace-go#1322]
Example failure: https://app.circleci.com/pipelines/github/DataDog/dd-trace-go/3983/workflows/52c748ca-8a78-4ce3-9bfd-75e2876c837e/jobs/28208
Passing pipeline on the same commit: https://app.circleci.com/pipelines/github/DataDog/dd-trace-go/3982/workflows/45a9bf15-36bf-428e-9481-839982c8db73/jobs/28207?invite=true#step-121-34

The test fails on [this line](https://github.com/DataDog/dd-trace-go/blob/3528a0d641097d68b3b9e750a51bd8f79c72d360/contrib/gofiber/fiber.v2/fiber_test.go#L146) with a timeout error after `100ms`. This is probably a case of an oversubscribed CI runner taking longer than expected. Maybe a longer timeout is the answer?

**Comment by gbbr** [comment]
You're probably right. The default timeout for `route.Test` is 1s. I propose we try going with the default. 100ms was likely too short.
