### ISSUE TITLE
contrib/net/http: tag full URL on the RoundTripper

### ISSUE THREAD

**Issue by andrea-vasapollo-cko** [DataDog/dd-trace-go#1345]
Hello, sorry I read at a later point about how to open a PR.
We would like to have the full URL on the tag on the net/http/roundtripper.
The full URL is already used on the AWS session [url](https://github.com/DataDog/dd-trace-go/blob/f1b2983aa4b757e7607a7d2b330b7f4f872d7543/contrib/aws/aws-sdk-go/aws/aws.go#L67).
I think this clarify better the destination of the request instead of the just PATH.
I opened a PR to change that https://github.com/DataDog/dd-trace-go/pull/1344

**Comment by gbbr** [comment]
Hi there! This is being addressed in https://github.com/DataDog/dd-trace-go/pull/1350

**Comment by andrea-vasapollo-cko** [comment]
ah nice thanks @gbbr so it will be add also the http roundtrip as well correct? because this https://github.com/DataDog/dd-trace-go/pull/1344/files it will set the full URL on the http client

**Comment by gbbr** [comment]
Sure thing!

That PR is going to implement our internal cross-language policy for the `http.url` tag. If interested, please watch it and comment there to ask questions regarding the implementation because the author has the most familiarity with the issue. 

I recommend you close your PR and work on this internal one instead.

**Comment by Hellzy** [comment]
I modified roundtripper a bit to make use of the new internal/httptrace utilities for span tags normalisation. http.url should hold the full URL once https://github.com/DataDog/dd-trace-go/pull/1350 gets merged.

**Comment by Hellzy** [comment]
@andrea-vasapollo-cko I cherry-picked your change on https://github.com/DataDog/dd-trace-go/pull/1350, let me know if that works for you.

**Comment by andrea-vasapollo-cko** [comment]
All your mate thanks for that guys
