### ISSUE TITLE
go.mod: upgrade dependencies to latest version to avoid vulnerabilities

### ISSUE THREAD

**Issue by mswathi-tw** [DataDog/dd-trace-go#1368]
We are using the latest version of [gopkg.in/DataDog/dd-trace-go.v1@v1.39.1] which internally uses the following libraries:

gopkg.in/DataDog/dd-trace-go.v1@v1.39.0 › github.com/emicklei/go-restful@v0.0.0-20170410110728-ff4f55a20633
gopkg.in/DataDog/dd-trace-go.v1@v1.39.0 › github.com/labstack/echo@v3.3.10+incompatible
gopkg.in/DataDog/dd-trace-go.v1@v1.39.0 › github.com/tidwall/buntdb@v1.2.0 › github.com/tidwall/gjson@v1.6.8
gopkg.in/DataDog/dd-trace-go.v1@v1.39.0 › github.com/hashicorp/memberlist@v0.1.6 › github.com/miekg/dns@v1.0.14

This has introduced certain snyk vulnerabilities and in order to solve this issue following library version has to upgraded to latest.

github.com/emicklei/go-restful@3.8.0
github.com/labstack/echo@4.2.0
github.com/tidwall/buntdb@v1.2.9
github.com/hashicorp/memberlist@v0.3.1

Can you please upgrade it.

**Comment by katiehockman** [comment]
@mswathi-tw We require the lowest possible version of each dependency in our `go.mod` file which has the features needed for our library to work. The versions in the `go.mod` file are the *minimum* required version to use our library, but anyone who uses gopkg.in/DataDog/dd-trace-go.v1 can raise the version in the `go.mod` file of their project as they feel appropriate.

**Comment by dalmarcolucas** [comment]
Hello! 

If I raise the version of one of the depencies in my go.mod, the "go mod tidy" command removes, as it seem not to consider being used. This seems to be happening only on datadog pkg.

**Comment by dalmarcolucas** [comment]
It is considered as if there is no dependency:

![image](https://user-images.githubusercontent.com/17152587/191839344-7cb47a22-13da-4513-8905-b05151188f58.png)


Indirect dependencies on other packages are correctly considered:

![image](https://user-images.githubusercontent.com/17152587/191839635-b910c06c-f3f5-40fe-af58-5ad8dd8ef68f.png)

**Comment by dalmarcolucas** [comment]
@mswathi-tw did you manage to update the dependencies?
