### ISSUE TITLE
contrib/elastic/go-elasticsearch: add support for elasticsearch v8

### ISSUE THREAD

**Issue by xrn** [DataDog/dd-trace-go#1370]
Hey,

As new ES were released I would like to be able to use DD Tracing for it. Following fresh PR - https://github.com/DataDog/dd-trace-go/pull/1017 I am able to prepare new one. 

Following https://www.elastic.co/support/eol - would be great to add ES8 support and deprecate ES6 (EOL 2022-02-10)

My PR: https://github.com/DataDog/dd-trace-go/pull/1363

**Comment by xrn** [comment]
@knusbaum can you take a look on this?

**Comment by dianashevchenko** [comment]
@xrn @ajgajg1134 will look at this shortly, thanks for reaching out 🙌

**Comment by VJean** [comment]
👋 FYI I opened a follow-up Pull Request here, which has been merged, and added to the `v.1.49.0` milestone: #1763

**Comment by zarirhamza** [comment]
Closed due to merged PR. If there are related problems, please open a separate issue.
