### ISSUE TITLE
What is the difference between StartSpanFromContext and StartSpan with ChildOf option?

### ISSUE THREAD

**Issue by piavgh** [DataDog/dd-trace-go#1384]
Hi everyone,

What is the difference between 2 ways:
```
span := tracer.StartSpan("myOperation", tracer.ChildOf(parentSpan.Context()))
```

vs

```
span := tracer.StartSpanFromContext(parentSpan.Context(), "myOperation")
```

And what is the preferred way to use it?

Thanks

**Comment by ajgajg1134** [comment]
Hello @piavgh, there's no real functional difference between the two functions, they both will start a new span where their parent is `parentSpan`. As for preference I would say it's a matter of style, personally I think `StartSpanFromContext` reads a little more clearly as it follows the very common `context` is the first argument pattern, but it's a very minor difference.

The _only_ thing I can think of that's different is that `StartSpanFromContext` will always set the parent to the span contained in the first argument, even if an `ChildOf` option is passed. Hypothetically I can imagine a set of requirements where you always want a specific parent span, and also have some number of "StartSpanOptions" to pass in that may or may not have a "ChildOf" option. (But this is highly contrived and I doubt anyone has ever run into this) Docs here: https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1@v1.40.1/ddtrace/tracer#StartSpanFromContext

I know this is a bit confusing as the API has two different ways to do the same thing, it's something we're looking at improving should we release a `v2` version of the tracer. I'm going to close this, but feel free to re-open if you need more clarification or if you have an idea on how to make this clearer in our documentation! Thanks!
