### ISSUE TITLE
Opentracing propagator not compatible with legacy propagation

### ISSUE THREAD

**Issue by hamiltop** [DataDog/dd-trace-go#139]
In the opentracing code, https://github.com/DataDog/dd-trace-go/blob/master/opentracing/propagators.go#L34 we are writing a base16 version of the trace-id and parent-id, whereas in the non opentracing libraries we are expecting a base10 version of the trace-id: https://github.com/DataDog/dd-trace-rb/blob/6534aaf725bd17df0363340595ebf3fc741e673e/lib/ddtrace/propagation/distributed_headers.rb#L19

This means we can't get distributed traces between opentracing (golang) services and legacy (ruby) services.

**Comment by hamiltop** [comment]
https://github.com/DataDog/dd-trace-go/pull/140 has a fix

**Comment by gbbr** [comment]
Seems like this is fixed in #140. @hamiltop please feel free to re-open otherwise.
