### ISSUE TITLE
profiler upload does always wait a second before retrying upload

### ISSUE THREAD

**Issue by sumerc** [DataDog/dd-trace-go#1395]
Interestingly, I have spotted this while I was reading the code below:

```go
if rerr, ok := err.(*retriableError); ok {
	statsd.Count("datadog.profiling.go.upload_retry", 1, nil, 1)
	wait := time.Duration(rand.Int63n(p.cfg.period.Nanoseconds()))
	log.Error("Uploading profile failed: %v. Trying again in %s...", rerr, wait)
	p.interruptibleSleep(time.Second)
	continue
}
```

It seems that `wait` is not used anywhere. I think the line should be following?

```go
...
p.interruptibleSleep(wait * time.Nanosecond)
```

**Comment by nsrip-dd** [comment]
Thanks, great catch! It looks like the randomized `wait` was introduced in #827, but it was lost by #961. Yes, it should be `p.interruptibleSleep(wait * time.Nanosecond)` to match the pre-#961 behavior.
