### ISSUE TITLE
contrib/segmentio/kafka.go.v0: resource name using generic writer (Writing to multiple topics) has no topic name

### ISSUE THREAD

**Issue by spandedius** [DataDog/dd-trace-go#1397]
The produce topic resource name has no topic name when a writer uses topic name from kafka.message 
```
w := &kafka.Writer{
	Addr:     kafka.TCP("localhost:9092"),
    // NOTE: When Topic is not defined here, each Message must define it instead.
	Balancer: &kafka.LeastBytes{},
}
```
https://github.com/segmentio/kafka-go#writing-to-multiple-topics

I found that the kafka-go contrib lib uses writer's topic name only. 
```
opts := []tracer.StartSpanOption{
		tracer.ServiceName(w.cfg.producerServiceName),
		tracer.ResourceName("Produce Topic " + w.Writer.Topic),
		tracer.SpanType(ext.SpanTypeMessageProducer),
	}
```
https://github.com/DataDog/dd-trace-go/blob/bac1cbcfb52424b6de30169cfa0eedc703e5a9fd/contrib/segmentio/kafka.go.v0/kafka.go#L130

Can this be changed to use message topic name if writer's topic name is unavailable?

**Comment by dianashevchenko** [comment]
@spandedius thanks for the suggestion, I opened a PR for that 🙌

**Comment by spandedius** [comment]
> @spandedius thanks for the suggestion, I opened a PR for that 🙌

Thanks a lot @dianashevchenko
