### ISSUE TITLE
contrib/internal/httptrace uses "inet.af/netaddr" which in turns imports go4.org/unsafe/assume-no-moving-gc

### ISSUE THREAD

**Issue by mrkagelui** [DataDog/dd-trace-go#1405]
Hi,

My app failed the test on the recent Go 1.19 because of `go4.org/unsafe/assume-no-moving-gc`, or rather because the current version used in this lib is not the latest, kindly check history of https://github.com/go4org/unsafe-assume-no-moving-gc/blob/main/untested.go for more info.

Here's part of my `go mod why`:

```
# go4.org/unsafe/assume-no-moving-gc
...
gopkg.in/DataDog/dd-trace-go.v1/contrib/net/http
gopkg.in/DataDog/dd-trace-go.v1/contrib/internal/httptrace
inet.af/netaddr
go4.org/intern
go4.org/unsafe/assume-no-moving-gc
```

My question is: why is inet.af/netaddr used instead of the standard package "net"?

If we really need it, could we upgrade to the latest "inet.af/netaddr" to use the latest unsafe package? ref: https://github.com/inetaf/netaddr/commit/377050f8e01de48af5bf56e3f714d7f210f5f648

**Comment by Hellzy** [comment]
Hi @mrkagelui

> My question is: why is inet.af/netaddr used instead of the standard package "net"?

This package has several features that are interesting to us that std "net" doesn't have.
An example: https://github.com/DataDog/dd-trace-go/pull/1328#discussion_r893492940.

I'd say let's go ahead with the upgrade.

**Comment by mrkagelui** [comment]
thank you for the answer, will read

**Comment by Hellzy** [comment]
https://github.com/DataDog/dd-trace-go/pull/1406 was merged, closing. Thanks for this @mrkagelui.

**Comment by hbagdi** [comment]
Is there a release planned including this fix?

**Comment by mrkagelui** [comment]
> Is there a release planned including this fix?

I think there's a milestone in that associated PR that says 1.41.0

**Comment by hbagdi** [comment]
I'm not very familiar with this repository's development and release timelines.
Is it possible to get this shipped as part of the patch release?
We want to move to Go 1.19 and this issue holds that up. This is the last blocker for us and possibly others in the community.

**Comment by nsrip-dd** [comment]
We have tagged a release candidate for v1.41.0 which contains this fix:

```
go get gopkg.in/DataDog/dd-trace-go.v1@v1.41.0-rc.1
```

The full release should be out by the end of the week

**Comment by hbagdi** [comment]
Sweet. Thanks!

**Comment by mrkagelui** [comment]
> I'm not very familiar with this repository's development and release timelines. Is it possible to get this shipped as part of the patch release? We want to move to Go 1.19 and this issue holds that up. This is the last blocker for us and possibly others in the community.

an alternative is to force upgrade, `go get -u inet.af/netaddr`
