### ISSUE TITLE
Opentracing propagation should return ErrSpanContextNotFound if X-Datadog-Trace-Id header is missing.

### ISSUE THREAD

**Issue by hamiltop** [DataDog/dd-trace-go#141]
The basictracer example demonstrates this: https://github.com/opentracing/basictracer-go/blob/c7c0202a8a77f658aeb2193a27b6c0cfcc821038/propagation_ot.go#L96

The comment in the opentracing-go code: https://github.com/opentracing/opentracing-go/blob/master/propagation.go#L20

With the current code, a ParentId and TracerId of `0` is used and that is rejected by the datadog-apm agent with the following log line: `2018-01-02 23:25:06 ERROR (receiver.go:219) - dropping trace reason: invalid span Span[t_id:0,s_id:8489972898621406477,p_id:0,ser:...`

**Comment by hamiltop** [comment]
https://github.com/DataDog/dd-trace-go/pull/140 has a fix

**Comment by palazzem** [comment]
Thank you for reporting the issue @hamiltop ! we're going to review it as soon as possible!

**Comment by palazzem** [comment]
Fixed in #140. Thanks for reporting the issue!
