### ISSUE TITLE
tracer: support injection/extraction of w3c trace-context headers

### ISSUE THREAD

**Issue by mvisonneau** [DataDog/dd-trace-go#1413]
We currently support [both proprietary & b3 header formats](https://docs.datadoghq.com/tracing/trace_collection/custom_instrumentation/go/#b3-headers-extraction-and-injection). With opentelemetry using [w3c trace-context](https://www.w3.org/TR/trace-context) by default, I reckon it could be interesting to support it as well.

For instance, this could be particularily useful when 3rd party implementing opentelemetry does not permit end users to fallback on B3. [eg: etcd](https://github.com/etcd-io/etcd/blob/8aa6ae9bbb940fd5688a52835c123da7cb277b6b/server/embed/config_tracing.go#L73)

**Comment by mvisonneau** [comment]
FWIW, here is how the propagation seems to work for the opentelemetry lib: https://github.com/open-telemetry/opentelemetry-go/blob/main/propagation/trace_context.go

**Comment by katiehockman** [comment]
Thanks for the suggestion. We'll take a look and get back in touch.

**Comment by katiehockman** [comment]
We plan on doing this in the coming quarter or two, so we will mark this as accepted.

**Comment by shawkyHS** [comment]
@katiehockman Is there any update regarding this feature ?

**Comment by katiehockman** [comment]
@shawkyHS there are no updates currently, but this is a high priority goal for us, and the team will provide updates once work is underway. 👍

**Comment by knusbaum** [comment]
Support for parsing w3c headers has been merged, but full support is still underway, as we need to support 128-bit IDs, whereas we are currently only able to support 64-bit IDs.

https://github.com/DataDog/dd-trace-go/pull/1630

**Comment by katiehockman** [comment]
Here's the bug tracking 128 bit support: https://github.com/DataDog/dd-trace-go/issues/909

**Comment by katiehockman** [comment]
W3C trace context support was released in the latest dd-trace-go release (v1.47.0). As @knusbaum said, you may still experience challenges with 128-bit trace ids until we complete that work (which is underway).

**Comment by katiehockman** [comment]
128 bit trace ids and W3C trace context injection and extraction is now completed and released. If you experience any issues with either of these features, please file an issues with our [support team](https://www.datadoghq.com/support/) so we can investigate!
