### ISSUE TITLE
tracer: unaligned atomic operation causes panic

### ISSUE THREAD

**Issue by DylanRJohnston-FZ** [DataDog/dd-trace-go#1418]
I believe this to be related to the issue here https://github.com/DataDog/datadog-go/pull/260, as you can see from these logs, 
![image](https://user-images.githubusercontent.com/107019337/183841825-ba7b2d13-9c6c-44e3-b1f8-c455374aacb1.png) ddtrace panics here https://github.com/DataDog/dd-trace-go/blob/03a3099b20dbf91212e2f85d2b1a636da4c140d5/ddtrace/tracer/spancontext.go#L212 because https://github.com/DataDog/dd-trace-go/blob/03a3099b20dbf91212e2f85d2b1a636da4c140d5/ddtrace/tracer/spancontext.go#L164 is unaligned.

This is running in GCP on an n2 node.

**Comment by ajgajg1134** [comment]
Hello! Thanks for pointing this out to us. Elsewhere in datadog we've been moving to standardize on go.uber.com/atomic which should prevent these alignment errors. I've made an internal bug ticket for us to fix this.
