### ISSUE TITLE
contrib/mongo: make tagging of mongo query configurable

### ISSUE THREAD

**Issue by dkuerner** [DataDog/dd-trace-go#1422]
Currently, the implementation of the datadog instrumentation will marshal the complete CommandStartedEvent and tag it as mongodb query.  Can we add an option to the monitor to omit the mongodb query to prevent leaking sensitive information?

**Comment by katiehockman** [comment]
Thanks for filing this @dkuerner. We'll review and get back in touch on this issue.

**Comment by katiehockman** [comment]
The Agent does perform obfuscation for MongoDB queries today, is that not working at all, or is it insufficient?

Please reach out to https://www.datadoghq.com/support/ with as many details as you can, and they can help you look into this, and route back to us if needed. Thanks!
