### ISSUE TITLE
contrib/database/sql: error with mssql when using FETCH. mssql: The number of rows provided for a TOP or FETCH clauses row count parameter must be an integer.

### ISSUE THREAD

**Issue by darrenparkinson** [DataDog/dd-trace-go#1432]
When I add sqltrace to my code, e.g.:

```go
import (
    "database/sql"
    mssql "github.com/denisenkom/go-mssqldb"
)
...
sqltrace.Register("mssql", &mssql.Driver{})
db, err := sqltrace.Open("mssql", cfg.db.dsn)
```

I receive the following error which I don't normally receive:

```log
mssql: The number of rows provided for a TOP or FETCH clauses row count parameter must be an integer.
```

The SQL query I'm using looks a little like this:

```sql
SELECT count(*) OVER(), c.id, -- ...
FROM contacts c
OFFSET 0 ROWS
FETCH NEXT 100 ROWS ONLY;
```

Any thoughts on what I'm likely doing wrong greatly appreciated.
Many thanks.

**Comment by katiehockman** [comment]
Nothing with your setup looking obviously incorrect to me. What does `cfg.db.dsn` resolve to? It's [possible the DSN is not supported](https://github.com/DataDog/dd-trace-go/blob/main/contrib/database/sql/internal/dsn.go#L36).

My suggestion would be to reach out to the support team via https://www.datadoghq.com/support so they can gather all of the necessary details about your setup and try to help you resolve this.
