### ISSUE TITLE
contrib/net/http: NewServeMux does not respect WithResourceNamer option

### ISSUE THREAD

**Issue by mccutchen** [DataDog/dd-trace-go#1435]
The NewServeMux wrapper in the contrib/net/http package takes a slice of Options, but if the WithResoureNamer option is given it is ignored and a hard coded resource name is always used instead:
https://github.com/DataDog/dd-trace-go/blob/50bd7cebbd482284c99e41321495ac610990269a/contrib/net/http/http.go#L47-L53

**Comment by katiehockman** [comment]
Thanks for filing the issue and for the PR 👍
