### ISSUE TITLE
opentracting: no way to set Error

### ISSUE THREAD

**Issue by hamiltop** [DataDog/dd-trace-go#144]
We can set ErrorMsg, ErrorType, ErrorStack, but we can't set the Error boolean to mark the trace as an error.

A possible approach would be for it to be set automatically if any of those 3 tags.

**Comment by gbbr** [comment]
Lets instead change this API so we set an "Error" of type `error` and everything else will happen internally just as before.

**Comment by gbbr** [comment]
With this new change it will work more or less like before. For example:
```go
span.SetTag(ot.Error, err)
```
Will automatically set the values for message, type and stack. Values of `nil` will also be ok.
@hamiltop please feel free to re-open if this isn't along the lines of what you were after...
