### ISSUE TITLE
proposal: profiler: enable arbitrary setting of host field

### ISSUE THREAD

**Issue by rlewis-grax** [DataDog/dd-trace-go#1441]
Host is currently calculated from domain name in the profiler while many parts of the Datadog API allow arbitrary setting of the host field/tag. Adding a "WithHost" option to the profiler would enable much better flow across DD features.

**Comment by nsrip-dd** [comment]
Hello, thanks for opening this issue! I will add `WithHostname` to match the [tracer](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer#WithHostname).
