### ISSUE TITLE
goroutine leak from github.com/golang/glog.(*loggingT).flushDaemon since 1.35.0

### ISSUE THREAD

**Issue by froodian** [DataDog/dd-trace-go#1469]
I verified that this issue is not present using dd-trace-go 1.34.0. When I update my go.mod to `gopkg.in/DataDog/dd-trace-go.v1 v1.42.0` and run `go mod tidy` / `go mod download`, it adds a `github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b // indirect` reference to my require section, after which my `go.uber.org/goleak` tests start failing with

```
leaks.go:78: found unexpected goroutines:
        [Goroutine 21 in state chan receive, with github.com/golang/glog.(*loggingT).flushDaemon on top of the stack:
        goroutine 21 [chan receive]:
        github.com/golang/glog.(*loggingT).flushDaemon(0x0?)
        	/Users/ian/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
        created by github.com/golang/glog.init.0
        	/Users/ian/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x265
        ]
```

even a minimal test such as

```golang
func TestForLeaks(t *testing.T) {
  defer goleak.VerifyNone(t)
}
```

fails in this way.  I noticed a similar issue https://github.com/kubernetes/klog/issues/188 which was forked from glog.

Any thoughts on how to upgrade dd-trace-go and continue leak-testing my code?

**Comment by nsrip-dd** [comment]
Hi, this is a known issue (see https://github.com/DataDog/dd-trace-go/issues/1153). Unfortunately we get this dependency transitively through `github.com/DataDog/datadog-agent/pkg/obfuscate`, which in turn brings in `glog` through an abandoned package which is no longer receiving updates. There have been previous attempts to remove the dependency but as far as I'm aware it hasn't been removed yet.

As a workaround for the goroutine leak issue, you can tell goleak to ignore the leaked goroutine from glog like this:

```
goleak.VerifyNone(t,
    goleak.IgnoreTopFunction("github.com/golang/glog.(*loggingT).flushDaemon"),
)
```

**Comment by froodian** [comment]
Ok, thanks for the reply and workaround @nsrip-dd
