### ISSUE TITLE
[Question] How to get hold of service, env, trace id, span id from span

### ISSUE THREAD

**Issue by NicklasWallgren** [DataDog/dd-trace-go#1492]
How do one get hold of `service`, `env`, `trace id` and `span id` from the current span?

`tracer.span` implements `fmt.Formatter` which builds a string of the mentioned fields, but I need to get hold of a map, or struct containing the fields. 

The end goal is to pass the fields to our (zap or logrus) logger, i.e
```
import (
  log "github.com/Sirupsen/logrus"
)
...
`log.WithFields(log.Fields{"dd.service": "<service>", "dd.env": "<env>", "dd.trace_id": <trace id>, "dd.span_id": "<span id>"})`
```

**Comment by NicklasWallgren** [comment]
So the following should work for TraceId and SpanId. Do we need to pass `dd.env` and `dd.service` as well?

```
span, _ := tracer.SpanFromContext(c.Request.Context())
span.Context().TraceID()
span.Context().SpanID()
```

**Comment by ajgajg1134** [comment]
I see your overall intent seems to be to connect spans to logs, we do have an integration for logrus already that may simplify that case here: https://github.com/DataDog/dd-trace-go/tree/main/contrib/sirupsen/logrus (or you can look at the source code for some inspiration on how to do something similar for `zap`. (And if you do and are interested in contributing it to this repository we're open to contributions! 😄  )

As for connecting the log entry to a span you should only need the trace_id and span_id.

**Comment by NicklasWallgren** [comment]
@ajgajg1134 Thanks for the reply. 

Zap dosen't support logging contextual metadata yet https://github.com/uber-go/zap/issues/654, but I guess a can add my own implementation.
