### ISSUE TITLE
contrib/dimfeld/httptreemux/v5: Add support for dimfeld/httptreemux

### ISSUE THREAD

**Issue by devillexio** [DataDog/dd-trace-go#1520]
We use [dimfeld/httptreemux](https://github.com/dimfeld/httptreemux) as our router. Unfortunately there is no direct Datadog tracing support for `dimfeld/httptreemux`.

I would like to propose adding support for Datadog tracing to the `dimfeld/httptreemux` project. This would allow us to easily instrument our router based on `dimfeld/httptreemux`, as well as other folks that also use this router.

The process should be relatively straightforward and similar to what was done for [Julien Schmidt's httprouter](https://www.github.com/julienschmidt/httprouter) in [contrib/julienschmidt/httprouter](https://github.com/DataDog/dd-trace-go/tree/main/contrib/julienschmidt/httprouter).

The only major difference between `julienschmidt/httprouter` and `dimfeld/httptreemux` in terms of affecting Datadog tracing is the way in which they deal with URL parameters, i.e.:
- `julienschmidt/httprouter` uses a custom `[]Param` type where `Param` is a custom type with a string key value pair (see [julienschmidt/httprouter/router.go#L92](https://github.com/julienschmidt/httprouter/blob/master/router.go#L92))
- Where `dimfeld/httptreemux` uses a `map[string]string`.

~The only blocker to adding support for Datadog tracing to `dimfeld/httptreemux` is the fact that the `httptreemux.LookupResult` type contains a private `params` field that stores the path parameters. These need to be accessible in order to use the path params to build the resource name. I have created an issue (https://github.com/dimfeld/httptreemux/issues/89) and PR (https://github.com/dimfeld/httptreemux/pull/90) to make the necessary changes.~ [Resolved](https://github.com/DataDog/dd-trace-go/issues/1520#issuecomment-1380944411).

**Comment by devillexio** [comment]
The only blocker has been resolved with https://github.com/dimfeld/httptreemux/pull/90 being merged and released as [v5.5.0](https://github.com/dimfeld/httptreemux/releases/tag/v5.5.0) of `dimfeld/httptreemux`.

**Comment by laughingman-hass** [comment]
I would love to see `dimfled/httptreemux` supported here

**Comment by zball** [comment]
This would be a great addition. I would love to see support for this as well.
