### ISSUE TITLE
Why is this not "http.client.request" instead of "http.request"?

### ISSUE THREAD

**Issue by gaston-haro** [DataDog/dd-trace-go#1525]
https://github.com/DataDog/dd-trace-go/blob/24176ebb009f325d69e3d422ebbba972f06071db/contrib/net/http/roundtripper.go#L45

Is there any agreement on how to name incoming vs outgoing operations? I though it should be `http.request` for incoming requests and `http.client.request` for outgoing. Can you provide any clarification on the criteria?

Thank you

**Comment by bradley-wh-cko** [comment]
There is another issue already open about this.

https://github.com/DataDog/dd-trace-go/issues/1158

I posted a potential horibble hacky workaround which seems to work.

**Comment by gaston-haro** [comment]
Thank you @bradley-wh-cko ! I will close this then so we have a common place for discussion.

Closing as duplicate of #1158
