### ISSUE TITLE
contrib/net/http: wrap an http.Handler

### ISSUE THREAD

**Issue by pierrre** [DataDog/dd-trace-go#153]
https://github.com/DataDog/dd-trace-go/pull/115 provides new integrations for `net/http.Mux` and `gorila/mux.Router`.
However, it doesn't allow to wrap a simple `http.handler` with a tracer.

Some of my projects don't use a mux/router.
They just use a simple `http.Handler`.

It could be interesting to provide a wrapper function for this use case.

The implementation is very simple:
```go
func WrapHandler(h http.Handler, service, resource string, tr *tracer.Tracer) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		internal.Trace(h, w, req, service, resource, tr)
	})
}
```

What do you think ?

**Comment by gbbr** [comment]
This seems useful to me. I think it's a good idea and I like the simplicity of it.

**Comment by pierrre** [comment]
Will you add it to https://github.com/DataDog/dd-trace-contrib-go ?
Or should I open a PR ?
Feel free to suggest a better name for the function.

**Comment by gbbr** [comment]
Yes, add it there please. I was also thinking of a better name but nothing came to mind. Let's go with that for now.

**Comment by gbbr** [comment]
@pierrre what I meant to say is that you can feel free and open a PR in _this_ repo. We have postponed moving the integrations to a different repository due to various implications that this might have. I am happy to merge your change and am happy with the naming you've chosen too!

**Comment by dcormier** [comment]
It would be nice if a new release was cut so that `dep` would pick it up without having to add a constraint to use `master`.

**Comment by pierrre** [comment]
@dcormier you can specify a commit id with dep

**Comment by dcormier** [comment]
You can also specify a branch. But it defaults to vendoring the latest tagged release.
