### ISSUE TITLE
proposal: Support for TracingInterceptor

### ISSUE THREAD

**Issue by NicklasWallgren** [DataDog/dd-trace-go#1538]
We would like to see support for a [TraceInterceptor](https://github.com/DataDog/dd-trace-java/blob/master/dd-trace-api/src/main/java/datadog/trace/api/interceptor/TraceInterceptor.java), similar to `dd-trace-java`.

We are currently utilising TraceInterceptor to drop/filter certain spans in long-lived queue jobs.

**Comment by NicklasWallgren** [comment]
Can possibly be considered as a duplicate.

https://github.com/DataDog/dd-trace-go/pull/1381/files
https://github.com/DataDog/dd-trace-go/issues/833

**Comment by knusbaum** [comment]
Similar to #833 and #360

**Comment by knusbaum** [comment]
Closing in favor of #833 but this issue is linked.
