### ISSUE TITLE
contrib/phi: new contribution

### ISSUE THREAD

**Issue by PhilipJovanovic** [DataDog/dd-trace-go#1543]
Hey, i've made a fork of go-chi callen "phi" and i'm not able to use the contrib/go-chi middleware for tracing with the datadog profiler.

I accidentally already made a pull request with only a few files changed, since the middleware itself should be replaceable with the forked version so i just needed to rename the go-chi middleware

[Pull Request](https://github.com/DataDog/dd-trace-go/pull/1541)

**Comment by knusbaum** [comment]
Hi, @PhilipJovanovic.

Thanks for the contribution. Unfortunately, at this time the `phi` library does not appear to have enough of a user base to support the inclusion of an integration in our contrib. Maintaining integrations is engineering-intensive so we are selective about what we choose to add and maintain.

However, if the `phi` library gains popularity and there becomes a demand for an integration, we would accept an integration for it.

So you know, it's possible for you to include the integration in your own library. The contrib integrations are ones that we officially maintain and support, but the dd-trace-go library should allow you to write and publish your integration along side your library. Aside from removing a couple of `internal` references, the integration should work as-is.

If there's more we can do in the library to support external integrations or you have any other questions, please file an issue to let us know.
