### ISSUE TITLE
APM Client IP Tracing

### ISSUE THREAD

**Issue by taltcher** [DataDog/dd-trace-go#1553]
I would like to open a feature request to keep the client IP as part of the APM tracing as well and not just having it in ASM - since it still enable us to measure some trends or suspicious activity only by having this tag

**Comment by Julio-Guerra** [comment]
Hello,

Thanks for letting us know.

> enable us to measure some trends or suspicious activity only by having this tag

You should definitely try ASM for Go which would show you all the attack attempts we detect on your service.

Adding some extra context here for the @DataDog/tracing-go team:
1. dd-trace-rb and dd-trace-java already decided to keep this feature available in the tracer alone, gated behind an env var. I asked @lloeki to further specify this into the `http.client_ip` [RFC](https://datadoghq.atlassian.net/wiki/spaces/APM/pages/2357395856/Span+attributes#http.client_ip) (sorry about the private link).
2. We kept the HTTP client ip tag setter public for you to reuse it: [`httpsec.SetIPTags(span, request)` ](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1@v1.43.1/internal/appsec/dyngo/instrumentation/httpsec#SetIPTags). Feel free to refactor it if necessary.
