### ISSUE TITLE
[BUG] v1.44.0 seems to pull in a broken pkg

### ISSUE THREAD

**Issue by Tethrinaa** [DataDog/dd-trace-go#1607]
**Describe what happened:**
Using go 1.19, running go get -u upgraded our codebase from v1.43.1 => v1.44.0, this seems to have pulled in:
`go: added github.com/DataDog/datadog-agent/pkg/remoteconfig/state v0.40.1`

Which causes the following build error:

`../../go/pkg/mod/github.com/!data!dog/datadog-agent/pkg/remoteconfig/state@v0.40.1/tuf.go:34:20: rootClient.InitLocal undefined (type *client.Client has no field or method InitLocal)`

Manually reverting to v1.43.1 resolved the issue.  Some kind of linking issue with 1.44.0?

**Comment by qgxpagamentos** [comment]
we are having the same problem.

**Comment by Tethrinaa** [comment]
Yes, I manually changed the go mod line to:
gopkg.in/DataDog/dd-trace-go.v1 v1.43.1 // indirect
and then run go mod tidy

**Comment by ajgajg1134** [comment]
👋 Hello! Thanks for bringing this up. It looks like the latest version of that `remoteconfig` package isn't quite compatible with v1.44.0 of dd-trace-go. I will take a look tomorrow at resolving the `remoteconfig` package issue inside the datadog-agent (it seems like it might just need a new tag)

If you'd like to upgrade dd-trace-go now and not wait for that fix you can use `go get -u gopkg.in/DataDog/dd-trace-go.v1@v1.44.0` which will pull a working version of `remoteconfig/state` and not upgrade it to `v0.40.1`

**Comment by Julio-Guerra** [comment]
Hey everyone,
Sorry again about this issue.

dd-trace-go v1.44.1 is out and should fix your issue.
Could you please give it a try by updating dd-trace-go the way you used to (I guess either `go get -u all` or `go get -u`) and let us know?

**Comment by Julio-Guerra** [comment]
> I'm getting the same errors after automatic dependency updates.

Thanks for bringing this to our attention. Our fix got lost in a git tag that followed it :-/
We are looking into properly tagging it again. The fix will be part of the v1.45.0 release happening later this week.

**Comment by Julio-Guerra** [comment]
v1.45.0-rc.2 is out and now includes this fix. We should release it next Thursday.
