### ISSUE TITLE
contrib/aws/aws-sdk-go: Add WithErrorCheck option

### ISSUE THREAD

**Issue by soh335** [DataDog/dd-trace-go#1664]
Same feature with https://github.com/DataDog/dd-trace-go/pull/1315.
Sometime, we want to ignore known aws error.

For example, It is dynamodb case. Some data are stored in dynamodb, and it is split by time for scaling (like [this](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-time-series.html)). 
And program request data with range, and  some queries are failed with "ResourceNotFoundException", because table is not exist.
But it is expected error for program, so we think not need to mark error in datadog.

But current aws wrapper records all error, so many error is shown in datadog.
So We want to add WithErrorCheck option.

**Comment by amwill04** [comment]
Are PR accepted? For another example: checking if a file exists on S3 is polluting datadog with `NotFound` errors which as OP states is a known/wanted error.

**Comment by soh335** [comment]
I'm happy if this p-r is merged !

**Comment by ajgajg1134** [comment]
Thanks for the contribution, we'll take a look at the PR shortly

**Comment by rodrigoff** [comment]
Any news on this?

**Comment by katiehockman** [comment]
It looks like this has been completed in https://github.com/DataDog/dd-trace-go/pull/2042 and https://github.com/DataDog/dd-trace-go/pull/1682 😄 I'll go ahead and close this issue. Thanks!
