### ISSUE TITLE
[BUG] mongo-go-driver monitor inconsistent with other contribs w/r to default service name

### ISSUE THREAD

**Issue by sgtsquiggs** [DataDog/dd-trace-go#1688]
**Version of dd-trace-go**
`gopkg.in/DataDog/dd-trace-go.v1 v1.37.1`

**Describe what happened:**
Using `gopkg.in/DataDog/dd-trace-go.v1/contrib/go.mongodb.org/mongo-driver/mongo` as described in the example

No spans generated for commands to mongo

**Describe what you expected:**

Expected spans to be generated with the default configuration.

**Steps to reproduce the issue:**

```go
	opts := options.Client().ApplyURI("connection-string").SetMonitor(mongotrace.NewMonitor())
	client, err := mongo.Connect(ctx, opts)
```

use as normal

If you use `SetMonitor(mongotrace.NewMonitor(mongotrace.WithAnalytics(true)))` you will see spans.

**Additional environment details (Version of Go, Operating System, etc.):**
debian buster, go1.19.1

**Comment by sgtsquiggs** [comment]
Immediately after filing this I found my actual issue. I am configuring mongodb before I configure profiling, and that means globally my service name has not been set by the time I configure the mongodb monitor. So the spans are sent to datadog but for the wrong service.

**Comment by sgtsquiggs** [comment]
The contributed libraries are not consistently setting the ServiceName default:

mongo defaults to `mongo`:
https://github.com/DataDog/dd-trace-go/blob/main/contrib/go.mongodb.org/mongo-driver/mongo/option.go#L23
```go
func defaults(cfg *config) {
	cfg.serviceName = "mongo"
	// cfg.analyticsRate = globalconfig.AnalyticsRate()
	if internal.BoolEnv("DD_TRACE_MONGO_ANALYTICS_ENABLED", false) {
		cfg.analyticsRate = 1.0
	} else {
		cfg.analyticsRate = math.NaN()
	}
}
```

net/http defaults to `http.router` but will use a global service name if set:
https://github.com/DataDog/dd-trace-go/blob/main/contrib/net/http/option.go#L40-L43
```go
func defaults(cfg *config) {
	if internal.BoolEnv("DD_TRACE_HTTP_ANALYTICS_ENABLED", false) {
		cfg.analyticsRate = 1.0
	} else {
		cfg.analyticsRate = globalconfig.AnalyticsRate()
	}
	cfg.serviceName = "http.router"
	if svc := globalconfig.ServiceName(); svc != "" {
		cfg.serviceName = svc
	}
	cfg.spanOpts = []ddtrace.StartSpanOption{tracer.Measured()}
	if !math.IsNaN(cfg.analyticsRate) {
		cfg.spanOpts = append(cfg.spanOpts, tracer.Tag(ext.EventSampleRate, cfg.analyticsRate))
	}
	cfg.ignoreRequest = func(_ *http.Request) bool { return false }
	cfg.resourceNamer = func(_ *http.Request) string { return "" }
}
```

**Comment by zarirhamza** [comment]
This is currently the behavior for the mongo integration and a few other integrations as well. However, we do have an initiative to improve the service naming across the board for several libraries within the go tracer. This includes allowing users to set their own service name for all integrations. @rarguelloF and I will keep this thread updated as we get more information.

**Comment by zarirhamza** [comment]
Hello, we have pushed a PR that would enable consistent behavior for service naming for all contributions in Go, including mongo. The default behavior is now to use the global service name but the user can provide a custom service name for the specific mongo integration if needed by enabling some options. Please refer to the referenced PR #1908 for more information and feel free to open another issue if necessary, thank you!
