### ISSUE TITLE
contrib/go-redis: support v9

### ISSUE THREAD

**Issue by taowata** [DataDog/dd-trace-go#1710]
Hi, go-redis recently upgraded to v9.
Here are the changes: https://github.com/redis/go-redis/blob/master/CHANGELOG.md
I would be happy to add support for this new major version.

With this release, the go-redis repository has moved to the [Redis GitHub organization](https://github.com/redis), so we have to fix more than just the version number as shown below. 

```go
// old v8
import "github.com/go-redis/redis/v8"

// new v9
import "github.com/redis/go-redis/v9"
```
Will a new /contrib/redis/go-redis.v9 package be created?

**Comment by katiehockman** [comment]
Sounds good to us! If you'd like to contribute to the project by sending over a PR, that would be great 😄

**Comment by taowata** [comment]
Thanks for the response. I'd like to contribute to this project. 
I'll send over a PR as soon as I am ready 👍

**Comment by David-Wobrock** [comment]
Thanks a lot for contributing this!
Is there any release planned in the coming days/weeks to make this contrib' available? 😇
