### ISSUE TITLE
proposal: add support for Labstack Echo

### ISSUE THREAD

**Issue by rv-rsouza** [DataDog/dd-trace-go#174]
Hi!

It would be nice to have an implementation for Labstack's Echo web framework.

**Comment by gbbr** [comment]
Hi @rv-rsouza ! Would you be interested in committing to this work?

**Comment by gbbr** [comment]
Thanks for putting in the effort, as discussed in #235, I'd be very happy to work with you to get this integration into the `v1` branch.

**Comment by gbbr** [comment]
Hi @rv-rsouza - is there any interest to build this or should we close the issue?

**Comment by rv-rsouza** [comment]
Hello! Yes, there is. I couldn't find the time to do it, but it will sure help.
