### ISSUE TITLE
contrib/jmoiron/sqlx: Question about automatically connecting child spans to parent spans

### ISSUE THREAD

**Issue by joshverma** [DataDog/dd-trace-go#1767]
Hello, this is not a feature request, bug report, or security vulnerability - just a question on recommended implementation. 

When using [chi](https://github.com/go-chi/chi) and the [associated DD chitrace integration](https://github.com/DataDog/dd-trace-go/tree/main/contrib/go-chi/chi), a trace and parent span are created automatically after the net/http server accepts a request. 

I'm also using contrib/jmoiron/sqlx, and have already registered the pg driver and connected to the database using the sqlx tracer. However, the postgres spans that are created are not automatically children of the http request spans that are created for incoming requests to the server by the chitracer. To create the parent-child relationship between these spans, I have decided to pass the http request context from each request down to the functions in my service that query the database. Passing these contexts to the `SelectContext()` and similar functions successfully creates the parent-child relationship between the http request spans and the postgres spans. 

Is this the recommended approach to connect child spans to parent spans? This requires a lot of changes to existing code - changes to all function signatures to accept the request context as an argument. I was wondering if there was a better approach to linking these spans. 

Thanks in advance, and let me know if you need me to clarify anything.

**Comment by felixge** [comment]
👋 Hi. I work on the profiler, so I'll leave it to @DataDog/tracing-go to confirm. But what you're describing sounds like the correct approach. I agree that it can be cumbersome. That being said, we have some ideas for potentially automating some of this in the future.

**Comment by ajgajg1134** [comment]
Hello! Yes, this is the recommended approach. You're right that unfortunately it can be a bit cumbersome to make these changes, and as @felixge mentioned it's something that we're actively doing research on how to improve the tracing experience.

I'll add that passing around the request context does give you an additional benefit: If the client closes their connection, "cancelling" the context, you'll be able to close or "not do" the database query saving a bit of unnecessary work

**Comment by joshverma** [comment]
Awesome thank you both for confirming!
@felixge @ajgajg1134

**Comment by katiehockman** [comment]
@joshverma let us know if we should keep this open, or if we're good to close the issue at this time. Thanks!

**Comment by joshverma** [comment]
You can close it thanks.
@katiehockman

**Comment by katiehockman** [comment]
Great, thanks!
