### ISSUE TITLE
database/sql: excluding Ping from database tracing

### ISSUE THREAD

**Issue by MDrollette** [DataDog/dd-trace-go#178]
Would it be reasonable to make it configurable whether or not the [Ping()](https://github.com/DataDog/dd-trace-go/blob/master/contrib/database/sql/conn.go#L84) call is traced on the DB conn? In my case Ping() is used in a service-level health check with a high call frequency, and those traces are just noise.

**Comment by gbbr** [comment]
@MDrollette I think you should be able to ignore those traces by configuring the agent. See [here](https://github.com/DataDog/dd-agent/blob/master/datadog.conf.example#L326-L330). Please let me know if that fixes it for you.

**Comment by MDrollette** [comment]
ah, great. I didn't know that was a feature. It would still be preferable to not send them to the agent at all, since they have such high frequency, but I think that ignore list will be acceptable.

**Comment by gbbr** [comment]
Great! If that is acceptable, then please close this issue. If not, let us know and we'll try and find another way.
