### ISSUE TITLE
Info Log about Unknown VCS sent as Warning since v.1.48.0

### ISSUE THREAD

**Issue by david-alza** [DataDog/dd-trace-go#1800]
We upgraded to 1.48.0 yesterday and ever since we're seeing a lot of errors for `Datadog Tracer v1.48.0 INFO: Unknown VCS: '', skip source code metadata extracting`. There's two overall issues I can see here: 

1. I think it'd be nice to silence this if possible? Or at least have a bit more helpful of an error message pointing to possibly why Datadog can't determine the VCS. We're not using source code extraction at the moment so it's a bit confusing to get errors like this. 
2. Any ideas why these are getting emitted as Errors instead of Info in Datadog? Based on the callsite it looks like these should be logged as Info: 
https://github.com/DataDog/dd-trace-go/blob/a56634f9c2b98dbb07e3d8d5a761ee75d4bd6cb3/internal/gitmetadatabinary.go#L35

**Version of dd-trace-go**
v.1.48.0

**Describe what happened:**
Upgraded to v 1.48.0 and started seeing unresolvable errors for a product we're not using
**Describe what you expected:**
I would have expected either nothing to be logged in this case or these to be logged as Info lines. 

**Additional environment details (Version of Go, Operating System, etc.):**
Go: 1.20 
Using kubernetes via EKS
Tracer config: 
```
{
  "date": "2023-03-14T15:05:01Z",
  "os_name": "Linux (Unknown Distribution)",
  "os_version": "unknown",
  "version": "v1.48.0",
  "lang": "Go",
  "lang_version": "go1.20.2",
  "agent_error": "",
  "debug": false,
  "analytics_enabled": false,
  "sample_rate": "NaN",
  "sample_rate_limit": "disabled",
  "sampling_rules": null,
  "sampling_rules_error": "",
  "service_mappings": null,
  "runtime_metrics_enabled": false,
  "health_metrics_enabled": false,
  "profiler_code_hotspots_enabled": true,
  "profiler_endpoints_enabled": true,
  "dd_version": "17825cf6",
  "architecture": "arm64",
  "lambda_mode": "false",
  "appsec": false,
  "agent_features": { "DropP0s": true, "Stats": true, "StatsdPort": 0 }
}
```

**Comment by amwill04** [comment]
Its also rather redundant as you can get VCS info from either; environment variables, or DD_TAGS. I consciously dont embed VCS in the binary so I have deterministic builds regardless of the commit hash if no source code has changed. It would be useful if this `warning` was only logged if no VCS info could be found from any of the three available sources
