### ISSUE TITLE
trace: Span.Context() uses a basic type string as key

### ISSUE THREAD

**Issue by pierrre** [DataDog/dd-trace-go#182]
https://github.com/DataDog/dd-trace-go/blob/6ba9d7ab13ac75d2b739571566f30e4d3ebe39e9/tracer/span.go#L307

My linter reports this:
> should not use basic type string as key in context.WithValue (golint)

IIRC, the best practice is to:
- create your own context key type
- create global variable(s) for each context key

Currently, if a third party service wraps the context with the same string, it will overwrite it.
The best practice mentioned above prevents that.

**Comment by gbbr** [comment]
You are right, we need to fix this. The release candidate that we are working on no longer does this. I will leave the issue open until we merge that.

**Comment by gbbr** [comment]
This is fixed in `v1`. Closing.

**Comment by pierrre** [comment]
Thanks ! Should I use the v1 branch ? Is it stable ?

**Comment by gbbr** [comment]
It is not officially released yet, but the chances of us breaking the API are close to zero at this point as we have already started using this extensively internally and will be releasing it soon. I'd be happy for you to use it and test if you're open to it.

It is however officially still in the Release Candidate state.
