### ISSUE TITLE
[BUG] contrib/gomodule/redigo: Passed context is ignored if not given in the args

### ISSUE THREAD

**Issue by lbcjbb** [DataDog/dd-trace-go#1935]
The `redis.Conn` returned by `DialContext()` ignore the explicit context given as first argument of `DoContext()`.

**Version of dd-trace-go**

All

**Describe what happened:**

Span are correctly created but are not attached to the parent span given in the context.

**Describe what you expected:**

Created span should be attached to the parent span given in the context.

**Steps to reproduce the issue:**

```go
client, _ := redigotrace.Dial("tcp", "127.0.0.1:6379", WithServiceName("my-service"))

span, ctx := tracer.StartSpanFromContext(context.Background(), "test")
defer span.Finish()

_, _ = redis.DoContext(client, ctx, "SET", "ONE", "TWO")
```

**Comment by zarirhamza** [comment]
Closing due to PR being merged successfully, thank you for all your hard work!
