### ISSUE TITLE
trace: unbounded trace channel can cause out-of-memory crashes

### ISSUE THREAD

**Issue by kevinlebrun** [DataDog/dd-trace-go#197]
It was actually seen in production, with large traces (around 2 MiB but it is actually an issue too) and heavy load, the channel got filled until the host memory became exhausted.

The channel can take 1000 traces and force flushes when it is half-filled.

https://github.com/DataDog/dd-trace-go/blob/master/tracer/channels.go#L8

We need to ensure two properties:

 - the tracer memory usage should remain low (defining a SLA on this one would be great)
 - the flush payload should not reach 10 MiB which is the maximum input size accepted by the agent

**Comment by gbbr** [comment]
This sounds good, we need to think about a good approach to this and see if it's reasonable from a performance point of view too. This involves reflecting on the size of each trace.

**Comment by gbbr** [comment]
Resolved in #206
