### ISSUE TITLE
contrib/go-redis/redis.v8: Support redis/go-redis/v9

### ISSUE THREAD

**Issue by mash** [DataDog/dd-trace-go#2027]
github.com/go-redis/redis has been moved to github.com/redis/go-redis and have released a new major version v9.

The CHANGELOG mentions breaking changes and many new features as well.
https://github.com/redis/go-redis/blob/master/CHANGELOG.md#v9-2023-01-30

We would like to see https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/contrib/go-redis/redis.v9 !

**Comment by taowata** [comment]
Hi, @mash 
We've already updated to support the new v9 of the go-redis in the latest release, [v1.51.0](https://github.com/DataDog/dd-trace-go/releases/tag/v1.51.0). 
You can access the updated package at: https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/contrib/redis/go-redis.v9.
