### ISSUE TITLE
proposal: contrib: Add support for log/slog

### ISSUE THREAD

**Issue by wijayaerick** [DataDog/dd-trace-go#2077]
Currently https://pkg.go.dev/log/slog is in Go1.21 release candidate.
Once it's released in go1.21 people will start using it so it would be nice to have this support after it's released.

Links:
- https://pkg.go.dev/log/slog@master#Handler
- https://tip.golang.org/doc/go1.21

**Comment by sivchari** [comment]
If this proposal is accepted, many projects that rely on Go 1.20 or lower versions will crash with build errors.
What do you think ?

**Comment by knusbaum** [comment]
This work would be adding a new integration for `log/slog`. This is something we probably want, and also want to look at automatic trace context injection into structured logs.

Let's fill this proposal out with exactly what we want to do, and then it will be a likely `accept`.
@wijayaerick, please feel free to write up how you think this should work, or we'll get to it as we are able.

@sivchari regarding the build errors, we can simply circumvent this with build tags in the integration to make sure it won't be build with <go1.21.

**Comment by sivchari** [comment]
@knusbaum 
OK, build tag is useful to provide a specify feature for users, but it's same as that we provide the complex feature. So, I think we must show usage more carefully including slog in the future, if a feature need build tag.  If you need someone to help to achieve the this roadmap, I welcome to help it.

**Comment by zarirhamza** [comment]
This proposal will definitely be accepted as soon as someone can provide a clear and concise plan forward on how to implement this. For that reason, we have marked it as `help wanted` rather than `proposal/accepted`

**Comment by jordan-bonecutter** [comment]
> This proposal will definitely be accepted as soon as someone can provide a clear and concise plan forward on how to implement this. For that reason, we have marked it as `help wanted` rather than `proposal/accepted`

```go
import (
	"context"
	"log/slog"

	tracer "gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
)

func WrapHandler(in slog.Handler) slog.Handler {
  return Handler{in}
}

type Handler struct {
  slog.Handler
}

func (h Handler) Handle(ctx context.Context, rec slog.Record) error {
  span, ok := tracer.SpanFromContext(ctx)
  if ok {
    rec.Add(
      slog.Uint64("dd.trace_id", span.Context().TraceID()),
      slog.Uint64("dd.span_id", span.Context().SpanID()),
    )
  }

  return h.Handler.Handle(ctx, rec)
}
```

**Comment by darccio** [comment]
Thanks to @rarguelloF, we'll be releasing support for `log/slog` in our upcoming `v1.66.0`. It should happen in July, as scheduled by our monthly release train.
