### ISSUE TITLE
ddtrace/tracer: diagnostic and startup logs should be in JSON format.

### ISSUE THREAD

**Issue by mariel-sendblocks** [DataDog/dd-trace-go#2152]
According to the docs, the tracer diagnostic/startup logs arent printed in json format. The actual diagnostic/config are in json format, but they are printed as part of non-json log msg : 
```
2020/07/09 15:57:07 Datadog Tracer v1.26.0 INFO: DATADOG TRACER CONFIGURATION {"date":"2020-07-09T15:57:07-05:00","os_name":"darwin","os_version":"10.15.4","version":"v1.26.0","lang":"Go","lang_version":"go1.14.2","env":"","service":"splittest2","agent_url":"http://127.0.0.1:8126/v0.4/traces","agent_error":"","debug":true,"analytics_enabled":false,"sample_rate":"NaN","sampling_rules":null,"sampling_rules_error":"","tags":{"runtime-id":"d269781c-b1bf-4d7b-9a55-a8174930554f"},"runtime_metrics_enabled":false,"health_metrics_enabled":false,"dd_version":"","architecture":"amd64","global_service":""}
```

**Version of dd-trace-go**
 latest

**Describe what happened:**
 general issue

**Describe what you expected:** The whole log should be printed in json format

**Steps to reproduce the issue:**

**Additional environment details (Version of Go, Operating System, etc.):**

**Comment by mariel-sendblocks** [comment]
Hey @knusbaum ,
Since the datadog collects all the content of the logs, those logs arrive the datadog ui as ERRORS. The tracer configuration indeed printed as a json, but its part of a log message that itself isnt json-formatted.
I would expect to have the ability to configure the tracer's log message format.

**Comment by nsrip-dd** [comment]
See also #2077. If we support `slog`, then the user can supply a JSON handler and we can provide the startup info to a `slog.Logger` so that it gets structured as a proper JSON record (without the leading timestamp)

**Comment by ahmed-mez** [comment]
Hey @mariel-sendblocks 

As mentioned in [the docs](https://docs.datadoghq.com/tracing/troubleshooting/tracer_startup_logs/), these prefixes are meant to simplify the search within your logs. They are also unified across the different Datadog tracers.

> Tracer startup logs capture all obtainable information at startup and log it as DATADOG TRACER CONFIGURATION, DATADOG TRACER DIAGNOSTICS, DATADOG ERROR, or DATADOG CONFIGURATION to simplify searching within your logs.

While we don't expect to change the current default format of these logs in dd-trace-go, we're not against giving users the ability to reformat the logs and use any other formats they want (including JSON). We're happy to review and guide any contributions to allow doing this.

For better tracking and prioritization, you can also reach out to the [support team](https://www.datadoghq.com/support/) and submit a feature request. Thanks.

**Comment by tspearconquest** [comment]
Hello, I'm interested in this and have opened a support case. We're facing the issue that Traefik Ingress Controller uses this library and while we have Traefik configured for JSON logging, this library is still logging to plaintext, which is breaking log parsing by Fluentd for our Traefik logs.

**Comment by rarguelloF** [comment]
👋  @tspearconquest 

As a workaround for this issue, you can use the `tracer.WithLogger` option (from `gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer`) to provide your existing JSON logger to the tracer:

```go
package main

import (
	"go.uber.org/zap"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
)

type ddLogger struct {
	logger *zap.Logger
}

func (d *ddLogger) Log(msg string) {
	d.logger.Info(msg)
}

func main() {
	// initialize your JSON logger - in this example I'm using go.uber.org/zap
	logger, err := zap.NewProduction()
	if err != nil {
		panic(err)
	}
	defer logger.Sync()

	tracer.Start(tracer.WithLogger(&ddLogger{logger: logger}))
	defer tracer.Stop()

	// ...
}
```

We are aware the existing `ddtrace.Logger` interface is limited as it doesn't expose some information like the log level or the key/value fields, but it should be enough to fix your existing issue.
