### ISSUE TITLE
[BUG] contrib/database/sql: Context passed to PrepareContext is used in later queries

### ISSUE THREAD

**Issue by WKBae** [DataDog/dd-trace-go#2172]
**Version of dd-trace-go**

v1.54.0

**Describe what happened:**

Context passed to `db.PrepareContext()` is kept throughout the lifespan of stmt, yielding "context canceled" error when using the stmt after the context is canceled.

The following code shadows `ctx` with a context derived from `s.ctx`, which is already canceled.
https://github.com/DataDog/dd-trace-go/blob/30bfd5205d6af7bc8928b90e92310ae35879726b/contrib/database/sql/stmt.go#L62-L65

[Go documentation](https://pkg.go.dev/database/sql#DB.PrepareContext) states that `The provided context is used for the preparation of the statement, not for the execution of the statement.`

**Describe what you expected:**
Context used in `PrepareContext` is not preserved; returned Stmt should be usable even after the prepare context has been expired.

**Steps to reproduce the issue:**

Code to reproduce: (actual driver implementation does not matter, tested MySQL and SQLite)
```go
package main

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/mattn/go-sqlite3"
	sqltrace "gopkg.in/DataDog/dd-trace-go.v1/contrib/database/sql"
)

func connectSQLite() *sql.DB {
	sqltrace.Register("sqlite3", &sqlite3.SQLiteDriver{})
	db, err := sqltrace.Open("sqlite3", "file::memory:?cache=shared")
	if err != nil {
		panic(err)
	}
	return db
}

func connectSQLiteNoTrace() *sql.DB {
	db, err := sql.Open("sqlite3", "file::memory:?cache=shared")
	if err != nil {
		panic(err)
	}
	return db
}

func main() {
	db := connectSQLite()
	defer db.Close()

	// Prepare using ctx1
	ctx1, cancel := context.WithCancel(context.Background())
	stmt, err := db.PrepareContext(ctx1, "SELECT 1")
	if err != nil {
		panic(err)
	}
	defer stmt.Close()
	cancel()

	// Query stmt using ctx2
	ctx2 := context.Background()
	var result int
	err = stmt.QueryRowContext(ctx2).Scan(&result)
	if err != nil {
		panic(err) // panics with "context canceled"
	}

	fmt.Println("result:", result)
}
```
When using `connectSQLiteNoTrace()`, the result prints out correctly. However, when using `connectSQLite()`, it returns "context canceled" error on `QueryRowContext`.

**Additional environment details (Version of Go, Operating System, etc.):**
Tested on go1.20.5 darwin/arm64, but OS shouldn't matter.

**Comment by nsrip-dd** [comment]
Thank you for the report, and for the reproducer! I've sent #2173 to address this.
