### ISSUE TITLE
contrib/internal/httptrace: optionally omit http.url tag

### ISSUE THREAD

**Issue by devillecodes** [DataDog/dd-trace-go#2178]
I would like to request the option to omit the `http.url` tag in list of tags captured in the trace span information.

We already have an option to remove the query string information from trace span tags by setting the environment variable: `DD_TRACE_HTTP_URL_QUERY_STRING_DISABLED`.

In addition to query parameters the HTTP request URL may also contain other information that we may choose to rather omit from the traces in APM.

Note that, at least from my testing, omitting the `http.url` does not interfere with the rest of APM's functionality. The one side-effect worth mentioning is that removing the `http.url` tag also means that the URL parser will not be able to populate the `http.url_details` tag on the Datadog backend as part of the ingestion pipeline.

To achieve this I propose we introduce another configuration parameter called `DD_TRACE_HTTP_URL_DISABLED`. When set to `"true"`, the `http.url` tag will be omitted from the traces sent to Datadog. This is an optional boolean variable that defaults to `"false"` and does not change the current behaviour of including the `http.url` tag unless it is explicitly set to `"true"`.

Note that this feature request is similar to https://github.com/DataDog/dd-trace-go/issues/2179, just for a different tag. It may be easier to review these together.

**Comment by devillecodes** [comment]
I apologize for the Unverified/Verified commit update spam. I found out (the hard way) that updating the branch via the GitHub UI using a rebase does not sign the commits. 😞 I had to locally update the commits to sign them and push up the changes.

**Comment by devillecodes** [comment]
Hi folks! :wave: Happy Monday! :tada: Just checking in if there's anything required on this issue at this stage.

**Comment by zarirhamza** [comment]
Hey @devillecodes!

After looking into it, we decided that creating an environment variable for every possible tag that users would want to filter would set a precedent that could quickly spiral out of control. Instead, we'd like to propose 2 possible options. If none of these work, feel free to let us know and we can work from there:

1. **Utilizing Agent Configurations** - We currently provide several options for customers to filter out tags that they do not want to send to the backend as part of trace collection. Looking at this [link](https://docs.datadoghq.com/tracing/configure_data_security/?tab=net#replace-tags), you can look at potential options to use the `replace_tags` setting to ignore any tags like `http.url` or `http.host`

2. **Using The `WithAfter` Option In The Tracer** - Specifically for the http libraries, we have the `WithAfter` option which allows users to configure values - including setting span tags - after all the processing is done by the tracer. You could potentially rewrite/delete `http.url` or `http.host` tags from the span similar to the example [here](https://github.com/DataDog/dd-trace-go/blob/992bbaf1af32094a1e7576398507e8f84ef66cae/contrib/net/http/roundtripper_test.go#L62).

If this works, we can close issue #2179 and PR #2181

**Comment by devillecodes** [comment]
Hi @zarirhamza! Thanks for taking a look and thoughtful suggestions. 🙏 

I think both of these are great options. Thanks for pointing them out!

I'll take this to my team and we can decide on the best way forward.

You may close the related PR and issue.

**Comment by zarirhamza** [comment]
Closed with above resolution
