### ISSUE TITLE
contrib/internal/httptrace: optionally omit http.host tag

### ISSUE THREAD

**Issue by devillecodes** [DataDog/dd-trace-go#2179]
I would like to request the option to omit the `http.host` tag in list of tags captured in the trace span information.

We already have an option to remove the query string information from trace span tags by setting the environment variable: `DD_TRACE_HTTP_URL_QUERY_STRING_DISABLED`.

In addition to query parameters the HTTP host may also contain information (such as a subdomain) that we may choose to rather omit from the traces in APM.

Note that, at least from my testing, omitting the `http.host` does not interfere with the rest of APM's functionality.

To achieve this I propose we introduce another configuration parameter called `DD_TRACE_HTTP_HOST_DISABLED`. When set to `"true"`, the `http.host` tag will be omitted from the traces sent to Datadog. This is an optional boolean variable that defaults to `"false"` and does not change the current behaviour of including the `http.host` tag unless it is explicitly set to `"true"`.

Note that this feature request is similar to #2178, just for a different tag. It may be easier to review these together.

**Comment by zarirhamza** [comment]
Closed with resolution in #2178
