### ISSUE TITLE
contrib/go-redis/redis.v9: Add Tag option like tracer.Tag from dd-tracer-go

### ISSUE THREAD

**Issue by koheiyamayama** [DataDog/dd-trace-go#2184]
Wouldn't it be beneficial for us to configure tags for spans by writing the following code?

```go
client := redis.NewClient(redisOpt, redis.WithTag("key", "value"))
// When this client executes commands such as GET, SET, and others, tags are applied to all associated spans.
```

Please react to this post if you feel the same way as I do.

**Comment by ajgajg1134** [comment]
👋 hello! Thanks for opening an issue here, is the desire that this tag becomes globally configured for that redis client such that all spans created will receive that tag? And can you explain a bit more your use case? Is there a specific tag missing from this integration that would be useful to add for everyone? Or is it something custom to your needs?

**Comment by ajgajg1134** [comment]
This looks good. We support this in a number of other contribs it looks like so let's make sure we use the same name `WithCustomTag` for consistency. Also let's follow the pattern similar to the `gorm` integration where the WithCustomTag accepts a function on `redis.Cmder` so we can support dynamic tags.

**Comment by koheiyamayama** [comment]
@ajgajg1134 

Thank you!

By the way, can I contribute to this issue if it hasn't been assigned to anyone?
