### ISSUE TITLE
[BUG] regression introduced in 1.53.0 causes context caching/cancellation

### ISSUE THREAD

**Issue by bertold** [DataDog/dd-trace-go#2191]
**Version of dd-trace-go**
The problem was introduced in 1.53.0. The library works fine in 1.52.0
1.54.0 is also affected.

**Describe what happened:**
We noticed that on a 2nd call to a REST API, the database call starts to fail as the context was already canceled.

We use chi as the HTTP router and gorm to access a Postgres database.

We use the `gopkg.in/DataDog/dd-trace-go.v1/contrib/database/sql` and `gopkg.in/DataDog/dd-trace-go.v1/contrib/gorm.io/gorm.v1` packages for database tracing.

**Describe what you expected:**

A canceled context should not be cached in the database tracing library.

**Steps to reproduce the issue:**

See [sample code](https://gitlab.com/verosint/public/tracerbug) to reproduce the issue.
Both success and failure scenarios are demonstrated. The successful scenario does *not* use the dd-tracer-go library.

**Additional environment details (Version of Go, Operating System, etc.):**

Go 1.21
macOS Ventura 13.5.1

**Comment by bertold** [comment]
I managed to isolate the [commit](https://github.com/DataDog/dd-trace-go/commit/ea87357117658166b639b81d49536ae805a5e43d0) that introduced this regression.

**Comment by ajgajg1134** [comment]
The fix is available now via 1.54.1!

**Comment by bertold** [comment]
@ajgajg1134 - much appreciated 🙇 I can confirm that our problems are gone. Thanks again.
