### ISSUE TITLE
profiler: support profile download API for PGO

### ISSUE THREAD

**Issue by aexvir** [DataDog/dd-trace-go#2230]
since now go has [profile guided optimization](https://go.dev/doc/pgo), we'd like to take advantage of it, but we can't use both the datadog profiler and the built in pprof to obtain the profiles that we'd have to supply to the compiler as part of the build step

it would be nice if the datadog profiler could provide similar handlers like the pprof ones so we could add them on specific routes and being able to obtain pprof formatted files from a running go service as part of our ci/cd

**Comment by nsrip-dd** [comment]
Thanks for reaching out! Today, you can download individual profiles from the app like this:

1) Select an individual profile:

<img width="855" alt="Screenshot 2023-09-25 at 7 53 32 AM" src="https://github.com/DataDog/dd-trace-go/assets/97066770/44cea6ca-8a50-4690-b31f-4f8b7e60f2d2">

2) Click the download button in the top right:

<img width="337" alt="Screenshot 2023-09-25 at 7 53 43 AM" src="https://github.com/DataDog/dd-trace-go/assets/97066770/e3f21910-03c7-4083-8171-6a763e616aec">

3) The `cpu.pprof` file is a CPU profile which can be used for PGO:

<img width="298" alt="Screenshot 2023-09-25 at 7 53 54 AM" src="https://github.com/DataDog/dd-trace-go/assets/97066770/d1a1bfea-154d-4718-9028-8bcfbd4878d7">


You can combine multiple such `cpu.pprof` files on the command line, like suggested in the [PGO guide](https://go.dev/doc/pgo#notes). You might pick several representative profiles from prod, combine them, call that file `default.pgo`, and commit that file.

We're actively looking into making this easier to integrate into CI/CD pipelines. What would be useful for you? An API to fetch an aggregation of recent CPU profiles for a service, for example?

cc @felixge

**Comment by aexvir** [comment]
aha! I wasn't aware of this feature, nice 🙂 
> What would be useful for you? An API to fetch an aggregation of recent CPU profiles for a service, for example?
correct, that would be ideal

**Comment by kellen-miller** [comment]
This would be helpful in implementing Continuous PGO based on production usage. Something similar is being proposed within Pyroscope: https://github.com/grafana/pyroscope/discussions/2783

**Comment by felixge** [comment]
@kellen-miller we're currently working on this. I hope to share an update here very soon!

**Comment by gturbat** [comment]
I'm pleased to announce we are now in public beta for PGO. 😃  

Simply follow the instructions on https://github.com/DataDog/datadog-pgo, and let us know if you have any questions or feedback on it!

Also, if you can measure a positive impact on performance, we'd love to learn more about it.

**Comment by felixge** [comment]
PGO is now GA, so I'm closing this issue. But feel free to continue post feedback or questions here.

https://www.datadoghq.com/blog/datadog-pgo-go/
