### ISSUE TITLE
[BUG] not connect using dd-trace-go and datadog-agent

### ISSUE THREAD

**Issue by julianojj** [DataDog/dd-trace-go#2249]
**Version of dd-trace-go**

v1.55.0

**Describe what happened:**

Throw error when try connect to datadog-agent. The config is based on: https://github.com/DataDog/apm-tutorial-golang/blob/main/docker/all-docker-compose.yaml

Error: Datadog Tracer v1.55.0 WARN: DIAGNOSTICS Unable to reach agent intake: Post "http://datadog-agent:8126/v0.4/traces": dial tcp 172.24.0.3:8126: connect: connection refused

**Describe what you expected:**
Success connect between tracer and application

**Steps to reproduce the issue:**

From what I saw, the datadog agent is not started before the application, this causes the error, I have to restart the application manually and then the error disappears

**Additional environment details (Version of Go, Operating System, etc.):**

Go version: 1.20.8

Docker: 24.0.6

Docker Compose: 2.21.0

**Comment by ajgajg1134** [comment]
👋 hello! Thanks for opening an issue, this seems like it may not be an issue in the tracer and perhaps can be resolved using a different configuration setup? For better assistance with your specific configuration I recommend opening a ticket with [Datadog Support](https://www.datadoghq.com/support/)
