### ISSUE TITLE
contrib/julienschmidt/httprouter and DD_* environment variables

### ISSUE THREAD

**Issue by mowshon** [DataDog/dd-trace-go#2251]
Versions:

```bash
gopkg.in/DataDog/dd-trace-go.v1       v1.55.0
github.com/DataDog/datadog-go/v5      v5.3.0
```

I'm using a package:

```
gopkg.in/DataDog/dd-trace-go.v1/contrib/julienschmidt/httprouter
```

Set the environment variable `DD_TRACE_HEADER_TAGS`:

```
export DD_TRACE_HEADER_TAGS=User-Agent:new.useragent3,Content-Type:new.content_type2,Some-Header:new.some
```

I'm running a simple code:

```golang
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/julienschmidt/httprouter"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"

	httptrace "gopkg.in/DataDog/dd-trace-go.v1/contrib/julienschmidt/httprouter"
)

func main() {
	// Start the tracer
	tracer.Start(
		tracer.WithService("julienschmidt"),
		tracer.WithEnv("dev"),
		tracer.WithAgentAddr("127.0.0.1:8126"),
		tracer.WithServiceVersion("v0.0.1"),
		tracer.WithDebugMode(false),
		tracer.WithHeaderTags([]string{"Some-Header:new.some", "User-Agent:new.useragent3"}),
	)

	defer tracer.Stop()

	router := httptrace.New(
		httptrace.WithServiceName("julienschmidt"),
	)

	router.GET("/", Index)

	log.Fatal(http.ListenAndServe(":8080", router))
}

func Index(w http.ResponseWriter, _ *http.Request, _ httprouter.Params) {
	fmt.Fprint(w, "Welcome!\n")
}
```

The query appears in Datadog, but no additional data is detected. 

I tried the exact same code, but using the `chi` framework and the data I needed appeared in Datadog.

```json
"new": {
    "content_type2": "text/plain",
    "some": "okokok1",
    "useragent2": "PostmanRuntime/7.32.3"
}
```

Maybe I need to specify some other settings for `julienschmidt/httprouter` ? 

In `tracer.WithHeaderTags` I specified explicitly the list of headers I need, but `julienschmidt/httprouter` ignores them.

The problem is not only with `DD_TRACE_HEADER_TAGS`, it turns out that `julienschmidt/httprouter` does not see any settings that I pass to tracer ?

**Comment by ajgajg1134** [comment]
👋 Thanks for opening this issue! I took a quick peek at the code and it appears `julienschmidt/httprouter` may have been missed when we implemented DD_TRACE_HEADER_TAGS originally. I'll talk to the team internally and see about getting this fixed as I don't believe it was intentional.

**Comment by bendiknesbo** [comment]
This appears to also be true for `contrib/google.golang.org/grpc`. I created a separate issue here: #2298
