### ISSUE TITLE
[BUG] gofiber/fiber v2.50.0 breaking changes

### ISSUE THREAD

**Issue by fahminlb33** [DataDog/dd-trace-go#2275]
**Version of dd-trace-go**

v1.55.0

**Describe what happened:**

Cannot build a Go project using fiber v2.50.0. This problem arises from the breaking changes in fiber [v2.50.0](https://github.com/gofiber/fiber/releases/tag/v2.50.0). 

```go
- func (c *Ctx) GetReqHeaders() map[string]string
+ func (c *Ctx) GetReqHeaders() map[string][]string
```

**Describe what you expected:**

Project should build without problems.

**Steps to reproduce the issue:**

Install the latest gofiber/fiber and dd-trace-go and setup the middleware like in the example.

```go
// Start the tracer
tracer.Start()
defer tracer.Stop()

// Create a fiber v2 Router
router := fiber.New()

// Use the tracer middleware with the default service name "fiber".
router.Use(fibertrace.Middleware())

// Set up some endpoints.
router.Get("/", func(c *fiber.Ctx) error {
	return c.SendString("test")
})

// And start gathering request traces
router.Listen(":8080")
```

**Additional environment details (Version of Go, Operating System, etc.):**

Build log

```
go build -o ./app ./cmd/server
# gopkg.in/DataDog/dd-trace-go.v1/contrib/gofiber/fiber.v2
../../../go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.55.0/contrib/gofiber/fiber.v2/fiber.go:53:13: cannot use v (variable of type []string) as string value in argument to h.Add
make: *** [Makefile:10: build] Error 1
```

**Comment by katiehockman** [comment]
> This problem arises from the breaking changes in fiber [v2.50.0](https://github.com/gofiber/fiber/releases/tag/v2.50.0).

That's unfortunate that they made a breaking change. We're looking into the fix.
Thanks for raising the issue @fahminlb33

**Comment by katiehockman** [comment]
@fahminlb33 the change has been merged, and we'll plan a patch release with this change soon. Thanks again for reporting this.

**Comment by fahminlb33** [comment]
Thank you so much @katiehockman for your quick response! Really appreciated it.

**Comment by katiehockman** [comment]
@fahminlb33 [dd-trace-go v1.56.1](https://github.com/DataDog/dd-trace-go/releases/tag/v1.56.1) has been released, which includes this fix 🚀
