### ISSUE TITLE
[BUG] contrib/dimfeld/httptreemux.v5: trailing slash requests are redirected with raw URL being tracked

### ISSUE THREAD

**Issue by laughingman-hass** [DataDog/dd-trace-go#2293]
**Version of dd-trace-go**
v1.56.1

**Describe what happened:**

The dimfeld/httptreemux router has logic to handle trailing slashes which redirects to the URL without the trailing slash. This happens without the URL parameterized and sanitized of any sensitive information. This results in a second request being done, which is parameterized, but more importantly, it means that the first request is traced with its raw URL rather than the parametrized one. This happens because while looking up the resource with a trailing slash, the parameters are not detected.

Screenshot demonstrating this issue

![Screenshot 2023-10-25 at 22 17 50](https://github.com/DataDog/dd-trace-go/assets/9951907/d652d17a-3e5c-4b29-b9b3-eaf18771e217)

**Describe what you expected:**
Both requests should be parametrized as shown in the screenshot below

![Screenshot 2023-10-25 at 22 18 38](https://github.com/DataDog/dd-trace-go/assets/9951907/c76f1580-4154-4b01-8b87-42520459ed3e)

**Steps to reproduce the issue:**

Call an endpoint with a trailing slash, while using the dimfeld/httptreemux.v5 router

**Additional environment details (Version of Go, Operating System, etc.):**
this issue is not related to an environment.

**Comment by katiehockman** [comment]
Fixed in https://github.com/DataDog/dd-trace-go/pull/2332

**Comment by katiehockman** [comment]
Thank you for your patience with the release of this fix. v1.59.0 is now released, which includes this fix.
