### ISSUE TITLE
contrib/google.golang.org/grpc: WithUntracedMethods

### ISSUE THREAD

**Issue by rafaeljusto** [DataDog/dd-trace-go#2371]
**Version of dd-trace-go**
`v1.58.0-rc.1`

**Describe what happened:**

Not sure this should be considered a bug, but as Github's discussion section is disabled I couldn't find other official places to ask this question. Please let me know if there's a better channel so I can close this one.

I'm currently trying to exclude client gRPC spans that are related to health check calls:
<img width="875" alt="image" src="https://github.com/DataDog/dd-trace-go/assets/611469/76060080-38a9-484e-baeb-9f03d994bb49">

As you can see in the image below, the `full_method` is `/grpc.health.v1.Health/Check`.

<img width="396" alt="image" src="https://github.com/DataDog/dd-trace-go/assets/611469/1f43117c-e744-442d-b100-9fa506d67c8a">

But when adding the `WithUntracedMethods` option to the code nothing happens.
```go
import (
  "google.golang.org/grpc"
  grpcddtrace "gopkg.in/DataDog/dd-trace-go.v1/contrib/google.golang.org/grpc"
)

// ...

opts := []grpc.DialOption{
  grpc.WithStreamInterceptor(grpcddtrace.StreamClientInterceptor(
    grpcddtrace.WithServiceName("grpc-hub"),
    grpcddtrace.WithUntracedMethods("/grpc.health.v1.Health/Check"),
  )),
}
```

From what I can see checking the source code, the `rpc.grpc.full_method` should match what I need to provide as an argument for `WithUntracedMethods`.

https://github.com/DataDog/dd-trace-go/blob/9cf50b36cb4c94eee30184e161cdeb3e3738387f/contrib/google.golang.org/grpc/grpc.go#L66

So it's unclear why the spans are not being dropped. Big chance I'm doing something wrong. 😄 Would you have an idea what it could be?

**Describe what you expected:**
gRPC spans with `rpc.grpc.full_method` matching the attribute from `WithUntracedMethods` to be dropped from the trace.

**Steps to reproduce the issue:**
Use the `WithUntracedMethods` in the gRPC client.

**Additional environment details (Version of Go, Operating System, etc.):**
Go version: 1.21
OS: Linux

**Comment by eyasy1217** [comment]
Hi
Because it is not set to grpc.WithUnaryInterceptor?
You can also use Health_Check_FullMethodName in package grpc_health_v1 instead of "/grpc.health.v1.Health/Check".

**Comment by rafaeljusto** [comment]
> Because it is not set to grpc.WithUnaryInterceptor?

🤦  Sorry, I will add it to the `grpc.WithUnaryInterceptor` section and check this again. I'm on holiday, so will be able to check only in January.

```go
opts := []grpc.DialOption{
  grpc.WithStreamInterceptor(grpcddtrace.StreamClientInterceptor(
    grpcddtrace.WithServiceName("grpc-hub"),
    grpcddtrace.WithUntracedMethods("/grpc.health.v1.Health/Check"),
  )),
  grpc.WithUnaryInterceptor(grpcmiddleware.ChainUnaryClient(
    grpcddtrace.UnaryClientInterceptor(
      grpcddtrace.WithServiceName("grpc-hub"),
      grpcddtrace.WithUntracedMethods("/grpc.health.v1.Health/Check"),
    ),
  )),
}
```

**Comment by rafaeljusto** [comment]
Looks like it worked, thank you! Closing this one.

**Comment by identifysun** [comment]
@rafaeljusto 

I don't think you should set the healthcheck interceptor for the client, because healthcheck is an interface that needs to be set in the server-side interceptor

**Comment by rafaeljusto** [comment]
> I don't think you should set the healthcheck interceptor for the client, because healthcheck is an interface that needs to be set in the server-side interceptor

Hey @identifysun, this health check, which identifies critical paths, is part of many other health checks on the client side. We do need them for alerts and monitoring of the chain of service dependencies.
