### ISSUE TITLE
opentracing: baggage propagation from another process

### ISSUE THREAD

**Issue by dlsteuer** [DataDog/dd-trace-go#243]
If an upstream process is trying to pass data along via baggage, like say a request id, this data is not copied into the initial span, if you using the opentracing implementation. Baggage information is only propagated when there parent struct is not nil. This can be followed through here https://github.com/DataDog/dd-trace-go/blob/master/opentracing/tracer.go#L60. I've looked through the code, and

**Comment by gbbr** [comment]
Hey! Thanks for reporting this. We have stopped maintaining the `master` branch in favour of the latest stable release which should be officially announced within the following 1-2 weeks. Would you care to try that one out? It's on [branch `v1`](https://github.com/DataDog/dd-trace-go/tree/v1).

**Comment by dlsteuer** [comment]
Thanks for the info, I'll check out the v1 branch
