### ISSUE TITLE
Add datastreams support for contrib/IBM/sarama.v1 

### ISSUE THREAD

**Issue by jieya907** [DataDog/dd-trace-go#2481]
Sarama used to be owned by Shopify but recently it [transitioned](https://github.com/IBM/sarama/issues/2461) to IBM. 

There is already an [IBM/sarama module](https://github.com/DataDog/dd-trace-go/tree/main/contrib/IBM/sarama.v1). However, it lacks feature parity with the [Shopify](https://github.com/DataDog/dd-trace-go/tree/main/contrib/Shopify/sarama) version. Specifically, it's missing support for the datastream feature. 
 
It would be nice to have the `ddsarama.WithDataStreams()` option available for IBM/sarama.

Thanks!

**Comment by felixge** [comment]
Thanks for requesting this. Assigning to @DataDog/apm-ecosystems.

**Comment by zarirhamza** [comment]
I think @piochelepiotr implemented this for Shopify/sarama not too long ago. Maybe he can take a look at it again?
