### ISSUE TITLE
Latest version of `github.com/google/pprof` breaks dd-trace-go

### ISSUE THREAD

**Issue by Ztkent** [DataDog/dd-trace-go#2519]
Upgrading from `github.com/google/pprof v0.0.0-20231229205709-960ae82b1e42` to `github.com/google/pprof v0.0.0-20240117000934-35fc243c5815` causes a build error in dd-trace-go.v1.

**Version of dd-trace-go**
gopkg.in/DataDog/dd-trace-go.v1 v1.59.0

**Describe what happened:**
After upgrading, simply running `go test` results in this error output:
# gopkg.in/DataDog/dd-trace-go.v1/profiler/internal/pprofutils
../../../go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.59.0/profiler/internal/pprofutils/protobuf.go:36:57: not enough arguments in call to protobuf.Aggregate
        have (bool, bool, bool, bool, bool)
        want (bool, bool, bool, bool, bool, bool)

Google updated pprof today, and released a breaking change to an exported function:
https://github.com/google/pprof/pull/818/files#diff-213323d4ae136c7b733df56c9658661e0b6b6aa64f60adc7ca95b9e3a04ec367R440

**Describe what you expected:**
The package to continue working as normal.

**Steps to reproduce the issue:**
Reference the latest version of `github.com/google/pprof` and `gopkg.in/DataDog/dd-trace-go.v1`

**Additional environment details (Version of Go, Operating System, etc.):**
Mac, Go 1.21.5

**Comment by nsrip-dd** [comment]
Thanks! https://github.com/DataDog/dd-trace-go/pull/2515 will fix this

**Comment by fabiomargarido** [comment]
Hey there, I still get this error on dd-trace-go 1.59.1 released yesterday.
