### ISSUE TITLE
[BUG] - Unable to import tracer package

### ISSUE THREAD

**Issue by koushik963** [DataDog/dd-trace-go#2552]
I'm trying to import the package into my project - `go get gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer` but I get the error below
`inet.af/netaddr@v0.0.0-20230525184311-b8eac61e914a: verifying module: inet.af/netaddr@v0.0.0-20230525184311-b8eac61e914a: cannot authenticate record data in server response`

**Version of dd-trace-go**

**Describe what happened:**
`inet.af/netaddr@v0.0.0-20230525184311-b8eac61e914a: verifying module: inet.af/netaddr@v0.0.0-20230525184311-b8eac61e914a: cannot authenticate record data in server response` 

**Describe what you expected:**
Should be able to import succesfully

**Steps to reproduce the issue:**
`go get gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer`

**Additional environment details (Version of Go, Operating System, etc.):**
Go - 1.21, MacOS

**Comment by felixge** [comment]
Thanks for reporting this. We suspect it's a problem with the `.af` domain, see [recent news](https://www.theverge.com/2024/2/12/24071036/queer-af-mastodon-taliban-shut-down-afghanistan).

Our plan is to provide instructions for a workaround and to fix the problem with a patch release ASAP.

**Comment by darccio** [comment]
@koushik963 We are still validating a workaround. In the meantime, make sure your `GOPROXY` environment variable is pointing to `proxy.golang.org`. It's still cached there.

**Comment by koushik963** [comment]
there was one more library causing the same error. I had to add `replace go4.org/intern => github.com/go4org/intern v0.0.0-20230525184215-6c62f75575cb` to get rid of it.

**Comment by darccio** [comment]
Released as [v1.60.3](https://github.com/DataDog/dd-trace-go/releases/tag/v1.60.3).
