### ISSUE TITLE
[BUG] Panic in contrib/gorm.io/gorm.v1

### ISSUE THREAD

**Issue by bendiknesbo** [DataDog/dd-trace-go#2559]
**Version of dd-trace-go**
v1.60.3 (latest)

**Describe what happened:**
Calling `Open` from `contrib/gorm.io/gorm.v1` with a `nil` config panics. This is due to passing a **non-nil** interface holding a  **nil** value.

**Describe what you expected:**
I expected `ddgorm.Open(dialector, nil)` to behave similar to `gorm.Open(dialector, nil)`.

**Steps to reproduce the issue:**
Call `ddgorm.Open(nil, nil)`, and see the panic.

**Additional environment details (Version of Go, Operating System, etc.):**
Go 1.22

**Comment by bendiknesbo** [comment]
I created a trivial PR to solve this panic:
https://github.com/DataDog/dd-trace-go/pull/2560

**Comment by darccio** [comment]
@bendiknesbo Hi! Thanks for reporting this issue. Just a note, we are not passing a non-nil interface holding a nil. What happens is that in `gorm.Open` the nil is untyped, while the nil passed from `ddgorm.Open` becames a typed nil.

Anyhow, we'll review your PR and verify if it's the most sensible approach. Thanks again for dedicating time in improving our tracer!
