### ISSUE TITLE
contrib/internal/httputil: do not replace http.ResponseWriter

### ISSUE THREAD

**Issue by gbbr** [DataDog/dd-trace-go#256]
The current implementation replaces the `http.ResponseWriter` with another one to track the HTTP status code. This is a problem because the `http.ResponseWriter` may implement additional interfaces based on the protocol (HTTP/{1,2}, WebSockets, etc) which we don't cover for, such as:
* CloseNotifier
* Flusher
* Pusher
* Hijacker

It may end up too tedious to continue covering for all these cases. We should investigate alternatives to extracting the HTTP status code without overwriting the `http.ResponseWriter`.

**Comment by pierrre** [comment]
I think `CloseNotifier` and `Flusher` are supported by all `ResponseWriter` from the Go stdlib.
`Pusher` is only supported for HTTP/2.
`Hijacker` is only supported by HTTP/1.

So it seems there are 2 implementations in the Go stdlib:
- `CloseNotifier` + `Flusher` + `Pusher` for HTTP/2 https://github.com/golang/go/blob/29e5a81e28c633aa8d1062ce9f3749e9a8f040da/src/net/http/h2_bundle.go#L5933
- `CloseNotifier` + `Flusher` + `Hijacker` for HTTP/1 https://github.com/golang/go/blob/29e5a81e28c633aa8d1062ce9f3749e9a8f040da/src/net/http/server.go#L409

So, the `dd-trace-go` could implement custom `ResponseWriter` for both cases
