### ISSUE TITLE
v2/contrib: Add datastreams support for contrib/IBM/sarama

### ISSUE THREAD

**Issue by KyleWiering** [DataDog/dd-trace-go#2573]
Referencing #2481 

Request Pulling the changes from #2006 into the IBM/sarama module as Shopify no longer supports sarama and the repository has migrated. 

It would be nice to have the ddsarama.WithDataStreams() option available for IBM/sarama.

IBM/sarama is using the same code base. 

(Disclaimer: I can try creating this PR - first time on looking at this project, I think I've read through all of the contrib docs)

**Comment by rarguelloF** [comment]
Hi @KyleWiering and sorry for the delayed response.

All contributions are welcome! I will be happy to review and merge your PR.
