### ISSUE TITLE
[BUG] Hostname providers spamming traces

### ISSUE THREAD

**Issue by adrianlungu** [DataDog/dd-trace-go#2575]
The `providerCatalog` has a set of providers that seem to be running regardless of any configuration given to the tracer; this sometimes leads to a behavior where traces are being spammed, as follows, with a call to `egress 169.254.169.254`. 

![Screenshot 2024-02-26 at 11 25 26](https://github.com/DataDog/dd-trace-go/assets/1700129/df40dcf4-a10c-40ff-9331-6d692226f7a7)

Ideally this could be configured somehow, or at least have a way to address what to do in case a provider cannot be reached so we can silence it if we don't use some of the specified providers; or maybe make it customizable which provider should be contacted and which not ? 

**Version of dd-trace-go**

v1.60.3

**Describe what happened:**

The internal hostname providers are being called and leads to a spam of traces with `egress 169.254.169.254`, url being `http://169.254.169.254/computeMetadata/v1/instance/hostname`. 

**Describe what you expected:**

Not to have these traces sent to datadog. 

**Steps to reproduce the issue:**
N/A - it can be reproduced just by enabling the tracer. 

**Additional environment details (Version of Go, Operating System, etc.):**

- Go 1.22 (same behavior with 1.21.x) 
- MacOS 14.3

**Comment by darccio** [comment]
@adrianlungu The provider that triggers the HTTP request is only activated if the hostname has one of the following prefixes:

```go
 	defaultPrefixes = []string{"ip-", "domu", "ec2amaz-"}
```

How does your hostname look like? Also, how is your service instrumented?

**Comment by darccio** [comment]
Thanks @adrianlungu, you are right. I'll check it again.
