### ISSUE TITLE
contrib/gofiber/fiber.v2: possibility to exclude spans generation for specific requests

### ISSUE THREAD

**Issue by nsakharenko** [DataDog/dd-trace-go#2582]
In order to be able to exclude spans on an application level, we need to have a possibility to prevent span generation in a [Middleware](https://github.com/DataDog/dd-trace-go/blob/main/contrib/gofiber/fiber.v2/fiber.go#L32).

Other popular frameworks has this feature:
- [gin-gonic](https://github.com/DataDog/dd-trace-go/blob/main/contrib/gin-gonic/gin/option.go#L26)
- [go-chi](https://github.com/DataDog/dd-trace-go/blob/8a989a5fccdddcbd19cd14c847c60d7d2fb306b3/contrib/go-chi/chi/chi.go#L46)

**Comment by nsakharenko** [comment]
I prepared feature implementation, but not able to push it. So if i can have permission to do that, will create a PR.

**Comment by darccio** [comment]
This will be released in next version `v1.62.0`. The release train is going to start soon as per our usual cadence.
