### ISSUE TITLE
Add support for custom tags to gqlgen contrib

### ISSUE THREAD

**Issue by samsullivan** [DataDog/dd-trace-go#2597]
Most contrib tracer packages expose a `WithCustomTags` option: https://github.com/search?q=repo%3ADataDog%2Fdd-trace-go+WithCustomTag+path%3Acontrib&type=code

One exception is the `gqlgen` package: https://github.com/DataDog/dd-trace-go/blob/63d7047cfd4d8e3d078dc5460fb385e544c2eb1d/contrib/99designs/gqlgen/option.go

This seems super easy to add, so I'm happy to open a PR; however, I saw that you want an open issue first for changes other than bug fixes.

**Comment by felixge** [comment]
Thanks for raising this issue and PR 🙇 . I see no reason against adding this feature. I'll ping the team to get you a review/merge.

**Comment by samsullivan** [comment]
Sweet, thanks @felixge; it'll be nice to remove the custom GQL spans from my app, so they can be tagged correctly for our retention policies 👍

I'm assuming this would need to wait for a new minor version, not a patch release, seeing how it's added functionality? Or is it small enough for the next patch release after merge?

**Comment by felixge** [comment]
Yes, this would need a minor release. We only do patch releases for critical fixes. However, we do one minor release per month, so your code would be released relatively soon after merging.

**Comment by samsullivan** [comment]
Thanks!

**Comment by dianashevchenko** [comment]
Hi there @samsullivan, I confirm that there's no reason not to add it :) . If you create a PR, you can tag me and I will review it right away 🙇

**Comment by samsullivan** [comment]
Thanks again, both!
