### ISSUE TITLE
gintrace can't set span in context

### ISSUE THREAD

**Issue by hawknewton** [DataDog/dd-trace-go#26]
`tracer/contrib/gin-gonic/gintrace.go` is currently broken as it has the [wrong context key](https://github.com/Datadog/dd-trace-go/blob/master/tracer/contrib/gin-gonic/gintrace/gintrace.go#L14).

It looks like [Context.spanKey](https://github.com/Datadog/dd-trace-go/blob/master/tracer/context.go#L9) was [changed recently](https://github.com/Datadog/dd-trace-go/commit/7a59dee73ef39e5f3b72e58fed8f9cb939a60e05) from a string to a struct.

I'd open a PR to fix the problem but unfortunately gin's implementation of `context.Context` [only accepts](https://github.com/gin-gonic/gin/blob/master/context.go#L159) string keys.

**Comment by galdor** [comment]
Do you have an example which breaks with the current code ?

**Comment by hawknewton** [comment]
[this test](https://github.com/DataDog/dd-trace-go/pull/27/commits/db7e0c4e633d94fddaf198383f7aa8a296679be4) fails on master.

**Comment by furmmon** [comment]
Fixed on #29, thanks for the fix
