### ISSUE TITLE
[BUG] Update dependencies to avoid vulnerabilities

### ISSUE THREAD

**Issue by EduardoGabrielWehrmeister** [DataDog/dd-trace-go#2632]
Our company has identified a critical vulnerability in one of the dependencies of the dd-trace-go library. To fix it, simply update the affected dependency.

**Version of dd-trace-go**

`v1.57.0`

**Describe what happened:**

Vulnerability **Critical**:

 - `github.com/gofiber/fiber` - Origin Validation Error
     - Current Version: `v2.50.0`
     - Fixed In Version: `2.52.1`

**Additional environment details (Version of Go, Operating System, etc.):**

`go 1.20`

**Comment by darccio** [comment]
@EduardoGabrielWehrmeister Thanks for sharing the patch. We understand your concerns, and we want to share that you can fix it in your side by pinning `github.com/gofiber/fiber/v2` to `v2.52.1`. This is explained in our [security policy](https://github.com/DataDog/dd-trace-go/blob/main/SECURITY.md#vulnerabilities-in-contrib-dependencies):

> If you are using a vulnerability checker other than golang.org/x/vuln/vulncheck you may detect vulnerabilities in our contrib dependencies. In general we like to specify non-vulnerable minimum versions of dependencies when we can do so in a non-breaking way. To avoid breaking users of this library there may be contrib libraries that are deprecated/vulnerable but still appear in our go.mod file. If you are not using these contrib packages you are not vulnerable (i.e. if they do not appear in your go.sum file). At the next major version we will drop support for these packages. (e.g. as of dd-trace-go@v1 labstack/echo v3 is considered deprecated and users should migrate to labstack/echo.v4)
> Note that since library go.mod files only specify minimum version requirements you are welcome to specify a newer version of any dependencies to satisfy your tooling. For example, if you would like to require a library like github.com/labstack/echo/v4 use version v4.10.0 you can do so by running go get github.com/labstack/echo/v4@v4.10.0. 

We also recommend you to upgrade as soon as the next version is released, as it's been updated to Fiber `v2.52.1`. If there is any reason you need to stick to `v1.57.x`, please share with us the reason and we'll help you.

**Comment by EduardoGabrielWehrmeister** [comment]
@darccio I made the modifications according to your instructions and everything worked perfectly. I am immensely grateful for the assistance!

**Comment by darccio** [comment]
@EduardoGabrielWehrmeister I'm glad that I was able to help. I'm closing this issue. Thanks!
