### ISSUE TITLE
Stats for contrib/jackc/pgxpool

### ISSUE THREAD

**Issue by bengentree** [DataDog/dd-trace-go#2680]
Basically the same request as https://github.com/DataDog/dd-trace-go/issues/2303 but using the [pgxpool stats](https://pkg.go.dev/github.com/jackc/pgx/v5/pgxpool#Stat) to periodically report pool stats. Happy to contribute as well, thanks in advance.

**Comment by mtoffl01** [comment]
Hello! I've been looking into this. Can you share how you configure the tracer's DogstatsD address? Do you use the env var DD_DOGSTATSD_URL? 
Thanks!

**Comment by bengentree** [comment]
> Hello! I've been looking into this. Can you share how you configure the tracer to connect via UDS? What config options are you using, including env vars? Thanks!

Hi, are you referring to the statsd connection? I configure the client using `hostname:port` for UDP currently.

**Comment by mtoffl01** [comment]
@bengentree ,
The existing DB Stats feature exists _only_ on the [database/sql contrib](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1@v1.63.1/contrib/database/sql), we don't yet have support for other related integrations.
To clarify, are you using the database/sql integration, or the [jackc/pgx.v5 integration](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1@v1.63.1/contrib/jackc/pgx.v5)?
