### ISSUE TITLE
contrib/gorilla/mux: resource name comes as "unknown" in mux integration

### ISSUE THREAD

**Issue by aarrtteemmuuss** [DataDog/dd-trace-go#269]
In mux integration, ServeHTTP method, var route often stays unknown. 
For example when I go to http://127.0.0.1:8000/v1/records trace comes with resource GET unknown. If I do http://127.0.0.1:8000/v1/records/new it comes as GET /v1/records/new.

Suggested fix: can we just do route = req.URL.Path instead of matching pattern? I checked this in my local project and it works. 

```go
func (r *Router) ServeHTTP(w http.ResponseWriter, req *http.Request) {
	var (
		match mux.RouteMatch
		route = "unknown"
	)
	// get the resource associated to this request
	if r.Match(req, &match) && match.Route != nil {
		if r, err := match.Route.GetPathTemplate(); err == nil {
			route = r
		}
	}
	resource := req.Method + " " + route
	httputil.TraceAndServe(r.Router, w, req, r.config.serviceName, resource)
...
}

**Comment by gbbr** [comment]
Thanks for reporting this. I agree it could be better. I'm afraid we won't be able to use `req.URL.Path` though because it might contain sensitive information.

**Comment by art-ivaschenko** [comment]
I think that usually `req.URL.Path` will contain only path itself, no query will be attached to it, because it might include tokens, keys and other sensitive data, if you are talking about that.

**Comment by gbbr** [comment]
@art-ivaschenko sorry for the late response here. Let's try and find a good way to solve this. I wonder which ones are the cases where the route stays `unknown`. Would you be able to help me reproduce this?

**Comment by gbbr** [comment]
I'm going to close this since it's gone stale. Please feel free to ping me and we can reconsider if you wish to pursue it...
