### ISSUE TITLE
Profiler: Add ability to override logger

### ISSUE THREAD

**Issue by seanamos** [DataDog/dd-trace-go#2712]
The tracer allows you to overwrite the logger to either disable it or force it to conform to your logging standards:

```go
tracer.Start(tracer.WithLogger(...))
```

The profiler offers no such option so you are stuck with whatever format and messages the profiler might periodically produce.

**Comment by nsrip-dd** [comment]
You can use [`ddtrace.UseLogger`](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/ddtrace#UseLogger) to give the same logger to both the tracer and the profiler.
