### ISSUE TITLE
Headers not propagated across custom spans within trace

### ISSUE THREAD

**Issue by sahilqc** [DataDog/dd-trace-go#2717]
Hi Moderators, 

I was looking at this document "https://docs.datadoghq.com/tracing/trace_collection/trace_context_propagation/go/" for propagating headers throughout the trace, but its not available after first default web span.

I have added all of supported styles under environment variables, and even under application docker env variables, yet I don't see them..
Am I doing something wrong here? Tried to apply same to your tutorial application but no success there too.

Basically, I want to see headers available throughout the trace which will be helpful in creating dashboards and distributed tracing "https://docs.datadoghq.com/tracing/trace_collection/custom_instrumentation/go/dd-api/".

  datadog-agent:
    container_name: datadog-agent
    image: "gcr.io/datadoghq/agent:latest"
    pid: host
    environment:
      - DD_API_KEY=xxx
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_TRACE_PROPAGATION_STYLE_INJECT=tracecontext,B3,datadog,B3 single header
      - DD_TRACE_PROPAGATION_STYLE_EXTRACT=tracecontext,B3,datadog,B3 single header

**Comment by felixge** [comment]
@sahilqc could you please open a support ticket for this? I think we'll also need a few more details on what your incoming and outgoing requests look like (http, grpc, ... ?) and what your code looks like. I'm closing this ticket for now, but feel free to reopen if you prefer to continue the discussion here for some reason.
