### ISSUE TITLE
contrib/jackc/pgx.v5: trace acquire and release

### ISSUE THREAD

**Issue by ngavinsir** [DataDog/dd-trace-go#2721]
pgx pool has two new tracing interfaces [AcquireTracer](https://pkg.go.dev/github.com/jackc/pgx/v5/pgxpool#AcquireTracer) and [ReleaseTracer](https://pkg.go.dev/github.com/jackc/pgx/v5/pgxpool#ReleaseTracer). We should add support for those.

**Comment by felixge** [comment]
Thanks for raising this issue and for the PR you submitted. I see no reason why we would not want to support this, so I'm marking the issue as `proposal/accepted`. I'll ping some more folks to look at the PR. Sorry for the delay.
