### ISSUE TITLE
proposal: have integrations inherit global service name

### ISSUE THREAD

**Issue by mbyio** [DataDog/dd-trace-go#273]
Currently, if I setup the unary server interceptor, even if I set the service name on the global tracer to be something specific (like "my-service"), the unary server interceptor will override that and change the service name to "grpc.server". This is surprising IMO because if you start a span manually (eg. with `tracer.StartSpanFromContext`), that _does_ pick up the global service name.

Besides being a little confusing, this behavior also means I have to thread the service name through multiple calls during setup, which makes the code harder to read and test.

**Comment by gbbr** [comment]
Thanks for reporting this. You're right, this can indeed be surprising and unexpected behavior when you would like to share your "default" service name with an integration. I think the question to ask here is: will this have the desired result? If yes, why?

In general all of the targets of our integrations are by definition a different service. For this reason, using the same service name as the rest of our application would cause us to lose the following benefits:
* Having the ability to isolate the integrated service in the Datadog application for monitoring and performance studies.
* Having the ability to visually differentiate between spans belonging to a shared service and spans belonging to a trace using that service.

It is valuable to keep these separate. Given all this, would you still feel you need to use the same service name? Are you trying to accomplish something I've not considered?

**Comment by mbyio** [comment]
I haven't forgotten about this, but haven't had a chance to write down my thoughts yet. I have some feedback from my org that I'm trying to assemble.

**Comment by gbbr** [comment]
This is a good proposal and I think we should consider doing it. It should easily be achievable now by means of the `globalconfig` package. 

However, marking for v2 because it would be a breaking change.

**Comment by geekflyer** [comment]
I just wanted to add that the current behaviour is inconsistent with datadog's other tracing libraries and I think fixing this should be a high priority. 
I spend probably an entire day to debug / figure out where the traces from library integrations end-up and now just realized that dd-trace-go basically doesn't reuse the service name from the global tracer.

How the other datadog trace libraries work (using dd-trace-js as example) work:
They **use the service name of the global tracer as prefix**. 

For example for the dd-trace-js library if you set as service name `myapp` you end up getting a separate service for each integration like:
- myapp-http-client
- myapp-dns
- myapp-elasticsearch
- myapp-redis
- myapp-postgres

This is imho how dd-trace-go should work as well to avoid confusion.

Could you please prioritize this in the short term?
I understand this is may be considered a breaking change, so if that's a large concern perhaps introduce a StartOption like `tracer.WithUseServiceNameAsPrefix(true)` or something like that.

Thanks!

**Comment by gbbr** [comment]
@geekflyer thanks for bringing this to our attention. We will be making this change soon.

**Comment by gbbr** [comment]
@geekflyer I feel like my message might've been too brief and could lead to confusion or misunderstanding. What I meant to say is that we are working and will be making changes in this area (around things discussed in this issue), but not that we will be making the particular change you are suggesting. We want to minimise the amount of of breaking changes. I'll keep the issue updated as we proceed.

**Comment by gbbr** [comment]
This was addressed and is now possible as of https://github.com/DataDog/dd-trace-go/pull/614
