### ISSUE TITLE
[BUG] fatal error: concurrent map writes when using contrib/net/http.(*roundTripper).RoundTrip

### ISSUE THREAD

**Issue by shreyaspurohit** [DataDog/dd-trace-go#2738]
**Version of dd-trace-go**
1.64.0

**Describe what happened:**
fatal error: concurrent map writes when using `contrib/net/http.(*roundTripper).RoundTrip` due to `tracer.(*span).setMetric(` calling `delete(s.Meta, key)` at high loads.

We use the `contrib/net/http` and [RoundTrip](https://github.com/DataDog/dd-trace-go/blob/main/contrib/net/http/roundtripper.go#L28) with http client to make calls to external APIs. At very high loads, we get `fatal error:   concurrent map writes`. The stacktrace is below:
```
/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.64.0/contrib/net/http/roundtripper.go:72   +0xa3f
gopkg.in/DataDog/dd-trace-go.v1/contrib/net/http.(*roundTripper).RoundTrip(0xc00181a210,   0xc001713b00)
/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.64.0/ddtrace/tracer/tracer.go:205   +0x91
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.Inject({0x1683410?,   0xc0013b4900?}, {0x12c5aa0?, 0xc001aa9650?})
/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.64.0/ddtrace/tracer/tracer.go:683   +0x50
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*tracer).Inject(0xc0000cf8c0,   {0x1683410, 0xc0013b4900}, {0x12c5aa0, 0xc001aa9650})
/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.64.0/ddtrace/tracer/tracer.go:712   +0xca
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*tracer).updateSampling(0xc0000cf8c0,   {0x1683410?, 0xc0013b4900?})
/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.64.0/ddtrace/tracer/rules_sampler.go:47
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*rulesSampler).SampleTrace(...)
/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.64.0/ddtrace/tracer/rules_sampler.go:516   +0x170
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*traceRulesSampler).sampleRules(0xc000588540,   0xc001522e10)
/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.64.0/ddtrace/tracer/rules_sampler.go:521   +0x55
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*traceRulesSampler).applyRate(0xc000588540,   0xc001522e10, 0x3ff0000000000000, {0x1?, 0x30?, 0x2097aa0?}, 0x3)
/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.64.0/ddtrace/tracer/span.go:442   +0x85
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*span).setMetric(0xc001522e10,   {0x14519c7, 0xc}, 0x3ff0000000000000)
```

Looking at the [code](https://github.com/DataDog/dd-trace-go/blob/v1.64.0/ddtrace/tracer/span.go#L442) where it fails, looks like the method has been called out to be not thread safe and the delete from the map might cause this issue. The `contrib/net/http.WrapRoundTripper` is initialized once for the httpClient and the same client is reused across all the API calls in a go func. 

**Describe what you expected:**
No Error.

**Steps to reproduce the issue:**

**Additional environment details (Version of Go, Operating System, etc.):**
Go version: 1.21.3, Linux

**Comment by darccio** [comment]
Hi @shreyaspurohit, thanks for reporting this. It's already fixed in #2734 and it'll be released today as part of `v1.65.0`.
