### ISSUE TITLE
Go 1.19 no longer works

### ISSUE THREAD

**Issue by kurochan** [DataDog/dd-trace-go#2750]
**Version of dd-trace-go**
[v1.65.0](https://github.com/DataDog/dd-trace-go/releases/tag/v1.65.0) or later.

**Describe what happened:**

As of today, Go 1.19 is described as Legacy support.
https://github.com/DataDog/dd-trace-go/blob/7bde0099d183af7b3d4303cdbd5244cb65115834/README.md?plain=1#L63

However, `DataDog/go-libddwaf` has been updated to v3 with this commit.
https://github.com/DataDog/dd-trace-go/pull/2670/files#diff-ec164f4b371c6a6171390de4d3501d899efefeb04274d6622327743358004a57R12

`DataDog/go-libddwaf` dropped support of Go 1.19 after this change.
https://github.com/DataDog/go-libddwaf/pull/89
https://github.com/DataDog/go-libddwaf/releases/tag/v3.0.0

**Describe what you expected:**
Drop support Go 1.19

**Comment by eliottness** [comment]
Hello :wave: 

The [Support Policy](https://github.com/DataDog/dd-trace-go#support-policy) section describes *legacy* support like this:
> Legacy implementation. May have limited function, but no maintenance provided. Not guaranteed to compile the latest version of dd-trace-go

Which is technically correct on that front but I understand that this is confusing. Removing this line in the README seems to be the quickest option here.

**Comment by kurochan** [comment]
@eliottness 
This time, dd-trace-go no longer compiles with go 1.19 because the dependent libraries have adopted the new features of go 1.20 (`errors.Join`). That's why I suggested it.

Thanks for your response!
