### ISSUE TITLE
[BUG] 99designs/gqlgen/tracer.go: panic cause nil pointer

### ISSUE THREAD

**Issue by dienvoandpadcojp** [DataDog/dd-trace-go#2791]
I was implement graphQL subscription, it just a simple subscription like this (https://gqlgen.com/recipes/subscriptions/) but I want to stop the subscription in server side so I close the response channel when there is no more data. But I found that in [99designs/gqlgen/tracer.go#L119 ](https://github.com/DataDog/dd-trace-go/blob/main/contrib/99designs/gqlgen/tracer.go#L119), there is missing check response nil. I think because we have to trace even if the response is nil, but when we get `Data` and `Error` from response it lead to panic.
 
**Version of dd-trace-go**
v1.65.1
**Describe what happened:**
When I want to stop the subscription from server side. I close channel and then I got panic: `runtime error: invalid memory address or nil pointer dereference`
**Describe what you expected:**
No panic when response from `responseHandler(ctx)` is nil

**Steps to reproduce the issue:**

**Additional environment details (Version of Go, Operating System, etc.):**

**Comment by darccio** [comment]
Released in `v1.69.0`.
