### ISSUE TITLE
[BUG]  appsec golang 1.23

### ISSUE THREAD

**Issue by fcarrero** [DataDog/dd-trace-go#2818]
2024/08/17 23:42:48 Datadog Tracer v1.66.0 ERROR: appsec: threats detection cannot be enabled for the following reasons: unsupported Go version: go1.23.0appsec: no security activities will be collected. Please contact support at https://docs.datadoghq.com/help/ for help. (occurred: 17 Aug 24 23:41 UTC)

![image](https://github.com/user-attachments/assets/37919a0e-ddd4-4173-8c40-8bf1f0a5a2ea)

**Comment by eliottness** [comment]
Hello @fcarrero 

This issue is fixed in v1.67.0 which should be released not so long from now. You can already try the last release candidate tag if you don't want to wait.

Please close the issue when you want to. Have a wonderful day
