### ISSUE TITLE
[BUG] contrib/database/sql: Wrong statsd tags when using WithDBStats & WithCustomTag options

### ISSUE THREAD

**Issue by rolandhawk** [DataDog/dd-trace-go#2836]
**Version of dd-trace-go**
v1.67.0

**Describe what happened:**
The original implementation
```go
tags := globalconfig.StatsTags()
...
tags = append(tags, ...)
```

Every call of `statsTags` shares the same initial `globalconfig.StatTags()` slice. Even thought the `append` function will assign new slice, the array behind the slice will be the same one if `append` function determine that it does not necessary to allocate new array. And when this happen `statsTags` will effectively pollute the array behind `globalconfig.StatTags()` slice.

This become a problem when you have multiple database/sql setup like this:
```go
sqltrace.Register("mysql", driver, sqltrace.WithServiceName("database"))

master, _ := sqltrace.Open("mysql", "mysql://user@master/test", sqltrace.WithDBStats(), sqltrace.WithCustomTag("instance", "master"))
replica, _ := sqltrace.Open("mysql", "mysql://user@replica/test", sqltrace.WithDBStats(), sqltrace.WithCustomTag("instance", "replica"))
```
The setup above will result `datadog.tracer.sql.*` metrics to have tags `instance:replica` for both master's DBStats and replica's DBStats

**Describe what you expected:**
DBStats metrics have correct tags.

**Steps to reproduce the issue:**
```go
sqltrace.Register("mysql", driver, sqltrace.WithServiceName("database"))

master, _ := sqltrace.Open("mysql", "mysql://user@master/test", sqltrace.WithDBStats(), sqltrace.WithCustomTag("instance", "master"))
replica, _ := sqltrace.Open("mysql", "mysql://user@replica/test", sqltrace.WithDBStats(), sqltrace.WithCustomTag("instance", "replica"))
```

**Additional environment details (Version of Go, Operating System, etc.):**
go 1.22.3

**Comment by mtoffl01** [comment]
This should be addressed in the PR linked above.
