### ISSUE TITLE
datadog trace retention time?

### ISSUE THREAD

**Issue by zdyj3170101136** [DataDog/dd-trace-go#2853]
In Datadog's trace tail sampling strategy (https://docs.datadoghq.com/tracing/trace_pipeline/trace_retention/), whether to sample depends on whether the trace has p99 latency, etc.

I assume that this may be implemented by saving each trace in memory by traceid, and then judging after a period of time.

How long will the trace be retained in memory?

**Comment by zdyj3170101136** [comment]
> 你好@zdyj3170101136， 我不确定我是否理解：您链接到的文档描述了我们的跟踪保留策略（即，一旦跟踪被摄取/“采样”，它会在 Datadog 平台中保留多长时间）。
> 
> Datadog 平台上的痕迹的标准保留期为 15 天。
> 
> 如果我上面没有回答，请澄清你的问题。谢谢！

i wonder  how much time it would retain in memory.

if i have a long trace, the first span is 1 days ago and last span is current, would it be store by p99 policy?

**Comment by mtoffl01** [comment]
Generally speaking, the client will retain a trace until all spans in the trace have completed. Once all the spans in the trace have completed, the client pushes the trace onto the buffer to be written out to the agent. The client flushes traces to the agent at an interval of 2s.

I'm not sure what "p99 policy" you're referring to; the only p99 calculation relating to traces that I can think of is the [DDSketch metrics](https://docs.datadoghq.com/tracing/guide/ddsketch_trace_metrics/) for span duration, which is not computed in the tracer.
