### ISSUE TITLE
[BUG] Error getting metrics profile: period between metrics collection is too small

### ISSUE THREAD

**Issue by SvenGasterstaedt** [DataDog/dd-trace-go#2863]
When our service is terminating, the corresponding dd profiler is terminated as well via `profiler.Stop()`

This results in an interupt of the sleep period of the profiler in (which may on some occasions be smaller then 1 sec)
![image](https://github.com/user-attachments/assets/8f2209f0-3b94-404f-b275-eb34a0dd4071)
![image](https://github.com/user-attachments/assets/88680222-e534-44db-b0e3-47f87350158f)
![image](https://github.com/user-attachments/assets/4e3bd897-a386-40c4-9653-767e73eea88e)

**Version of dd-trace-go**
v1.67.1

**Describe what happened:**
`Datadog Tracer v1.67.1 ERROR: Error getting metrics profile: period between metrics collection is too small min=1s observed=573.458102ms; skipping. (occurred: 13 Sep 24 09:49 UTC)`

**Describe what you expected:**
No error when the service is shutting down and the profiler is terminating (even if it just reported its metrics)

**Steps to reproduce the issue:**
-

**Additional environment details (Version of Go, Operating System, etc.):**
go 1.23.1

**Comment by nsrip-dd** [comment]
Thanks for the report. I'll see if we can handle this better.
