### ISSUE TITLE
Support configurable error reporting based on status code in net/http 

### ISSUE THREAD

**Issue by nakkamarra** [DataDog/dd-trace-go#2876]
Many of the other frameworks supported in `contrib` offer something along the lines as what the [echo dd-trace-go package offers here](https://github.com/DataDog/dd-trace-go/blob/main/contrib/labstack/echo.v4/option.go#L27), where a user can provide a function to determine whether or not a given trace should be considered an error (i.e a user wants to report 400s as errors or want to not report a single specific code for some reason)

I suggest we support something similar [here](https://github.com/DataDog/dd-trace-go/blob/v1.67.1/contrib/net/http/trace.go#L53) and update [this check](https://github.com/DataDog/dd-trace-go/blob/main/contrib/internal/httptrace/httptrace.go#L74-L76) to use the new configured function instead. This way, explicit usage of `TraceAndServe(...)` can supply a function for it's `ServeConfig` (my use case), and the `contrib/net/http` package's dependence upon this function can also provide a functional option to it's ServeMux's configuration that can simply pass right through to this `TraceAndServe` function.

LMK what you think! Thanks

**Comment by mtoffl01** [comment]
Responded on the PR https://github.com/DataDog/dd-trace-go/pull/2882. Let's keep the discussion over there, and I will close this proposal.
