### ISSUE TITLE
[BUG] The pgx integration silently overwrites other tracers

### ISSUE THREAD

**Issue by mbyio** [DataDog/dd-trace-go#2908]
**Version of dd-trace-go**

Latest version v1.68.0

**Describe what happened:**

If you take a look at this code, you can see the problem:
https://github.com/DataDog/dd-trace-go/blob/main/contrib/jackc/pgx.v5/pgxpool.go#L24

The datadog tracing integration overwrites any existing Tracer in the pgx config.

**Describe what you expected:**

Datadog should *wrap* any existing tracers it finds, instead of just overwriting them.

For our specific use case, we want to add debug logging for all database queries. In pgx, the way to do that is to add a tracer to the config. Unfortunately, Datadog silently overwrites our custom tracer, so we can't add logging.

**Comment by rarguelloF** [comment]
Hello @mbyio and thanks for reporting this issue! I've confirmed this is indeed a problem, so we will handle as soon as possible.
