### ISSUE TITLE
Should clone record before calling .Add on it for the Go "slog" integration

### ISSUE THREAD

**Issue by cideM** [DataDog/dd-trace-go#2918]
I noticed that the [Go integration for `slog`](https://github.com/DataDog/dd-trace-go/blob/v1.68.0/contrib/log/slog/slog.go#L45-L48) does not call `rec.Clone()` before adding to the record. [The documentation for `slog` states](https://pkg.go.dev/log/slog#hdr-Working_with_Records):

> Sometimes a Handler will need to modify a Record before passing it on to another Handler or backend. A Record contains a mixture of simple public fields (e.g. Time, Level, Message) and hidden fields that refer to state (such as attributes) indirectly. **This means that modifying a simple copy of a Record (e.g. by calling [Record.Add](https://pkg.go.dev/log/slog#Record.Add) or [Record.AddAttrs](https://pkg.go.dev/log/slog#Record.AddAttrs) to add attributes) may have unexpected effects on the original.** Before modifying a Record, use [Record.Clone](https://pkg.go.dev/log/slog#Record.Clone) to create a copy that shares no state with the original, or create a new Record with [NewRecord](https://pkg.go.dev/log/slog#NewRecord) and build up its Attrs by traversing the old ones with [Record.Attrs](https://pkg.go.dev/log/slog#Record.Attrs).

**Comment by felixge** [comment]
Thanks for spotting this. https://github.com/DataDog/dd-trace-go/pull/2929 should fix it.
