### ISSUE TITLE
[BUG] Panic from v1.66 on startup

### ISSUE THREAD

**Issue by picollomartin** [DataDog/dd-trace-go#2923]
**Version of dd-trace-go**
v.1.68.0

**Describe what happened:**
With an upgrade from version 1.58 to latest 1.68, tracer start to panic

We trace down the panic to this [PR](https://github.com/DataDog/dd-trace-go/pull/2748), because occurs here:

https://github.com/DataDog/dd-trace-go/blob/5b9a8af2b241ec60b990840add9da5799c3c811b/ddtrace/tracer/log.go#L130-L131

Workaround is disable startup log (by env variable or in code)

**Describe what you expected:**
Not panic, instead if propagator is not the expected one ignore those fields

**Steps to reproduce the issue:**

- Override with some custom propagator using `tracer.WithPropagator`
- Start tracer with `tracer.WithLogStartup(true)` (enabled by default, you can skip this)
- Tracer panics when reach [this lines](https://github.com/DataDog/dd-trace-go/blob/5b9a8af2b241ec60b990840add9da5799c3c811b/ddtrace/tracer/log.go#L130-L131)

**Additional environment details (Version of Go, Operating System, etc.):**
Go 1.22 - linux

**Comment by mtoffl01** [comment]
Thanks for reporting this! We're working on a fix for it now.
