### ISSUE TITLE
Question about release version

### ISSUE THREAD

**Issue by gbarsky** [DataDog/dd-trace-go#2928]
Could you please advise in what version of dd-trace-go we can see the fix submitted by this PR 
https://github.com/DataDog/dd-trace-go/pull/2792

Thank you
Gera

**Comment by rarguelloF** [comment]
Hi @gbarsky , you can see it is included in the upcoming [v1.69.0 release](https://github.com/DataDog/dd-trace-go/releases/tag/untagged-e9632e6fbfcf9a8ef7fe).

**Comment by gbarsky** [comment]
Thank you
