### ISSUE TITLE
Unexpected Relocation Error for Dynamic Symbol __CFConstantStringClassReference When Running Unit Tests

### ISSUE THREAD

**Issue by juri-t** [DataDog/dd-trace-go#3000]
After updating dd-trace-go, I encountered an issue where running unit tests outputs the following error log:

```bash
github.com/shoenig/go-m1cpu(__DATA/__cfstring): unexpected reloc for dynamic symbol __CFConstantStringClassReference
```

This appears to have been introduced in [this PR](https://github.com/DataDog/dd-trace-go/pull/2817/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R251), where the library github.com/shoenig/go-m1cpu was added as a dependency.

While the tests continue to work as expected, this log is very noisy and clutters the output, making debugging other issues difficult.

Could you provide guidance on how to suppress or resolve this error log?

Any help would be greatly appreciated!

**Comment by darccio** [comment]
Hi @juri-t, thanks for reaching to us. It's possible that you are [forcing internal linking mode](https://github.com/mattn/go-sqlite3/issues/404#issuecomment-290398361), which it isn't well supported when compiling with CGO enabled.

We were able to reproduce it. Assuming a simple program like this one:

```go
package main

import (
	"fmt"
	"net/http"

	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
)

func main() {
	tracer.Start(tracer.WithServiceName("hello-world"))
	defer tracer.Stop()

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		span, _ := tracer.StartSpanFromContext(r.Context(), "register")
		defer span.Finish()

		fmt.Fprintf(w, "Hello world!")
	})
	http.ListenAndServe(":3000", nil)
}
```

Compiled as is, it doesn't complain. If we set `GOFLAGS='-ldflags=-linkmode=internal'` we get the warnings you see:

```
❯ export GOFLAGS='-ldflags=-linkmode=internal'
❯ go clean && go build .
# go-http-puppy
github.com/shoenig/go-m1cpu(__DATA/__cfstring): unexpected reloc for dynamic symbol __CFConstantStringClassReference
github.com/shoenig/go-m1cpu(__DATA/__cfstring): unexpected reloc for dynamic symbol __CFConstantStringClassReference
github.com/shirou/gopsutil/v3/cpu._Cvar_mach_task_self_: relocation target mach_task_self_ not defined
```

If we set `CGO_ENABLED=0`, the warnings go away:

```
❯ export CGO_ENABLED=0
❯ go clean && go build .
❯ echo $?
0
```

Make sure you don't use internal linking mode unless strictly required. In that case, if you can work with `CGO_ENABLED=0`, that will get rid of the warnings.

**Comment by juri-t** [comment]
Thank you for the quick response.
I have confirmed that setting `CGO_ENABLED=0` has resolved the warning.

I am using `GOFLAGS='-ldflags=-linkmode=internal'` to suppress the following warning:
```
ld: warning: '/private/var/folders/qj/yfmd02rj21v9fwc_bhp3dvj40000gn/T/go-link-4078882021/000020.o' has malformed LC_DYSYMTAB, expected 98 undefined symbols to start at index 1626, found 95 undefined symbols starting at index 1626
```

The issue has been resolved. Thank you.
