### ISSUE TITLE
Name, service, and resource?

### ISSUE THREAD

**Issue by roustem** [DataDog/dd-trace-go#31]
I am having a hard time trying to understand the logic behind SetServiceInfo and the difference between the name, service, and resource.

I re-read the source code several time and I still end up just trying difference variations of names in `NewRootSpan` to get the result I want.

Is there any documentation that explains the difference between them? It seems that it would be much simpler to just have a name and type for each span and use meta for everything else.

**Comment by furmmon** [comment]
Hey @roustem, the documentation on the terminology can be found here https://docs.datadoghq.com/tracing/terminology/#overview, feel free to ask us questions on our public slack channel `datadoghq.slack.com` in the channel #apm
