### ISSUE TITLE
How do I set more than one custom config option on a tracer?

### ISSUE THREAD

**Issue by mapleoin** [DataDog/dd-trace-go#311]
I'd like to set both a custom AgentAddr **and also** ServiceName, but there doesn't seem to be a way to do that when creating a `StartOption`? `tracer.WithAgentAddr` and `tracer.WithServiceName` both return a `StartOption`, but neither accepts a `StartOption` and the `tracer.config` struct is not public.

**Comment by dd-caleb** [comment]
Hi @mapleoin . `Start` takes multiple options:

```go
func Start(opts ...StartOption)
```

So you can pass:

```go
tracer.Start(tracer.WithAgentAddr("127.0.0.1:1234"), tracer.WithServiceName("some-service-name"))
```

If you need to do this conditionally, you can create a slice:

```go
opts := []tracer.StartOption{tracer.WithAgentAddr("127.0.0.1:1234")}
if somecondition {
    opts = append(opts, tracer.WithServiceName("some-service-name"))
}
tracer.Start(opts...)
```

Does that help?

**Comment by mapleoin** [comment]
Sounds great. Thanks!
