### ISSUE TITLE
proposal: add support for Google APIs

### ISSUE THREAD

**Issue by dd-caleb** [DataDog/dd-trace-go#312]
The [google.golang.org/api](https://github.com/google/google-api-go-client) package is used to interact with various Google APIs and is auto-generated from service definitions. Adding tracing support in a generic way would help anyone who uses Google APIs extensively.

There is also the similar [cloud.google.com/go] package, which is used for many GCP apis (like storage and compute).

I think we should be able to create an `http.RoundTripper` that will trace all of these HTTP calls similar to how we did the Kubernetes integration. We can generate the routing rules using the same definition files that were used to generate the package.

**Comment by gbbr** [comment]
I guess we already did
