### ISSUE TITLE
ddtrace/tracer: sampler should add sampling.priority

### ISSUE THREAD

**Issue by JackWink** [DataDog/dd-trace-go#321]
In the python tracer, the SDK [decides whether or not to keep a root span](https://github.com/DataDog/dd-trace-py/blob/5a65259023bd7f846e913c5e23a94d1f5ad45f74/ddtrace/tracer.py#L218). 

I could not find anything in this SDK that does something similar. It looks like propagation is set up for child spans, but no initial sampling. Is this a planned feature? Will we run into issues if we set every root span to AUTO_KEEP (1) and continue to propagate child span priority from our other (non-go) services?

**Comment by JackWink** [comment]
Perhaps the sample priority attribute needs to be set around https://github.com/DataDog/dd-trace-go/blob/cea9c1da7d13b20d538a75ea5e047112d34864f6/ddtrace/tracer/tracer.go#L352-L355
if distributed tracing is enabled?

**Comment by JackWink** [comment]
Might not have been clear in my explanation, we have code that will propagate the value from child spans over HTTP boundaries, but in addition to that, we have code that will set all of our Golang root spans to AUTO_KEEP. 

I'm wondering if that's the correct behavior, or if we should set our golang root spans to `AUTO_KEEP` or `AUTO_REJECT` based on whether or not that span has been sampled.

**Comment by gbbr** [comment]
Usually, the right value to use with distributed tracing is "user keep". You can read more about sampling priorities [here](https://docs.datadoghq.com/tracing/advanced_usage/?tab=go#priority-sampling). I wouldn't advise ever manually setting the "auto keep" value unless there is a valid reason to do so. That value is reserved for built-in samplers.

That being said, I'd be wary about setting the "user keep" value too, as this will guarantee that all traces get sampled and will affect your account's quotas. The best way to do this is to set the priority only on distributed parts of a trace. Let's say a trace starts and then propagates itself over HTTP to another service: in this case, you'd have to set the priority on the distributed part only. If you are using an integration (which I assume you are), you'd have to extract the root span that the integration created from context and set the priority, like this:
```go
span, ok := tracer.SpanFromContext(req.Context())
if ok {
    span.SetTag(ext.SamplingPriority, ext.PriorityUserKeep)
}
```
If distributed traces show up correctly, you've done it right. This will allow the system to still have functioning sampling but also ensure all parts get sampled. This priority will automatically be copied over to all child spans and will also automatically be propagated cross-process if you are using the internal propagator.

I hope this makes sense. We are working on simplifying and automating this behavior as we are aware ourself it's slightly tedious now.

Please feel free to ask more questions if I've been in any way unclear or have confused things.

**Comment by knusbaum** [comment]
I'm going to close this issue now, since it's old and the question appears answered. Please reopen if needed.
