### ISSUE TITLE
contrib/sql: allow setting per connection connection service names

### ISSUE THREAD

**Issue by lattwood** [DataDog/dd-trace-go#325]
We have a service that talks to multiple databases, and are currently instrumenting queries for *each* database under a different service name, using this: https://github.com/DataDog/dd-trace-go/blob/fbe92b2acbb3a20d43f5304ea11021a15abd1a8e/tracer/contrib/sqltraced/sqltraced.go#L18-L25

We want to run a current version of `dd-trace-go`, but until we have some solution for this we're unable to upgrade. :(

**Comment by lattwood** [comment]
I might be able to find the time to handle this but would appreciate some guidance on design

**Comment by gbbr** [comment]
@lattwood I'm not completely sure what you are trying to accomplish, the current `database/sql` integration allows you to do the exact same thing by running:
```go
sqltrace.Register("pq", pq.Driver{})
db, err := sqltrace.Open("pq", "postgres://pqgotest:password@localhost...", sqltrace.WithServiceName("my-service"))
```
Maybe we should've made it a bit clearer in the documentation that the [`RegisterOption`s](https://godoc.org/gopkg.in/DataDog/dd-trace-go.v1/contrib/database/sql#RegisterOption) exist.

Does this solve your problem?

**Comment by gbbr** [comment]
@lattwood do you reckon we can close this?

**Comment by lattwood** [comment]
@gbbr looks like your example got it backwards.

https://github.com/DataDog/dd-trace-go/blob/v1/contrib/database/sql/sql.go#L51-L60

```
sqltrace.Register("pq", pq.Driver{})
db, err := sqltrace.Open("pq", "postgres://pqgotest:password@localhost...", sqltrace.WithServiceName("my-service"))
```

Should have been

```
sqltrace.Register("pq", pq.Driver{}, sqltrace.WithServiceName("my-service"))
db, err := sqltrace.Open("pq", "postgres://pqgotest:password@localhost...")
```

which means if we have multiple databases they all end up with the same service name.

**Comment by gbbr** [comment]
You're right, it does make more sense to define a service on a per-connection basis, rather than per-driver basis. It would definitely make sense to allow this.

P.S. I assume what you meant was the reverse of what you wrote.

**Comment by gbbr** [comment]
@lattwood I think we can close this given #466, right? Can you please confirm?

**Comment by gbbr** [comment]
Closing but happy to re-open if you want to continue the discussion.
