### ISSUE TITLE
ddtrace/tracer: data race in payload.go

### ISSUE THREAD

**Issue by YoshikiShibata** [DataDog/dd-trace-go#330]
`reset` and `Read` might cause a data race:
https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/tracer/payload.go#L75
https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/tracer/payload.go#L108

(In the following log, I deleted some information which identifies the project I'm working for)

```
WARNING: DATA RACE
Write at 0x00c0004cc338 by goroutine 16:
  .../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*tracer).flushTraces()
      .../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/payload.go:76 +0x275
  .../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*tracer).flush()
      .../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/tracer.go:315 +0x38
  ../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*tracer).worker()
      .../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/tracer.go:150 +0x3e5

Previous read at 0x00c0004cc338 by goroutine 35:
  .../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*payload).Read()
      .../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/payload.go:109 +0x75
  io/ioutil.(*nopCloser).Read()
      <autogenerated>:1 +0x87
  net/http.transferBodyReader.Read()
      /Users/yoshiki.shibata/tools/go/src/net/http/transfer.go:62 +0x77
  io.copyBuffer()
      /Users/yoshiki.shibata/tools/go/src/io/io.go:402 +0x149
  io.Copy()
      /Users/yoshiki.shibata/tools/go/src/io/io.go:364 +0x74
  net/http.(*transferWriter).writeBody()
      /Users/yoshiki.shibata/tools/go/src/net/http/transfer.go:355 +0x6fa
  net/http.(*Request).write()
      /Users/yoshiki.shibata/tools/go/src/net/http/request.go:645 +0x762
  net/http.(*persistConn).writeLoop()
      /Users/yoshiki.shibata/tools/go/src/net/http/transport.go:1934 +0x321

Goroutine 16 (running) created at:
  .../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.newTracer()
      .../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/tracer.go:132 +0x530
  .../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.Start()
      .../vendor/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/tracer.go:67 +0x7b
  ...run()
     .../main.go:89 +0x572
  ....main()
     .../main.go:48 +0x120

Goroutine 35 (finished) created at:
  net/http.(*Transport).dialConn()
      /Users/yoshiki.shibata/tools/go/src/net/http/transport.go:1339 +0xb4d
  net/http.(*Transport).getConn.func4()
      /Users/yoshiki.shibata/tools/go/src/net/http/transport.go:999 +0xca
```

**Comment by gbbr** [comment]
Thanks for reporting this. This is quite odd. We've never encountered this race condition on our side and we've been running this in production for quite some time now. I suspect there could be something happening in your instrumentation code.

Would you be able to share some code or any information that would help me reproduce this?

**Comment by YoshikiShibata** [comment]
I'm not using the official version of Go. Go 1.11 doesn't produce this problem, but somehow, the latest tip version of Go can easily produce this problem. (Every morning I build the latest tip version.)
I guess some implementations of the tip version of `http` might have changed. In that sense, this might be a problem now, but it would be with Go 1.12. I will try to write a sample code to reproduce this problem.

**Comment by gbbr** [comment]
I see, thanks! That would be super helpful.

**Comment by YoshikiShibata** [comment]
It turned out that this problem occurs when a DataDog server accept the POST request but doesn't read the request's body (traces). For our local e2e test, I just implemented a fake version of the DataDog server: the fake version didn't read the request's body. 

After fixing the fake version of DataDog server by reading the body, the problem disappeared. 

Probably without reading the body, data over a TCP connection will not be flushed and then the sender which is blocked by writing data somehow causes the problem. 

So please close this issue.

**Comment by gbbr** [comment]
Oh! That makes sense. Thanks a lot @YoshikiShibata for helping us clarify this.
