### ISSUE TITLE
contrib/google.golang.org/grpc: Send gRPC status code

### ISSUE THREAD

**Issue by ewang** [DataDog/dd-trace-go#332]
It looks like the current gRPC StreamServerInterceptor and UnaryServerInterceptor aren't currently including the grpc.code tag.

We would like to be able to filter by grpc.code in the APM trace search view.

**Comment by gbbr** [comment]
You're right, we should add this. Thanks. 

P.S. If this is pressing, you are welcome to make contributions. Otherwise, we'll get to it soon!
