### ISSUE TITLE
Child span starts after parent span in goroutine call

### ISSUE THREAD

**Issue by willyyang** [DataDog/dd-trace-go#341]
Why does the parent span not contain the child span within its execution time if there is a goroutine call to `childFc` ? If the `childFc` call isn't called as a goroutine, then I see on DD that the parent span contains the child span (as expected)

```
package main

import (
	"fmt"
	"os"
	"time"

	opentracing "github.com/opentracing/opentracing-go"
	"github.com/.../db"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/opentracer"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
)

func childFc(sp opentracing.Span) {
	childSpan := opentracing.GlobalTracer().StartSpan("child span", opentracing.ChildOf(sp.Context()))
	time.Sleep(2 * time.Second)
	childSpan.Finish()
}

func main() {
	fmt.Println("Hello, 世界!!")
	name, _ := os.Hostname()
	fmt.Println(name)
	t := opentracer.New(
		tracer.WithAgentAddr("127.0.0.1:8126"),
		tracer.WithServiceName("goroutinetest"),
		tracer.WithGlobalTag("env", name),
	)
	opentracing.SetGlobalTracer(t)
	defer tracer.Stop()

	parentSpan := opentracing.StartSpan("the parent")

	time.Sleep(2 * time.Second)
	go childFc(parentSpan)
	parentSpan.Finish()
	db.Init()

}
```
db.Init() initializes the mongo client.

<img width="582" alt="screen shot 2018-10-10 at 9 29 31 pm" src="https://user-images.githubusercontent.com/6396257/46775082-a13b8b80-ccd3-11e8-8da7-8e10cd8359b9.png">

**Comment by gbbr** [comment]
Hi Will!

It's because `parentSpan.Finish()` is most of the time called before or around the same time as the `StartSpan` call inside the goroutine. It depends on Go's scheduler when that goroutine is started. It's an asynchronous operation. What you are seeing is correct.
