### ISSUE TITLE
Status error in Goroutine

### ISSUE THREAD

**Issue by willyyang** [DataDog/dd-trace-go#344]
So It seems that if a parent span completes without error and a child span ( which is running on another thread via Goroutines) throws an error, the status of the overall trace is still OK?

Has anyone experienced / know how to fix this?

**Comment by gbbr** [comment]
This isn't an assumption we can make by default, because it might not be the correct assumption to take in most situations. Can you give a more specific example of what you are doing? Maybe we can find a workaround or a solution together?

**Comment by willyyang** [comment]
Actually, even without goroutines it seems like the overall trace's status is `OK` while only the parent span completes without error and a child span logs an error.

```go
import (
 opentracing "github.com/opentracing/opentracing-go"
 golog "github.com/opentracing/opentracing-go/log"
"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/opentracer"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
)

func childfunc(parentSpan opentracing.Span) error {
	sp := opentracing.StartSpan("child_span", opentracing.ChildOf(parentSpan.Context()))
	time.Sleep(2 * time.Second)
	sp.SetTag("errors", "this is a new error")
	sp.LogFields(
		golog.Error(fmt.Errorf("this is an error!")),
	)
	defer sp.Finish()
	return nil
}

func parentfunc() opentracing.Span {
	span := opentracing.StartSpan("parent_span")
	time.Sleep(2 * time.Second)
	return span
}
func start() {
	t := opentracer.New(
		tracer.WithAgentAddr("127.0.0.1:8126"),
		tracer.WithServiceName("goroutine_test"),
		tracer.WithGlobalTag("env", "none"),
	)
	
	opentracing.SetGlobalTracer(t)
	span := parentfunc()

	childfunc(span)

	span.Finish()
	defer tracer.Stop()

	startMicroServices()
}
```
![screen shot 2018-10-23 at 12 51 58 pm](https://user-images.githubusercontent.com/6396257/47377465-57837580-d6c3-11e8-8e7d-1c8cc3ddf090.png)
![screen shot 2018-10-23 at 12 52 06 pm](https://user-images.githubusercontent.com/6396257/47377473-5d795680-d6c3-11e8-86e6-12e3fdfb7cf2.png)
![screen shot 2018-10-23 at 12 52 14 pm](https://user-images.githubusercontent.com/6396257/47377476-610cdd80-d6c3-11e8-830f-c7e22b0da19b.png)

**Comment by willyyang** [comment]
This seems odd to me.. I'm looking to use the `Trace Search & Analytics` feature to filter traces with a status of ERROR but it doesn't like I'm able to if a trace is deemed as an ERROR only if the parent span has an error?

Is there any way to propagate the child span error so the overall status of the trace is an `Error` so I'm able to filter the traces?

Maybe there's some code you can share with me to explain what I can do for this situation, thanks.

**Comment by gbbr** [comment]
A trace is considered an error only if the main operation (root span) results in an error. If a child operation results in an error and the main one doesn't, it simply means that the main operation handled the error successfully. If you want the entire trace to be considered as an error, you should fail in the main operation.

In your code, you would return the error you've applied to the span from `childfunc` and apply it to the root span as well. Then you should see the trace as an error. I'm closing this, since there is no issue here, but you are welcome to leave further replies and I am happy to help out.
