### ISSUE TITLE
httputil.TraceAndServe doesn't follow the attribute naming conventions

### ISSUE THREAD

**Issue by phette** [DataDog/dd-trace-go#347]
https://github.com/DataDog/dd-trace-go/blob/v1/contrib/internal/httputil/trace.go#L22

The above adds the path of the request at the `http.url` where as the naming convention recommends sticking it at `http.url_details.path`.

https://docs.datadoghq.com/logs/processing/attributes_naming_convention/#url-details-attributes

Should it stick the full URL with the existing key or should it be broken up into the `http.url_details`?

**Comment by gbbr** [comment]
What we have now is correct. The article you've linked to talks about structured logging attributes, which is separate from tracing. Maybe that's what the source of confusion was?

**Comment by phette** [comment]
That definitely was a source of confusion so thanks for that.  Still seems to me like that key implies the full URL and not just the path.  Thanks!
