### ISSUE TITLE
proposal: add span.FinishWithErr

### ISSUE THREAD

**Issue by gbbr** [DataDog/dd-trace-go#352]
Feedback came in from @clutchski suggesting adding a new method to the span's interface which will reduce the need to write:
```go
span.Finish(tracer.WithError(err))
```
and simplify it to:
```go
span.FinishWithErr(err)
```
Feel free to upvote or downvote. We can consider implementing it if there seems to be real need for this.

**Comment by gbbr** [comment]
I am voting against it:
* We already have many "shortcut methods" on our alpha tracer which caused a lot of confusion. Better have only one way to do things.
* When boilerplate gets tedious (e.g. duplication occurs in the code) it's always easy to write your own helper method, for example: `finishErr(span, err)` which does the same.
* Seems odd to add something to the span's interface which only does one simple thing.

I'd suggest that if this is indeed cumbersome and disturbing, we consider doing the finishing differently in a potential 2.0 version of the tracer.

**Comment by knusbaum** [comment]
I think we can consider this proposal rejected. We can reopen if we want to revisit it.
