### ISSUE TITLE
contrib/google.golang.org/grpc: proposal: add a way to disable debug stacks on errors

### ISSUE THREAD

**Issue by niamster** [DataDog/dd-trace-go#354]
Traceback generation in Go is quite costly operation and as errors such as `BE` is throttled might occur very often the the application end up just burning CPU on generating the backtraces.
On top of that the gRPC backtraces are super long which put pressure on `GC` and also they are completely useless as they all end up in gRPC's stack not pointing to a caller

**Comment by gbbr** [comment]
I would be ok with adding a new option to the grpc package, let’s call it `NoDebugStack` which would simply do the below when it is set:

```go
span.SetTag(ext.Error, true)
span.SetTag(ext.ErrorMsg, err.Error())
```

This will then set the error but not the stack. Additionally you could set the error type too.

**Comment by niamster** [comment]
@gbbr that would work (although it breaks nice `WithError` interface). 
Please fix `gRPC` error handling because in normal use case error handling shall affect normal application behaviour

**Comment by gbbr** [comment]
I think making `WithError` a bit more customizable is definitely something to consider for a 2.0 version of the tracer. I don't think we should always have a stack by default. It would be nice to have an option such as in your initial PR. My only concern with your PR is that this doesn't offer a way to disable the stack when doing:
```go
span.SetTag(ext.Error, err)
```

**Comment by niamster** [comment]
I believe that `span.SetTag(ext.Error, err)` is a special case and shall be discouraged to use in the same way as
 ```
span.SetTag(ext.Error, true)
span.SetTag(ext.ErrorMsg, err.Error())
```
exposes too much information about the internals.

**Comment by gbbr** [comment]
I agree. This was mostly a design decision to support our old functionality along with OpenTracing as well. One way would be also to have a dedicated method for setting an error.

**Comment by gbbr** [comment]
I think we could compromise and have a solution that combines both our PRs, let's:
* Use your PR but replace the word "backtrace" with "DebugStack" everywhere (that's the correct term in Go)
* Add an option to the gRPC interceptor which enables this functionality. We can't enable it by default because it will break backwards compatibility. We can call it `NoDebugStack` like in my PR.

How's that sound?
