### ISSUE TITLE
proposal: add processing pipeline

### ISSUE THREAD

**Issue by vadimi** [DataDog/dd-trace-go#360]
Hello,

I'm using grpc tracer and I would like error traces to have higher sampling priority (`PriorityUserKeep`). Is there a way to control it?

**Comment by gbbr** [comment]
Unfortunately not at this point. There have been discussions about potentially introducing a pre-flush drop-in callback filter but nothing has materialized yet. Do you have the sense that you are missing errors?

**Comment by vadimi** [comment]
Yeah, we definitely are missing some of the errors based on the agent sampling. The callback would certainly work for me.

**Comment by gbbr** [comment]
I understand. We do have a plan for this in our backlog (we call it the "processing pipeline") but we've not yet scheduled work for it. There are some concerns around performance but I think it will eventually be introduced as it is already available in our tracers for other languages. It might take a while though.

If this is very important to you now, I can suggest as a work around to try to create a span which wraps the call (having sampling priority set as you wish) and pass that within the context to the call itself. The integration should pick it up and make the span it creates a child. That should work. It will introduce an extra span into your trace but will have the desired effect. Would this be a good solution to you?

**Comment by vadimi** [comment]
Thanks, it will work for me for this app. Looking forward to more permanent solution to just have it one place.

**Comment by knusbaum** [comment]
Closing this ancient issue. There has been more recent work towards a processing pipeline, but it is not certain yet.

There are also new features in the agent for better error sampling. If this is still a problem, please reopen this issue.
