### ISSUE TITLE
Ensure correct traceID is Injected to carrier

### ISSUE THREAD

**Issue by willyyang** [DataDog/dd-trace-go#361]
Hi, I'm hoping to understand whether the following code will inject the `X-Datadog-Trace-Id` of a span correctly in the `carrier`...

```
carrier := opentracing.HTTPHeadersCarrier(http.Header{})
tracer.Inject(spanContext, carrier)
```
Can I be sure that the `traceID` of `spanContext` is the same as the one in carrier's `X-Datadog-Trace-Id` field?

If two spans show up on DD with parent/child relationships.. can we assume that their traceIDs are the same and the `X-Datadog-Parent-Id` of the child span is the SpanID of the parent span?

Thanks in advance.

**Comment by gbbr** [comment]
Hi Will!

What are you trying to accomplish? We have unit tests for this and we (along with our customers) have been using distributed tracing for quite some time now without issues.

I'm not sure I understand the question. Yes, inject and extract should correctly attach and extract a context from a carrier.

**Comment by willyyang** [comment]
Yes, I am having issues seeing the traceID in the Trace Search feature.. So I'm trying to pinpoint where the problem may be. 

I have multiple services and I am seeing if the traceID is being dropped somewhere (which would cause me to not be able to filter my services via traceIDs)

**Comment by gbbr** [comment]
I think in this case it's best to reach out to our support team, as this doesn't seem to be strictly related to this repository. I'm sure they'll be able to help a lot better than I. After you've done so and are happy with the result, feel free to close this issue.

If there are any technical issues however strictly related to this repository, I'm more than happy to help.

**Comment by knusbaum** [comment]
I'm going to close this issue. If there's anything else we can help with, feel free to reopen.
