### ISSUE TITLE
Span Tags naming conventions are inconsistent in docs and sources

### ISSUE THREAD

**Issue by marty-stranger** [DataDog/dd-trace-go#364]
From https://docs.datadoghq.com/logs/processing/attributes_naming_convention/#source-code
error.kind, error.message, error.stack

From https://github.com/DataDog/dd-trace-go/blob/v1.6.0/ddtrace/ext/tags.go#L46-L53
error.type, error.msg, error.stack

**Comment by gbbr** [comment]
Hey! Thanks for the remark, if you look more closely, those naming conventions are for logs, not for APM.
