### ISSUE TITLE
Unable to send spans to datadog agent with latest version over rabbitMQ pub/sub

### ISSUE THREAD

**Issue by willyyang** [DataDog/dd-trace-go#377]
Unable to use the latest version `1.7.0` to send spans created using `childOf` method from a spanContext created using the `Extract` method to datadog agent. I'm using pub/sub rabbitMQ communication 

`1.4.0` seems to work fine.

**Comment by gbbr** [comment]
#373 should address this, included a regression test.

**Comment by nicolas-martin** [comment]
Can confirmed `1.8.0` fixed the bug, thank you!

**Comment by gbbr** [comment]
Glad to hear that. Closing in that case! @willyyang please re-open if it doesn't for you.

**Comment by willyyang** [comment]
works for me as well thanks !
