### ISSUE TITLE
contrib/olivere/elastic: Option to disable elasticsearch.body tag 

### ISSUE THREAD

**Issue by Mathiou04** [DataDog/dd-trace-go#382]
Hello,
currently when tracing elasticsearch http.Client, we automatically get the json payload of the request in the trace.
Sometimes this payload can contain sensitive or personal data which might be an issue due to the GDP Regulation. Could we add an option to the client to disable this?
I am willing to open a PR if needed (as it is probably a simple one).

**Comment by gbbr** [comment]
I think what you're looking for is ElasticSeach obfuscation in the agent. See it [here](https://github.com/DataDog/datadog-trace-agent/blob/master/datadog.example.yaml#L109-L117) in our example config.

Please close the issue if this solves your problem.

**Comment by Mathiou04** [comment]
Thanks, exactly what I was looking for.

**Comment by gbbr** [comment]
Glad it helped!
