### ISSUE TITLE
Question: Does this support the Open tracing standard.

### ISSUE THREAD

**Issue by nicksrandall** [DataDog/dd-trace-go#39]
Our service uses this standard... http://opentracing.io/. Is dd-trace-go compatible with this standard?

**Comment by gchaincl** [comment]
@nicksrandall I'm working on an implementation https://github.com/gchaincl/dd-go-opentracing
Even though is not completed yet, (Baggage Items are not implemented) it's works pretty good so far.

**Comment by palazzem** [comment]
@nicksrandall since we're moving to OpenTracing for sure in the next few weeks, I'm going to close this issue. Thanks and sorry if it took so long to have an official answer about OpenTracing support!
