### ISSUE TITLE
contrib/google.golang.org/grpc: proposal: add tracing handler which implements stats.Handler interface

### ISSUE THREAD

**Issue by zoncoen** [DataDog/dd-trace-go#398]
`google.golang.org/grpc` package provides the mechanism to collect and report various network and RPC stats.
We can trace requests more correctly by using the mechanism instead of gRPC interceptor.

ref. https://godoc.org/google.golang.org/grpc/stats

**Comment by zoncoen** [comment]
I think it should be like this. https://github.com/zoncoen/dd-trace-go/commit/90aa1ec7eb07c77b9e52c3424a1f22c941233269

**Comment by gbbr** [comment]
I definitely like this a lot. I'd be happy to consider adding this into our `grpc` integration if you're interested in contributing it. Some questions arise:

* Documentation says it's experimental. I wonder how often they might break the API?
* Have you actually tried this out with Datadog? Are you, or have you been using it?
* Is there any additional information we can get by using this `stats` package which we weren't from using interceptors? Or, are we losing any information here?
* What's the advantage of using this over interceptors?

Thanks!

**Comment by zoncoen** [comment]
Thank you for your reply!

> Documentation says it's experimental. I wonder how often they might break the API?

I'm not sure, but I think it is not a very unstable API.
Actually, OpenCensus uses the package for request tracing. https://github.com/census-instrumentation/opencensus-go/blob/57c09932883846047fd542903575671cb6b75070/plugin/ocgrpc/server.go#L24-L54

> Have you actually tried this out with Datadog? Are you, or have you been using it?

No, I haven't yet. I will try it lator.

> Is there any additional information we can get by using this `stats` package which we weren't from using interceptors? Or, are we losing any information here?
> What's the advantage of using this over interceptors?

The information that stats handler can collect is almost the same as interceptors.

**Comment by gbbr** [comment]
> No, I haven't yet. I will try it later.

Great! Please let me know if it works.

> The information that stats handler can collect is almost the same as interceptors.

That's what I'm noticing as well. One thing missing on your branch is getting the peer information as we currently do [here](https://github.com/DataDog/dd-trace-go/blob/v1/contrib/google.golang.org/grpc/client.go#L26-L28). But I'm sure that can be added.

I'd be happy to work together on getting this merged when you're ready for a PR.

**Comment by zoncoen** [comment]
> One thing missing on your branch is getting the peer information as we currently do here.

I got it! I will fix it and send a PR.

**Comment by zoncoen** [comment]
Set the peer information at [here](https://github.com/zoncoen/dd-trace-go/blob/90aa1ec7eb07c77b9e52c3424a1f22c941233269/contrib/google.golang.org/grpc/client_stats_handler.go#L40-L46).
