### ISSUE TITLE
proposal: add support for go-chi/chi

### ISSUE THREAD

**Issue by davidjumani** [DataDog/dd-trace-go#404]
Modifying the existing gorilla/mux to allow for go-chi/chi too!
https://github.com/davidjumani/dd-trace-go/commit/a6a211ab73a61efe2e7700d52197da7c31975d18

**Comment by gbbr** [comment]
> Modifying the existing gorilla/mux to allow for go-chi/chi too!

Thanks David! It's fine to add support for `go-chi/chi`, but I don't see the connection with `gorilla/mux`?

**Comment by davidjumani** [comment]
Hi Gabriel, I've ported the `gorilla/mux` wrapper to support `go-chi/chi`. You can review the commit and let me know if there are any issues and to raise the PR.

**Comment by gbbr** [comment]
I'd be happy to review after you open a PR.

**Comment by davidjumani** [comment]
Raised (https://github.com/DataDog/dd-trace-go/pull/405)

**Comment by davidjumani** [comment]
Just realized that some error handling was missing. Could you please add at https://github.com/DataDog/dd-trace-go/blob/v1/contrib/go-chi/chi/chi.go#L45

```
resourceName := chi.RouteContext(r.Context()).RoutePattern()
if resourceName == "" {
	resourceName = "unknown"
}
resourceName = r.Method + resourceName
span.SetTag(ext.ResourceName, resourceName)
```

Added the method along with the resource name as seen in https://github.com/DataDog/dd-trace-go/blob/v1.8.0/contrib/gorilla/mux/mux.go#L101

**Comment by gbbr** [comment]
Ah, damn, I missed that one.

**Comment by davidjumani** [comment]
Thanks!

**Comment by gbbr** [comment]
Let me know if you find more issues. Also feel free to open subsequent PRs if you wish...
