### ISSUE TITLE
question: how to configure distributed tracing beetween grpc and downside python service?

### ISSUE THREAD

**Issue by pendolf** [DataDog/dd-trace-go#408]
My setup:
grpc-server->httpapi_client -> python_api

in python api, distributed-tracing is enabled.

main.go
```go
tracer.Start(
	tracer.WithAgentAddr("datadog-agent:8126"),
	tracer.WithDebugMode(true),
	tracer.WithGlobalTag("env", os.Getenv("ENVIRONMENT")),
)
defer tracer.Stop()
...
// HTTP API Client init.
apiClient := busgoapi.NewAPIClient(*apiURL)
...
grpcServer := grpc.NewServer(
grpc_middleware.WithUnaryServerChain(grpctrace.UnaryServerInterceptor(grpctrace.WithServiceName("driver-api"))),
grpc_middleware.WithStreamServerChain(grpctrace.StreamServerInterceptor(grpctrace.WithServiceName("driver-api"))),
)

apiServer := driver.NewAPIServer(apiClient, redisClient)
```

client.go
```go
// NewAPIClient returns API Client.
func NewAPIClient(url string) *Client {
	HTTPClient := &http.Client{}
	if enableTracing {
		HTTPClient = ddhttptrace.WrapClient(&http.Client{})
	}
	return &Client{BasePath: url, HTTPClient: HTTPClient}
}
```

**Comment by gbbr** [comment]
The way you instantiate the `http.Client` looks fine to me. What are you seeing in Datadog?

**Comment by pendolf** [comment]
@gbbr 
For example:
This is apm page for grpc service
![image](https://user-images.githubusercontent.com/598479/54256024-9d62ac80-4584-11e9-8381-c59f208a0f66.png)

This is apm page for python service
![image](https://user-images.githubusercontent.com/598479/54256045-b8cdb780-4584-11e9-97e8-e95da53bfbeb.png)

I don't see any relations between golang and python services at Flame graph.

Also for golang http client requests at the apm services page I see separated services called "server" with only one Resource called "http.request". I expected to see what http requests will be attached to grpc call transaction in driver-api service

**Comment by gbbr** [comment]
@pendolf thanks for sharing that. It's very likely that you might be missing something in your code. I don't think there is a bug here in the repository. You'll get a faster turnaround if you reach out through support. They can get more information from you and your organization and can share that internally.

If we do find a bug in the repository, we'll report it here in this issue. You can mention my name to support and I can help more via that channel.
