### ISSUE TITLE
contrib/gorilla/context: incompatible with context.Context

### ISSUE THREAD

**Issue by lwc** [DataDog/dd-trace-go#41]
Gorilla's context is a map keyed off request references, meaning that it breaks rather catastrophically when mixing with the more recent `request.Context()` stdlib approach.

Taken from the gorilla docs:

> Note: gorilla/context, having been born well before context.Context existed, does not play well with the shallow copying of the request that http.Request.WithContext (added to net/http Go 1.7 onwards) performs. You should either use just gorilla/context, or moving forward, the new http.Request.Context().

In light of this, it's probably best to consider Gorilla deprecated in favour of the standard library context and routers that make use of it. 

If you want to keep a gorilla implementation around, `muxtrace.SetRequestSpan` and `muxtrace.GetRequestSpan` should be updated to use Gorilla's context.

**Comment by gbbr** [comment]
@lwc thanks for reporting this, and apologies for the super late reply. As far as I can notice, we are not really using `gorilla.Context` directly anywhere, and by looking at the code that is currently in `gorilla/mux`, such as [this file](https://github.com/gorilla/mux/blob/c0091a029979286890368b4c7b301261e448e242/context_native.go#L1) I can see that it has a conditional for builds with Go 1.7+ where it uses the standard library context.

Given the above and the age of this issue I think it'll be safe to assume that this is no longer an issue. I am closing. If you are still having this problem please feel free to re-open and I'll be happy to address it with a faster turnaround.
