### ISSUE TITLE
contrib/sqltraced: Contexted queries not generating traces

### ISSUE THREAD

**Issue by andysnowden** [DataDog/dd-trace-go#413]
When attempting to follow the example code for https://godoc.org/gopkg.in/DataDog/dd-trace-go.v1/contrib/database/sql#ex-package--Context I am unable to generate any traces that use sql.{command}Context() such as db.QueryRowContext and db.ExecContext

However commands without a context are properly generating traces such as db.Query and db.Exec.

Common connection code:
```golang
dsn := fmt.Sprintf("host=%v port=%v user=%v dbname=%v password=%v sslmode=%v", dbHost, dbPort, dbUser, dbName, dbPass, dbSSL)
sqltrace.Register("pgtrace", &pq.Driver{}, sqltrace.WithServiceName("my-db"))
db, err := sqltrace.Open("pgtrace", dsn)
```

Working traces:
```golang
sqlStatement := `select 1`

_, err = db.Exec(sqlStatement)
if err != nil {
	log.Errorf("sql error: %v", err)
}
```

Not working:
```golang

_, ctx := tracer.StartSpanFromContext(context.Background(), "my-query",
	tracer.SpanType(ext.SpanTypeSQL),
	tracer.ServiceName("my-db"),
	tracer.ResourceName("initial-access"),
)

sqlStatement := `select 1`

_, err = db.ExecContext(ctx, sqlStatement)
if err != nil {
	log.Errorf("sql error: %v", err)
}
```

If I enable trace debugging I don't see any errors
`
2019/03/21 19:30:16 Sending payload: size: 912 traces: 3
`

**Comment by gbbr** [comment]
Are there any errors on the trace-agent logs when you run this?

**Comment by andysnowden** [comment]
@gbbr No errors in the trace log, just the normal messages about size/traces/etc.

When I enable the tracer WithDebug I also don't see any errors on the send side.  For debugging purposes I ran once with just db.Exec and it says "sending 3 traces".  If I also uncomment the code using db.ExecContext I still only see "sending 3 traces".  However if I comment out db.Exec it goes down to "2 traces".

**Comment by cgilmour** [comment]
Hi @andysnowden, the example is inaccurate. The span object returned by `StartSpanFromContext` should not be discarded, and its `Finish()` method should be called.

An update for your example is below.
```
span, ctx := tracer.StartSpanFromContext(context.Background(), "my-query",
	tracer.SpanType(ext.SpanTypeSQL),
	tracer.ServiceName("my-db"),
	tracer.ResourceName("initial-access"),
)

sqlStatement := `select 1`

_, err = db.ExecContext(ctx, sqlStatement)
if err != nil {
	log.Errorf("sql error: %v", err)
}
span.Finish(tracer.WithError(err))
```

I'll open a PR to update the example in the codebase.

**Comment by andysnowden** [comment]
Thanks @cgilmour using your modified example I was able to get traces to appear with postgres information.
