### ISSUE TITLE
Having trouble wrapping the library

### ISSUE THREAD

**Issue by srizzling** [DataDog/dd-trace-go#419]
I'm having trouble wrapping this library in a separate library.

Mainly my reason for creating a wrapped library is because I want to be able to source configuration of the agent via environment variables (similar to how to configure the tracing agents for java) and I created middleware for the `go-swagger` library.

I have my example illustrated here: https://github.com/srizzling/dd-swagger-tracer. 

So what I'm seeing is that all the instrumentation added is no-oped and the tracer is never started. Checkout the `example/simple` folder, and run `make run`

I have a feeling its to do with the mutex that is holding the global singleton. But I don't wanna implement that logic myself. Do you have any ideas?

**Comment by srizzling** [comment]
![image](https://user-images.githubusercontent.com/2313668/54975391-09183100-4feb-11e9-8ff9-c19953b5b8cb.png)

Here is showing the no-op'd span.

**Comment by gbbr** [comment]
I'm sorry but I won't be able to check out that code, build it and examine it. If you could pin-point a specific problem with this repository by posting a snippet of code here that helps reproduce it, I'd be more than happy to help. If you just want to read configuration from environment to start the tracer, nothing is stopping you from doing that.

Lastly, in your screenshot, I don't see a call to `tracer.Start`. That's possibly the problem

**Comment by srizzling** [comment]
I ended up figure out the issue..

I did this:

```
tracer.Start()
defer tracer.Stop()
```

But obviously the scope of the defer was limited to my function, while I need it to run for the whole server process. Doh!

**Comment by gbbr** [comment]
Glad you figured it out 😄
