### ISSUE TITLE
contrib/garyburd/redigo: the repo has been archived

### ISSUE THREAD

**Issue by Hendra-Huang** [DataDog/dd-trace-go#421]
Future development of Redigo is at github.com/gomodule/redigo. Please submit issues at gomodule/redigo. The repository at github.com/garyburd/redigo is a read-only snapshot.

I use `gomodule/redigo` currently and I would like to have datadog tracing enabled for it. If I import `contrib/garyburd/redigo`, it will introduce a new dependency to `garyburd/redigo`. It would be nice if we can copy `contrib/garyburd/redigo` to `contrib/gomodule/redigo` and replace `garyburd/redigo` with `gomodule/redigo` so my app doesn't need any dependency to `garyburd/redigo`

**Comment by gbbr** [comment]
I think that's a good idea. Would you be interested in submitting a PR?

**Comment by Hendra-Huang** [comment]
yes sure.. will send a PR to fix this issue
