### ISSUE TITLE
proposal: simplify the API for starting a child span

### ISSUE THREAD

**Issue by gbbr** [DataDog/dd-trace-go#427]
Currently to start a new span as a child of a current span (let's say `root`):
```go
child := tracer.StartSpan("op", tracer.ChildOf(root.Context()), tracer.Tag("key", 1))
```
The suggestion is to instead have:
```go
child := root.StartChild("op", tracer.Tag("key", 1))
```

This could serve for a simpler, more intuitive API.

**Comment by knusbaum** [comment]
👍  I think this would be good to add to v2.0.
