### ISSUE TITLE
question: how to enable b3 trace propagation?

### ISSUE THREAD

**Issue by szabado** [DataDog/dd-trace-go#431]
It seems like the only way is some code like the following:
```
// getB3Propagator returns a tracer.Propagator configured to use B3.
func getB3Propagator() (tracer.Propagator, error) {
	err := setB3Propagation()
	if err != nil {
		return nil, err
	}

	prop := tracer.NewPropagator(nil)
	return prop, unsetB3Propagation()
}

const (
	headerPropagationStyleInject  = "DD_PROPAGATION_STYLE_INJECT"
	headerPropagationStyleExtract = "DD_PROPAGATION_STYLE_EXTRACT"
	headerPropagationStyle = "b3"
)

// setB3Propagation sets the required environment variables to enable b3 propagation.
func setB3Propagation() error {
	err := os.Setenv(headerPropagationStyleExtract, headerPropagationStyle)
	if err != nil {
		return err
	}
	return os.Setenv(headerPropagationStyleInject, headerPropagationStyle)
}

// unsetB3Propagation unsets the environment variables set by setB3Propagation
func unsetB3Propagation() error {
	err := os.Unsetenv(headerPropagationStyleExtract)
	if err != nil {
		return err
	}
	return os.Unsetenv(headerPropagationStyleInject)
}
```

The tests seem to do what I'm doing: https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/tracer/textmap_test.go#L199-L279.

If this is the only way, would it be possible to get this exposed via a configuration option/would you be open to me opening a pr that did that? Setting environment variables doesn't feel like an elegant way to pass configuration options into a library.

**Comment by gbbr** [comment]
@cgilmour can you please take a look?

**Comment by cgilmour** [comment]
Hi @szabado, you're correct that environment variables are not an elegant way to pass configuration, and that it's currently the only way to set the header propagation options.
The intention is to expose this via tracer `StartOption` items in the future, once it has matured and certain decisions made.
Eg: how we will handle IDs with more than 64 bits, and what other propagation styles need to be supported.
Those will affect the final options that get exposed, and the internal behavior.

If you're able to share some additional details about your use case that involves B3 header propagation, that will also help make the correct design decisions.

**Comment by szabado** [comment]
What additional details are you curious about?

**Comment by szabado** [comment]
Also, would it be possible to get some documentation about how to configure b3 propagation [here](https://docs.datadoghq.com/tracing/setup/go/#configuration) and in the Godoc?
