### ISSUE TITLE
proposal: Add option to skip stack frames

### ISSUE THREAD

**Issue by matoous** [DataDog/dd-trace-go#435]
Hello!

Proposal: It would be nice to be able to configure how many frames are in the stack trace and also to skip number of frames, now all of our traces begin with:
```
goroutine 325 [running]:
runtime/debug.Stack(0xdcd9c0, 0xc0004595c0, 0xf0509f)
    /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*span).setTagError(0xc0006b4000, 0xe009e0, 0xc0003558a0, 0x1)
    /go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.12.1/ddtrace/tracer/span.go:133 +0x218
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*span).Finish(0xc0006b4000, 0xc000160208, 0x1, 0x1)
    /go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.12.1/ddtrace/tracer/span.go:189 +0x169\ng
```
which is quite useless and clutters the traces. As an example `zap` logger uses following function to remove its own frames: https://github.com/uber-go/zap/blob/416e66ad83ebde35df0e09f02e65ac149e193b0e/stacktrace.go#L46-L110.
We could implement something similar for the `dd-trace-go`. It would make the traces smaller while keeping the necessary information.

Configuration of the stack trace could be another `FinishOption` with two parameters `WithDebugStackConfig(frames, skip int)` for example.

**Comment by gbbr** [comment]
I think this is a great idea and would be useful! I'd be happy to help review if you're willing to commit to the work. Maybe `WithStackFrames` would be a better name but I don't have strong feelings for it.
