### ISSUE TITLE
bugs: contrib/grpc.v12 module has metadata.FromContext

### ISSUE THREAD

**Issue by TKNGUE** [DataDog/dd-trace-go#444]
Hi, friends.

I am getting errors following: 

```
# gopkg.in/DataDog/dd-trace-go.v1/contrib/google.golang.org/grpc.v12
../../../../.go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.14.0/contrib/google.golang.org/grpc.v12/grpc.go:48:11: undefined: metadata.FromContext
../../../../.go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.14.0/contrib/google.golang.org/grpc.v12/grpc.go:78:13: undefined: metadata.FromContext
../../../../.go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.14.0/contrib/google.golang.org/grpc.v12/grpc.go:83:9: undefined: metadata.NewContext
```

it seems the module to still use older metada functions 
and it can be fixed by changing API properly.

But, READMe.md describes that this modules intend to skip its test 

> The grpc.v12 integration will fail (and this is normal), because it covers for deprecated methods. In the CI environment we vendor this version of the library inside the integration. Under normal circumstances this is not something that we want to do, because users using this integration might be running versions different from the vendored one, creating hard to debug conflicts.

Do you have any concern to resolve this issue?

# related issues

Same problem:
https://github.com/DataDog/dd-trace-go/issues/120

**Comment by gbbr** [comment]
Hi @TKNGUE! I'm not sure I understand the problem. What is it that is failing? Is running the tests failing? If so, that's normal if you aren't using `grpc.v12`. The newer package is the sibling in the same folder: https://github.com/DataDog/dd-trace-go/tree/v1/contrib/google.golang.org/grpc. Simply use that. The package you point to is meant to be used with older grpc versions.

**Comment by TKNGUE** [comment]
Thanks for you help!
As @gbbr said, I solved my problem by just using https://github.com/DataDog/dd-trace-go/tree/v1/contrib/google.golang.org/grpc.

My mistake is due to stupid confusion which grpc.v12 is newer than https://github.com/DataDog/dd-trace-go/tree/v1/contrib/google.golang.org/grpc

**Comment by gbbr** [comment]
Glad it worked out!
