### ISSUE TITLE
contrib/go-redis/redis not compiling on CI

### ISSUE THREAD

**Issue by cgilmour** [DataDog/dd-trace-go#448]
```
# gopkg.in/DataDog/dd-trace-go.v1/contrib/go-redis/redis
contrib/go-redis/redis/redis.go:75:11: tc.Client.WrapProcess undefined (type *redis.Client has no field or method WrapProcess)
```

This is an upstream change on `master`, as they work toward v7.
It's not released, so we shouldn't change the code yet.

We can probably vendor go-redis/redis at the latest working version, but that may cause type conflicts for users of the tracer, and also other contrib packages eg: redigo.
If that occurs, we'll need to start using dep or modules.

Thoughts?

**Comment by gbbr** [comment]
My suggestion is to do the same as we do for grpc, have [two folders](https://github.com/DataDog/dd-trace-go/tree/v1/contrib/google.golang.org): one for v6 and one for v7, once that's out. It will break people's import paths but if they are using pre-v7 they'll still be able to trace their application.

We can use the same technique as we do for gRPC in CI: https://github.com/DataDog/dd-trace-go/blob/v1/.circleci/config.yml#L69-L79
