### ISSUE TITLE
StartSpan/setTagString taking a huge amount of memory

### ISSUE THREAD

**Issue by froodian** [DataDog/dd-trace-go#458]
We're seeing dd-trace-go take the vast majority of application memory in a production context:

![image](https://user-images.githubusercontent.com/1547435/59710005-11d96700-91d6-11e9-829d-2f209884b121.png)

In the place where we call StartSpan, we do call Finish on the result shortly after. Let me know if there's any more information I can provide to help debug this issue, thank you!

**Comment by cgilmour** [comment]
Hi @froodian, thanks for reporting this.

From the profile you've provided, we can seemingly rule out existing integrations (eg: contrib/net/http, since that only accounts for 1.50mb of allocations.
So it's likely in the parts that have been redacted.

Can you share the pieces of code that are related to configuring the tracer, creating spans (`StartSpan`, `StartSpanFromContext`), calling `Finish()` and setting tags and so on?
The names of things aren't terribly important, so they can be replaced with generic values.

Without seeing additional code, the best guess is there's a spot where a span is started, but Finish() never gets called. Eg: returning from a function before calling it, or there's a `defer span.Finish()`, but it's stuck somewhere before returning.

**Comment by froodian** [comment]
Hi @cgilmour, thanks for your response. The code looks something like this:

```
# Where r is an http.Request made through a dd-trace-go.v1/contrib/net/http mux
ctx := r.Context()
rootSpan, _ := tracer.SpanFromContext(apmCtx)
rootSpan.SetTag("log_tag", "A varying string of about this length")
go myFunc(&ctx)

func myFunc(apmCtx *context.Context) {
  childSpan, _ := tracer.StartSpanFromContext(*apmCtx, "doSingleSend")
  defer childSpan.Finish()

  leafSpan := tracer.StartSpan("SendNotification", tracer.ChildOf(childSpan.Context()))
  ... blocking operation that should take strictly <120s ...
  leafSpan.Finish()

  ... code that should not block infinitely... there are channel sends here, which I recognize are a block risk, so I will verify/ensure that they cannot block infinitely, but note that this code was running for months pre-datadog without any sign that it was leaking goroutines, which would be the outcome of blocking on these sends ...

  return
}
```

note that I am not calling Finish on the span that I get from the http request's context with `SpanFromContext`, as my understanding is that it is being closed already when the response is written back to the caller?

**Comment by cgilmour** [comment]
Hi @froodian thanks for providing the code. You're correct that `Finish()` should not be called on the result from `SpanFromContext`.

The code helped to write up a test case for this to see if the same behavior could be reproduced.
So far, not exactly, but similar. where the heap hotspots were from allocations in `StartSpan` / `setTagString`, and also the other part with `runtime.malg`.
I had to lower the `runtime.MemProfileRate` locally to be able to see things in reasonable detail.

Now looking at the original report again, the 100M allocated from `runtime.malg` indicates _a lot_ of goroutines that got launched and were active at the time or had recently completed and not cleared out by the GC. It'd make sense if it were choking during that "blocking operation" or having channel contention in "shouldn't block indefinitely".
The side-effect would also be lots of unfinished spans and they'd show up in a heap profile as the StartSpan / setTagString parts of our code.

If this is happening repeatably, then it'll be worth checking the `block` and `goroutine` profiles in addition to `heap`.

**Comment by cgilmour** [comment]
Another point on this is that the results for rootSpan, childSpan and leafSpan will sometimes not show up correctly in the UI if the child and/or leaf finish a long time after the root span does.

You might get better measurements by creating a new trace in that goroutine (not using `rootSpan` as the parent) and adding tags of all the information you'd want to correlate, eg: original trace ID, and other context from that request.

**Comment by froodian** [comment]
> the 100M allocated from runtime.malg indicates a lot of goroutines that got launched and were active at the time or had recently completed and not cleared out by the GC. It'd make sense if it were choking during that "blocking operation" or having channel contention in "shouldn't block indefinitely".
The side-effect would also be lots of unfinished spans and they'd show up in a heap profile as the StartSpan / setTagString parts of our code.

Yeah, so the key thing the "blocking operation" does is make an http request with `http.Do` (but not read the response body, that comes later).  The http.Client that it uses has a Timeout of 120s set on it which is why I say it *should* take strictly <120... experience in a slightly different codebase tells me that in reality that time limit does not always seem to be respected though, so that is a potential place for goroutine pile-ups.  

The fact that we haven't been able to reliably limit the duration of `http.Do` calls makes your latter note that

> the results for rootSpan, childSpan and leafSpan will sometimes not show up correctly in the UI if the child and/or leaf finish a long time after the root span does.

particularly interesting, as that's precisely what would occur when http.Do takes longer than the allotted time.

In terms of next steps, I made some changes yesterday to the "shouldn't block indefinitely" block to help ensure that there is not channel contention as you say. We haven't seen the memory pile up since then - if we do, I'll take a look at the `block` and `goroutine` profiles as you suggest, thanks for pointing those out, I hadn't realized those sample indexes existed.

**Comment by cgilmour** [comment]
Great!
Another thing to be aware of with `http.Client` are the tunables for `MaxConnsPerHost` and `MaxIdleConnsPerHost`. If the client is shared between goroutines (eg: because it's the default client used by `http.Do`) and the request is hitting the same host address, then the default limits can get exceeded quite quickly and start to block.
I'm not sure if the timeout includes the duration that it's blocked or only when the request is unblocked and in-flight.

**Comment by froodian** [comment]
yeah that's a good call-out, thanks - this service has `MaxIdleConnsPerHost` turned up to 50, but doesn't have `MaxConnsPerHost` set at all (I think this transport was last tweaked pre go-1.11 when that was introduced) - I'm tweaking those up now.

**Comment by kanwals** [comment]
@froodian I saw similar characteristics for memory usage in our prod app as well. Tangential to this discussion, what tool did you use to get that nice looking flow chart?

**Comment by cgilmour** [comment]
@kanwals those can be generated using `pprof` tooling that come with Go.

**Comment by cgilmour** [comment]
@froodian have things improved after some tweaking? If so, can the issue be closed?

**Comment by froodian** [comment]
Indeed - we're still having some trouble with `http.Do` calls sometimes taking longer than the timeout on the http client and piling up (and are continuing to experiment with transport settings to attempt to fully alleviate), but at this point we're purely in the land of golang framework usage (and legitimate networking slowness). I agree the memory usage we were seeing was a result of goroutine pile-up, sparked by this issue and exacerbated by blocking channel sends in our code in that timeout case. Thank you very much for your help.
