### ISSUE TITLE
math/rand needs to be seeded

### ISSUE THREAD

**Issue by jbowes** [DataDog/dd-trace-go#46]
`math/rand` needs to be seeded. If it's not, it will seed with 1 every time.

Because of this, trace and span id generation is deterministic across restarts (and across different applications); this really confuses the DataDog dashboard ;)

There should be some documentation about seeding random before use. Or even better, the tracer should hold its own random source that it ensures is seeded, or use crypto/rand.

**Comment by palazzem** [comment]
That was a big concern, thanks for pointing that quickly! By the way, it has been fixed with https://github.com/DataDog/dd-trace-go/pull/48 so we should be fine now.

Thanks!
