### ISSUE TITLE
contrib/olivere/elastic: Allow customized resource naming through a ClientOption

### ISSUE THREAD

**Issue by cranti** [DataDog/dd-trace-go#460]
The existing [quantize](https://github.com/DataDog/dd-trace-go/blob/v1/contrib/olivere/elastic/elastictrace.go#L90-94) function doesn't play nicely with the index patterns that we're using, resulting in a large list of resources. I'd like to add a `ClientOption` that sets a function that will be used to name spans. The function will have the same signature as `quantize()`, which will be used as the default. I'd be happy to open a PR.

**Comment by gbbr** [comment]
Sounds like a nice idea to me! 👍
