### ISSUE TITLE
proposal: add support for execution tracer

### ISSUE THREAD

**Issue by gbbr** [DataDog/dd-trace-go#468]
The proposal is to automatically [create tasks](https://golang.org/pkg/runtime/trace/#NewTask) using the `runtime/trace` package, when tracing [is enabled](https://golang.org/pkg/runtime/trace/#IsEnabled), augmenting the `go tool trace` output with information that is valuable to the user on profiling.

Overhead should be completely negligible when tracing is disabled.

**Comment by gbbr** [comment]
A PR to illustrate a proposed implementation is opened at #467.

**Comment by cgilmour** [comment]
Sounds like a good thing to include.
Is the PR a full implementation, or are there a few more things to add?
Would users be able to pass a `context.Context` in so they get parented properly?

**Comment by gbbr** [comment]
I guess not, at this point. That would require a lot more changes. I’d propose to start basic and move forward based on feedback and adoption.

**Comment by cgilmour** [comment]
That's reasonable.
But it might be worth it to do it for a single contrib (eg: `net/http`) as an experiment.
A suggestion only, and update the PR's reviewers and labels when you're ready.

**Comment by gbbr** [comment]
I don't see why we'd want to do that. Given that this is disabled by default, and only runs when tracing is enabled, I don't see any impact of it. Furthermore, if someone wants to try it out, why should they only get a small part of their app (or none) marked when they can get the whole thing?

**Comment by gbbr** [comment]
Added in #467
