### ISSUE TITLE
span.Resource, span.Duration, span.Sampled = false

### ISSUE THREAD

**Issue by Jin-Dhaliwal** [DataDog/dd-trace-go#469]
Hello,

I'm in the process of upgrading my vendored version of dd-trace-go from release `0.6.1` to latest. I'm not seeing a way to do the following that we used to be able to do:

`span.Resource` - inspect the resource name of a span after creation. We seem to be extremely limited in the information we can extract from a span after creating it...

`span.Duration` - inspect the current duration of a span.

`span.Sampled = false` - being able to tell a span that it should be discarded before we `Finish()` it. 

Please let me know if I am just looking in the wrong place. I need this functionality. I don't want to be tracing `404` requests. At minimum I need a way to tell a span that it's no longer needed.

**Comment by cgilmour** [comment]
Hi @Jin-Dhaliwal 
> We seem to be extremely limited in the information we can extract from a span after creating it

That's correct, they aren't exposed like they used to be. Were you inspecting `Resource` and `Duration` as part of tests, or for a different purpose?

> `span.Sampled = false`

This can be done using `span.SetTag(ext.ManualDrop, true)`

**Comment by Jin-Dhaliwal** [comment]
@cgilmour Thanks!

> That's correct, they aren't exposed like they used to be. Were you inspecting Resource and Duration as part of tests, or for a different purpose?

I was inspecting Resource to match it against the current Resource being processed in the app. In the case where the current resource is actually a child process of another resource we wanted to make sure the span we are marking as unneeded wasn't a parent span for some other resource.
