### ISSUE TITLE
contrib/jinzhu/gorm: passing trace ids into gorm

### ISSUE THREAD

**Issue by NilsJPWerner** [DataDog/dd-trace-go#474]
I'm currently instrumenting end to end distributed tracing in my application. I want to include gorm spans in the trace but I can't find a way of injecting the span ids into the gorm trace. 

I see that the sql tracer has a way of doing it: https://godoc.org/gopkg.in/DataDog/dd-trace-go.v1/contrib/database/sql#ex-package--Context 

I have also found opentracing gorm contribs that have that functionality: https://github.com/smacker/opentracing-gorm

**Comment by NilsJPWerner** [comment]
I looked into switching to sqlx since it appears that it supports passing contexts through queries unlike gorm: https://godoc.org/github.com/jmoiron/sqlx#DB.QueryxContext. However it seems like ddtrace doesn't support this either. This seems like it would be an easier package to instrument than gorm though.

**Comment by cgilmour** [comment]
Yes, passing contexts through is the key to getting distributed traces in the database calls.
The current gorm instrumentation doesn't seem to have an easy path to this. The callback approach you linked to might be the right way forward - I'll check about it in more detail.

For sqlx, it should be working when the connection is opened using the wrapper ( gopkg.in/DataDog/dd-trace-go.v1/contrib/jmoiron/sqlx ) and passing the context through in database calls. What happened instead?

**Comment by NilsJPWerner** [comment]
I hadn't tested sqlx before because I didn't see any examples in the example_test.go file and therefore assumed it wasn't supported. Just created a small test and it is indeed working. Thank you for the confirmation. Now comes the painful task of switching all gorm code to sqlx.

**Comment by cgilmour** [comment]
That confirmation is helpful and also highlights an improvement we can try to make available.
Eg: spans for a web request and also a DB interaction.

For now, let's keep this issue open for the original report - possible improvements of tracing for gorm.
