### ISSUE TITLE
Gin tracing option to set resource name to url

### ISSUE THREAD

**Issue by NilsJPWerner** [DataDog/dd-trace-go#476]
It would be great to be have a gin tracing configuration option that uses `c.Request.URL.Path` for tracer.ResourceName instead of `c.HandlerName()`. 

The handler name string is always something unnecessarily long and contrived like: `github.com/xyz-company/cool-app-123/web.(*Server).healthCheck-fm`. I think that url is also the more correct resource name.

**Comment by cgilmour** [comment]
@NilsJPWerner nice idea!
A similar thing was added in #461 where `WithResourceNamer` lets you supply a function that returns resource names.
In this case, the namer function would probably take a `gin.Context` as the parameter.

Would you be interested in submitting a PR?

**Comment by NilsJPWerner** [comment]
Here is the PR: go/pull/477
