### ISSUE TITLE
contrib/gin-gonic/gin: add query string tag option

### ISSUE THREAD

**Issue by NilsJPWerner** [DataDog/dd-trace-go#479]
It would be great to have an option for the gintracer that adds a query string tag. This would of course be optional because of potentially sensitive information in the query string. This could be implemented with a urlTagger function option, that lets you create your own tag based on the url struct.

If this is a good idea, I can create the PR.

**Comment by cgilmour** [comment]
Are you able to do this using `SpanFromContext` ?
Code below is untested, but may be close to what you asked for.
 
```go
if span, ok := tracer.SpanFromContext(c.Request.Context()); ok {
    span.SetTag(ext.HTTPURL, c.Request.URL.RequestURI())
}
```

**Comment by NilsJPWerner** [comment]
I'd like to have the option to set this up for every route across a lot of services. I think it would be useful to have a built in option.

**Comment by gbbr** [comment]
As you've stated yourself, I don't think this is something we'd want to add into the package, because it risks exposing sensitive data. You can, at your own risk, simply add an extra middleware following the Datadog one, which contains code similar to what @cgilmour described, for example:
```
r.Use(
	gintrace.Middleware("my-web-app"),
	func(c *gin.Context) {
		if span, ok := tracer.SpanFromContext(c.Request.Context()); ok {
                     span.SetTag(ext.HTTPURL, c.Request.URL.RequestURI())
		}
	},
)
```

**Comment by gbbr** [comment]
@NilsJPWerner if that works, can we close the issue?

**Comment by NilsJPWerner** [comment]
I understand. Thank you for considering it :)
