### ISSUE TITLE
contrib/gorilla/mux: add middleware to include HTTP headers and query string

### ISSUE THREAD

**Issue by thomas91310** [DataDog/dd-trace-go#480]
These are two middlewares I have been adding to a good amount of projects:
`addHeaders` and `addQuery` (middlewares that rely on the `mux` contrib).
 
I think that these two middlewares could live inside the contrib itself so we don't have to duplicate the code in all our projects.

I'd think a good amount of people have similar logic. It's always good to have headers and query string split out in the span even though sometimes it might be a good amount of data...

These are the two middlewares:

```golang
// add the headers to the current span
func addHeaders(original http.Handler) http.Handler {
	return http.HandlerFunc(func(rw http.ResponseWriter, r *http.Request) {
		// the root span was just started so get it
		span, _ := tracer.SpanFromContext(r.Context())

		for k, v := range r.Header {
			span.SetTag(fmt.Sprintf("http.headers.%v", k), strings.Join(v, ""))
		}

		original.ServeHTTP(rw, r)
	})
}
```

```golang
// add the query string parameters to the current span
func addQuery(original http.Handler) http.Handler {
	return http.HandlerFunc(func(rw http.ResponseWriter, r *http.Request) {
		// the root span was just started so get it
		span, _ := tracer.SpanFromContext(r.Context())

		query, err := url.ParseQuery(r.URL.RawQuery)
		if err != nil {
			span.SetTag(ext.Error, err)
		}

		// the query map will be empty in case of an error in ParseQuery
		for k, v := range query {
			span.SetTag(fmt.Sprintf("http.querystring.%v", k), strings.Join(v, ""))
		}

		original.ServeHTTP(rw, r)
	})
}
```

This is the server code where the two middlewares are in use:
```golang
package main

import (
	"fmt"
	"os"

	"gopkg.in/DataDog/dd-trace-go.v1/contrib/gorilla/mux"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
)

const (
	serviceName = "my-service"
)

var (
	env          = os.Getenv("ENV")
	ddHost       = os.Getenv("DD_HOST")
	ddTracerPort = os.Getenv("DD_TRACE_PORT")
)

func main() {
	tracer.Start(
		tracer.WithAgentAddr(fmt.Sprintf("%v:%v", ddHost, ddTracerPort)),
		tracer.WithServiceName(serviceName),
		tracer.WithGlobalTag("env", env),
	)
	defer tracer.Stop()

	r := mux.NewRouter(
		mux.WithServiceName(serviceName),
		mux.WithAnalytics(true),
	)
	r.Use(
		addHeaders,
		addQuery,
	)

	// start the server somewhere ....
}
```

**Comment by gbbr** [comment]
Unfortunately we don't want to do this because headers and query strings can contain sensitive information such as API keys, tokens, etc. It's best this stays within the control of the user (you).

**Comment by thomas91310** [comment]
- It's a middleware so you can just opt in / opt out of it so it's not like I'm imposing on everybody to use this but it's just like an option that you can opt in / opt out of.

- I would add that the goal of APM as a product is to help understand request flow and troubleshoot issues on certain requests that fail under certain circumstances.
If you're missing half of the information, how can you really replicate a problem? Who knows if the api key/secret was properly passed (on the query string/header) on a specific HTTP call? 
It is more a concern to me to quickly be able to identify and replicate why a service might behave a certain way than it is to show an api key or a secret on a company's private datadog UI. 
I definitely understand why you would not make this part of every single span but I don't really understand why you wouldn't provide the tooling necessary for your customers to add this metadata to their spans if they want to/need to.

For example, I do this with a debug flag (if true, start adding metadata to the spans, otherwise don't):
```golang
package main

import (
	"fmt"
	"os"
	"strconv"

	"github.com/DataDog/dd-trace-go/ddtrace/tracer"
	"gopkg.in/DataDog/dd-trace-go.v1/contrib/gorilla/mux"
)

var (
	debug, _ = strconv.ParseBool(os.Getenv("SERVICE_DEBUG"))
)

func main() {
	tracer.Start(
		tracer.WithAgentAddr(fmt.Sprintf("%v:%v", ddHost, ddTracerPort)),
		tracer.WithServiceName(serviceName),
		tracer.WithGlobalTag("env", env),
	)
	defer tracer.Stop()

	r := mux.NewRouter(
		mux.WithServiceName(serviceName),
		mux.WithAnalytics(true),
	)

	if debug {
		r.Use(
			addHeaders,
			addQuery,
		)
	}
}

```

**Comment by gbbr** [comment]
@thomas91310, I know it's been ages, but if you're still interested we could add these behind two configuration options: `WithHeaderTags` and `WithQueryString` if you like. 

* For headers, we'll have to make sure to exclude `x-datadog-*` headers though as we don't want those...
* For query strings, just one tag will be enough `http.querystring` (no need to have one for each key)

**Comment by mgale** [comment]
Coming in late ... could we also include the CORS middleware support? https://github.com/gorilla/mux#handling-cors-requests.

**Comment by mgale** [comment]
Also it maybe adding an option to blacklist or whitelist query params?
