### ISSUE TITLE
ddtrace/mocktracer: WithSpanID option is ignored

### ISSUE THREAD

**Issue by EmilGedda** [DataDog/dd-trace-go#481]
I don't know if this is a bug or expected behaviour but it definitely caught me by surprise.

Reproduction: https://play.golang.org/p/EAoiusEOkOh
Expected behaviour: That the SpanID in the SpanContext of my span should have the id I specified in WithSpanID.
Observed behaviour: The span gets a SpanID (and TraceID) of 0

Essentially when creating a new span with `tracer.WithSpanID`, the span's `SpanContext` will return 0 for the SpanID and TraceID which contradicts with the documentation of `tracer.WithSpanID`:
> WithSpanID sets the SpanID on the started span, instead of using a random number. If there is no parent Span (eg from ChildOf), then the TraceID will also be set to the value given here.

Is this a bug or am I misunderstanding what the SpanContext is?

**Comment by gbbr** [comment]
@EmilGedda that's because `WithSpanID` is not considered in the mock tracer (which is the default tracer). If you add `tracer.Start()` at the beginning of your code, it will work as expected.

**Comment by EmilGedda** [comment]
> @EmilGedda that's because `WithSpanID` is not considered in the mock tracer (which is the default tracer). If you add `tracer.Start()` at the beginning of your code, it will work as expected.

Thanks for the explanation, that explains my confusion when trying to isolate this in tests.

Closing as invalid.

**Comment by gbbr** [comment]
No problem. We should however, maybe add this to the mock tracer. Let's change the issue title a bit and leave it open, ok?
