### ISSUE TITLE
proposal: find a better way to configure integrations

### ISSUE THREAD

**Issue by gbbr** [DataDog/dd-trace-go#493]
[Some integrations](https://github.com/DataDog/dd-trace-go/blob/402d3cf/contrib/net/http/option.go) have gotten nasty, like the `net/http` one where we have `MuxOption`, `RoundTripperOption` along with functional options that clash names.

We should investigate better ways. One suggestion is to have just one global `Option` structure per package and many functional options, where not all functional options apply to all scenarios. For example (in the context of `net/http`): some apply to the multiplexer (mux) and some apply to the roundtripper, but also some apply to both.

**Comment by darccio** [comment]
Solved in `v2-dev`: [net/http](https://github.com/DataDog/dd-trace-go/blob/0d5f5a766e7556e858a83d9962a70338c048616a/contrib/net/http/option.go#L42) example.
