### ISSUE TITLE
Setting tags at the tracer level

### ISSUE THREAD

**Issue by Taik** [DataDog/dd-trace-go#50]
Hello, are there plans to set tags at the tracer level? Basically the equivalent of [`tracer.set_tags()`](http://pypi.datadoghq.com/trace/docs/#ddtrace.Tracer.set_tags) from DD's python tracing library.

**Comment by palazzem** [comment]
Hello @Taik ! Sure that's in our plans and we're going to improve the Go client so that it has the same set of functionalities as the Python one. Will keep you updated!

**Comment by YassineE** [comment]
Hello, this functionality is really required for us. Do you know when it will be released ?

**Comment by YassineE** [comment]
#56 will fix this issue. Thanks to the team !

**Comment by ufoot** [comment]
Hi @YassineE #56 has been merged so this is definitely going to ship in the next release, stay tuned.

**Comment by YassineE** [comment]
Hello @ufoot, do you know when it will be released ?
Thanks,

**Comment by furmmon** [comment]
Fixed on #56, released on v0.4.0
