### ISSUE TITLE
Tracer should use environment variables if they exist

### ISSUE THREAD

**Issue by blaketastic2** [DataDog/dd-trace-go#500]
The DataDog go tracer should align itself with the other DataDog language tracing implementations and use environment variables to set default values such as global tags, service name, etc.

Here's an example of what's available via Java - https://docs.datadoghq.com/tracing/setup/java/#configuration

List of environment variables to support:
- `DD_SERVICE_NAME` - set the name of the application being traced
- `DD_TRACE_GLOBAL_TAGS` - set default tags like `env`, etc.
- `DD_AGENT_HOST` - Already supported, just wanted to call out
- `DD_TRACE_AGENT_PORT` - Already supported, just wanted to call out

Additional variables to get input from the community on:
- `DD_SERVICE_MAPPING` - control renaming integrations from a central place. Will require `contrib` packages to look at the tracer config as part of their `default` method
- `DD_WRITER_TYPE` - Not sure if Go will support writing to stdout vs an agent
- `DD_TRACE_SPLIT_BY_TAGS` - Rename spans to use provided service name
- `DD_PROPAGATION_STYLE_INJECTION` - `DataDog` vs `B3`
- `DD_TRACE_SPAN_TAGS` - List of default tags to be added to every span
- `DD_TRACE_HEADER_TAGS` - Map headers to trace tags
- `DD_TRACE_PARTIAL_FLUSH_MIN_SPANS` - Allow control of flushing the spans based on count
- `DD_TRACE_REPORT_HOSTNAME` - Add the hostname to the trace data
- `DD_LOGS_INJECTION` - This will rely on auto-instrumentation working. See https://docs.datadoghq.com/tracing/advanced/connect_logs_and_traces/?tab=go#automatic-trace-id-injection for details

**Comment by gbbr** [comment]
Thanks Blake, can you please list here the environment variables that you wish to add? We can discuss them. Not all of the ones in the list for Java, apply to Go.

Are you talking specifically about `DD_SERVICE_NAME` and `DD_TRACE_GLOBAL_TAGS` ? In which case, let's be specific about that.

**Comment by blaketastic2** [comment]
shouldn’t we implement all that are applicable to Go? In my use, DD_SERVICE_NAME and DD_TRACE_GLOBAL_TAGS made sense, but I’m guessing there are others that I missed.

**Comment by gbbr** [comment]
Whatever we implement, we should list each one clearly here. I'd recommend we start with the two that you suggested. What do you think?

**Comment by blaketastic2** [comment]
@gbbr That sounds good. I've update the description to include all values that should be potentially added. Let's get the community to give some input on the values. In the mean time, do you want me to split out another issue that tracks just the `DD_SERVICE_NAME` and `DD_TRACE_GLOBAL_TAGS`, and reference it here? Then I can get that PR back out?

**Comment by gbbr** [comment]
My recommendation, to simplify the process, is to limit the issue to only the environment variables you need, and then we can focus on those and make sure they get implemented and merged as soon as possible.

Other community members who wish to request support for further environment variables can open separate issues mentioning those specifically. I feel there is no point to add in env. vars. that are not needed by anyone yet.

I'd suggest we focus on the ones you need only, because some of the others may require longer discussions. That will simplify the process, as well as bring your the result you are after (e.g. getting your PR back on). What do you think?

**Comment by blaketastic2** [comment]
Yep, that's why I've created #501 , to track just the changes I'm looking for.

**Comment by gbbr** [comment]
Cool, thanks! I'd suggest we close this one then.

**Comment by knusbaum** [comment]
I'm going to close this in favor of #501 
Please reopen if this is still needed.
