### ISSUE TITLE
proposal: tracer to support DD_SERVICE_NAME and DD_TRACE_GLOBAL_TAGS environment variables

### ISSUE THREAD

**Issue by blaketastic2** [DataDog/dd-trace-go#501]
Currently, tracer does not support `DD_SERVICE_NAME` and `DD_TRACE_GLOBAL_TAGS`. I would like to be able to use my default environment variables to set the tracer values from these environment variables, but still allow for overwriting at the method level.

**Comment by gbbr** [comment]
Thank you for taking the time to go through the regular process. We are more than happy to accept a PR now and work through it.
