### ISSUE TITLE
strings.Builder is not supported in Go 1.9

### ISSUE THREAD

**Issue by greedo** [DataDog/dd-trace-go#502]
Docs currently say this library supports Go 1.9 however [here](https://github.com/DataDog/dd-trace-go/blob/7dee14a75b219a87013f9ec1467f9cb0345b25f9/ddtrace/tracer/span.go#L168) `strings.Builder` is used which was added in Go 1.10 https://golang.org/pkg/strings/#Builder.String

**Comment by cgilmour** [comment]
Thanks for reporting this!
I've opened #503 to fix the readme.

**Comment by greedo** [comment]
Thanks so much :+1:
