### ISSUE TITLE
proposal: support github.com/99designs/gqlgen

### ISSUE THREAD

**Issue by danishsatkut** [DataDog/dd-trace-go#507]
The library `https://github.com/99designs/gqlgen` package is the most maintained and feature rich graphql server library.

**Comment by gbbr** [comment]
Thanks @danishsatkut. That library is still early days (v0), but we're starting to brainstorm in a draft at #515. Feel free to jump in if you have ideas.

**Comment by knusbaum** [comment]
We are going to put this integration on hold for the time being. The gqlgen author has made us aware that there are going to be significant changes to the resolver and tracer interfaces coming soon, so we'll wait for that to happen before we continue this. (See: https://github.com/DataDog/dd-trace-go/pull/515#issuecomment-547207818)

**Comment by andytruong** [comment]
More and more companies are using it, including Khan Academy: https://github.com/99designs/gqlgen/issues/268

**Comment by jippi** [comment]
Hi, any chance to revive this integration? been 12 months since the last update, it would be fair to think either they changed their interfaces by now, or they never did anyway :)

**Comment by knusbaum** [comment]
We should figure out how we want to support v0 libraries. (#729)
Gqlgen is requested a lot and we want to support it.

I don't know when they plan on publishing v1, but according to this comment by @vektah (https://github.com/DataDog/dd-trace-go/pull/515#issuecomment-559480785), the handler refactor is done.

**Comment by samlof** [comment]
There is https://github.com/99designs/gqlgen-contrib/blob/master/gqlopencensus/tracer.go which has DataDog bool. It's not plug and play but should help for users who need tracing to datadog

**Comment by jpeeler** [comment]
Perhaps now that a [new release](https://github.com/99designs/gqlgen/releases/tag/v0.14.0) as of about a week ago was done, this can be revisited?

@vektak can you provide some assurance that the tracing implementation is nearing stability at this point?

**Comment by DurkinDevelopment** [comment]
Any updates on this that might not of been linked?

**Comment by ashishb** [comment]
Any details on how to configure and use DataDog with this - https://github.com/DataDog/dd-trace-go/issues/507#issuecomment-891479205

**Comment by katiehockman** [comment]
This is in progress, but is not yet supported. Will provide updates here when a PR is out.

**Comment by knusbaum** [comment]
DONE!
