### ISSUE TITLE
proposal: remove or improve useless Sampler interface

### ISSUE THREAD

**Issue by gbbr** [DataDog/dd-trace-go#508]
Current [`Sampler`](https://godoc.org/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer#Sampler) interface is useless and can not be implemented by external code because its parameter is a read-only span which doesn't help take sampling decisions.

We should either:

* Remove this interface completely and simply allow setting a client sampling rate.
* Provide it an argument that can reveal span properties.

**Comment by knusbaum** [comment]
Fixing the interface might be useful, but do we know of anyone that needs it? I'd be more in favor of removing the interface since we have the rules sampler. I would say if we get requests for more dynamic sampling, we can revisit the sampler interface.

**Comment by ahmed-mez** [comment]
Addressed in https://github.com/DataDog/dd-trace-go/pull/2395
