### ISSUE TITLE
proposal: write HTTP status code response if handler panics

### ISSUE THREAD

**Issue by sayboras** [DataDog/dd-trace-go#516]
Due to any reason, http handler function got panic, we don't have status code in trace. Without status code, the APM tracing will consider this request as successful. This will have huge impact for any monitoring based on status code
 
I am thinking about to extend this defer function https://github.com/DataDog/dd-trace-go/blob/v1/contrib/internal/httputil/trace.go#L33 

Draft changes https://github.com/sayboras/dd-trace-go/pull/1

**Comment by gbbr** [comment]
Instrumentation libraries are supposed to be non-intrusive. It's the responsibility of the server author to reply to clients, and by no means should the tracing library write a status code response.

I'm afraid this isn't something that we can add.

**Comment by sayboras** [comment]
It's good point, can we set some other tags such as `error`, `error.object`, etc instead ?

**Comment by gbbr** [comment]
APM currently offers you visibility into status code errors returned by an endpoint. The standard library (`net/http`) doesn't panic unless a programming error occurs on the user side, or unless user code panics. This is the reason why I think the code you propose does not belong in the integration. I tend to believe it's better suited in user code.

Are you not able to do this in your handler?

```go
defer func() {
    if e := recover(); e == nil {
        return
    }
    span, ok := tracer.SpanFromContext(req.Context())
    if !ok {
        return
    }
    span.SetTag("error", e)
}
```

**Comment by sayboras** [comment]
I tried but still can't. As recovery handler is the first one in middleware chain, the span is already finished in router.

```
http.ListenAndServe(handlers.RecoveryHandler(
				handlers.RecoveryLogger(logger.GetLogger()),
				handlers.PrintRecoveryStack(true))(router),
		)
````

**Comment by gbbr** [comment]
It works fine for me. 

Code: 
https://play.golang.org/p/U9P8Yaeu7Vy

Result:
<img width="1013" alt="Screenshot 2019-10-21 at 10 30 48" src="https://user-images.githubusercontent.com/6686356/67185187-f1bced00-f3ed-11e9-9da9-3a1c211d4d9e.png">

It looks to me that you are having difficulties with `gorilla/mux` instead, which is a separate repository. If you think that something doesn't work as expected over there, my suggestion is to open an issue on that repository instead.

**Comment by sayboras** [comment]
@gbbr Thanks a lot for your help
