### ISSUE TITLE
proposal: contrib/gin-gonic/gin: filter out traces of incoming requests to specific urls

### ISSUE THREAD

**Issue by skaji** [DataDog/dd-trace-go#519]
`dd-trace-py` allows us to filter out traces of incoming requests to specific urls:
https://github.com/DataDog/dd-trace-py/blob/master/docs/advanced_usage.rst#trace-filtering

I would like `contrib/gin-gonic/gin` to support this feature too.
If `contrib/gin-gonic/gin` supported this feature, I would filter out traces for health checks.

**Comment by gbbr** [comment]
I think this is something interesting to have. I'm wondering whether it should be added as a global feature or specific to the contribution.

But before exploring this further, have you considered using the `apm_config.ignore_resources` setting in the Datadog Agent `datadog.yaml` file? See https://github.com/DataDog/datadog-agent/blob/6.14.0/pkg/config/config_template.yaml#L456-L460

**Comment by skaji** [comment]
@gbbr Thanks!
Oh, I haven't noticed `apm_config.ignore_resources`.
I'll look into it.

**Comment by gbbr** [comment]
Cool! Let me know how it goes!

**Comment by skaji** [comment]
I was able to filter out health checks by setting environment variable `DD_APM_IGNORE_RESOURCES=healthHandler` to datadog agents.
Thanks!

I am deploying datadog agents as kubernetes daemonsets so that they are shared with various clients.
Thus it would be still nice to filter out some traces in client side (not in agent side).

Anyway, I was able to filter out health checks. Thanks again!

@gbbr Please feel free to close this issue.

**Comment by gbbr** [comment]
@skaji glad it worked! If you like, I am more than happy to accept a proposal as a separate issue which suggests adding support for filtering out traces on the client side, if you have ideas on how this would work and you believe it's worth adding.
