### ISSUE TITLE
SpanFromContextDefault causes panics

### ISSUE THREAD

**Issue by jbowes** [DataDog/dd-trace-go#52]
After the fix for https://github.com/DataDog/dd-trace-go/issues/46 was applied, if SpanFromContextDefault is called when there is no existing span, a new one is created with a zero valued Transport, including a nil randGen.

Using this span previously would allow you to record data, but it wouldn't go anywhere. Now, trying to use  this span's tracer to make a new child span will cause a panic when it tries to generate a new span id for the child.

**Comment by galdor** [comment]
Fixed by #54.

**Comment by LotharSee** [comment]
Closing it since a fix got shipped. Are all things good to you now?
Feel free to create a new one if any similar issue happen again!
