### ISSUE TITLE
proposal: support differentiation between streaming and unary RPCs

### ISSUE THREAD

**Issue by jonasrmichel** [DataDog/dd-trace-go#521]
As a consumer of the gRPC tracer, I would like the ability to view and analyze streaming and unary traces separately within the APM UI.

The [gRPC tracer](https://github.com/DataDog/dd-trace-go/tree/v1/contrib/google.golang.org/grpc) provides a stream and unary interceptor for both clients and servers. These interceptors are configured with RPC metadata like `service` (gRPC service name), `method` (RPC name), and `operation` (client or server). 

However, none of these interceptors capture whether a span is streaming or unary within the span's metadata. This means it's impossible to differentiate between streaming and unary RPCs within the APM UI and at the metric level. 

The very specific symptom is that APM latency metrics are heavily skewed towards streaming RPCs, especially in scenarios where streaming RPCs may last for an indefinite amount of time. However, in general, it would be exceptionally useful to have the ability to analyze, search, filter by, etc. streaming and unary RPCs separately.

**Comment by cgilmour** [comment]
For reference, the python tracer already supports this and a handful of [additional tags](https://github.com/DataDog/dd-trace-py/blob/master/ddtrace/contrib/grpc/constants.py#L6-L22) for grpc.

This one would be tagged `grpc.method.kind` with one of these values: `unary`, `client_streaming`, `server_streaming`, `bidi_streaming`.
A fix for this would need to match that tag names and values.

@jonasrmichel from the additional tags listed, would many of them be useful for analysis / search / filtering? It'd be good to get the top ones included in this proposal, so they could be done with a  higher priority than informational tags that don't get analyzed.

**Comment by jonasrmichel** [comment]
@cgilmour -- Thanks for the snappy turnaround.

The four `grpc.method.kind` tags you identified would be immensely useful within the APM UI and would solve this issue.
* `unary`
* `client_streaming`
* `server_streaming`
* `bidi_streaming`
