### ISSUE TITLE
proposal: have one single global Option type for an entire integration

### ISSUE THREAD

**Issue by gbbr** [DataDog/dd-trace-go#532]
The proposal is to have only one global `Option` type for an entire integration, as opposed to multiple `Option` types for different functions in the same integration, resulting in difficulties with naming and bad practices, such as [`Option`](https://github.com/DataDog/dd-trace-go/blob/v1/contrib/net/http/option.go#L26) vs. [`RoundTripperOption`](https://github.com/DataDog/dd-trace-go/blob/v1/contrib/net/http/option.go#L93) in the `net/http` integration, resulting in terrible option names like [`WithAnalytics`](https://godoc.org/gopkg.in/DataDog/dd-trace-go.v1/contrib/net/http#WithAnalytics) and [`RTWithAnalytics`](https://godoc.org/gopkg.in/DataDog/dd-trace-go.v1/contrib/net/http#RTWithAnalytics).

The downside of this would be that some options might apply to one construct but not to another, but that may seem like a reasonable compromise to take.

**Comment by knusbaum** [comment]
This is related to #493

**Comment by gbbr** [comment]
Duplicate even :)
