### ISSUE TITLE
contrib/gomodule/redigo: Redigo don't support ConnWithTimeout

### ISSUE THREAD

**Issue by MichaelMure** [DataDog/dd-trace-go#535]
Redigo instrumentations implement `redis.Conn` but not not `redis.ConnWithTimeout`.

When trying to use a timeout enabled function (say `ReceiveWithTimeout`), Redigo return a `redis: connection does not support ConnWithTimeout` error.

**Comment by gbbr** [comment]
The [documentation](https://godoc.org/github.com/gomodule/redigo/redis#ConnWithTimeout) for `ConnWithTimeout` specifies:
> All of the Conn implementations in this package satisfy the ConnWithTimeout interface.

As a result, we should also support this. This should be an easy change.

**Comment by MichaelMure** [comment]
Note that this also concern `contrib/gomodule/redigo` and that `contrib/garyburd/redigo` is not maintained anymore upstream.

**Comment by gbbr** [comment]
Right, sorry. I forgot we have both. It makes sense to probably apply it to `contrib/gomodule/redigo` only.
