### ISSUE TITLE
proposal: add support for upper.io/db

### ISSUE THREAD

**Issue by salvalcantara** [DataDog/dd-trace-go#538]
Are there plans to add support for [upper.io/db](https://upper.io/db.v3/)? Maybe there is a simple workaround using the existing integration for database/sql. Otherwise I would like to work on this.

**Comment by gbbr** [comment]
I don't see why not. Before starting work, can you please tell us the plan. Does this package provide any hooks for instrumentation or do we need to take a different approach?

**Comment by salvalcantara** [comment]
From what I have seen, it seems that each adapter (leaving aside Mongo for now) allows to create a session based on an existing sql connection. For example, for postgres:

```go
// New wraps a regular *sql.DB session and creates a new upper-db session
// backed by it.
func New(sess *sql.DB) (sqlbuilder.Database, error) {
	d := newDatabase(nil)

	// Binding with sqladapter's logic.
	d.BaseDatabase = sqladapter.NewBaseDatabase(d)

	// Binding with sqlbuilder.
	d.SQLBuilder = sqlbuilder.WithSession(d.BaseDatabase, template)

	if err := d.BaseDatabase.BindSession(sess); err != nil {
		return nil, err
	}
	return d, nil
}
```

So one option would be to provide a `New` in the integration which would basically build the traced sql.DB using existing integration for database/sql and then invoke the above method:

```go
// The first step is to register the driver that we will be using.
sqltrace.Register("postgres", &pq.Driver{})

// Followed by a call to Open.
db, err := sqltrace.Open("postgres", "postgres://pqgotest:password@localhost/pqgotest?sslmode=disable")

// Create upper.io/db Database
return New(db)
```

Apart from `New`, they also provide `Open`:

```go
func Open(settings db.ConnectionURL) (sqlbuilder.Database, error) {
	d := newDatabase(settings)
	if err := d.Open(settings); err != nil {
		return nil, err
	}
	return d, nil
}
```

I guess we could just call our `New` inside for this case.

For Mongo (the only NoSql available), there is only the option for the `Open`:

```go
// Open attempts to connect to the database.
func (s *Source) Open(connURL db.ConnectionURL) error {
	s.connURL = connURL
	return s.open()
}
```

So for this case we will need to basically replicate what `s.open()` does but injecting a traced mongo connection instead (using existing integration in contrib).

**Comment by gbbr** [comment]
Given that we can already use the existing `sql` integration and 3 lines of code, why do you want to add a new integration?

**Comment by salvalcantara** [comment]
Yeah...I had not seen the actual code when I raised the issue (specially
the New method). Let me check that it works as described above and if this
is the case you're probably right and can just close the issue.

**Comment by salvalcantara** [comment]
@gbbr I confirm that integration is quite straightforward by just using the existing `sql` integration:

```
func getUpperIoDbSession(c *config.Config, logger logging.Logger) sqlbuilder.Database {
	sqltrace.Register("postgres", &pq.Driver{})
	db, err := sqltrace.Open(
		"postgres",
		fmt.Sprintf("%s:%s@%s/%s", c.DbUser, c.DbPassword, c.DbHost, c.DbName),
	)
	if err != nil {
		logger.Fatal("Error connecting to database: ", err)
	}
	sess, err := postgresql.New(db)
	if err != nil {
		logger.Fatal("Error connecting to database: ", err)
	}
	return sess
}
```

You can close the issue, thanks!
