### ISSUE TITLE
Number of facets limit?

### ISSUE THREAD

**Issue by thomas91310** [DataDog/dd-trace-go#541]
Hello!

I know this is quite unrelated to this repo but what is (if there is) a limit on the number of facets you can create for an analyzed span?
I didn't find anything in https://docs.datadoghq.com/tracing/advanced/

I also asked my question in the datadog #apm slack room.
I can also create a support ticket for this if you think that is better.

Let me know,

Thanks,
Thomas

**Comment by cgilmour** [comment]
Hi @thomas91310, creating a support ticket would be better for this question, thanks!

**Comment by thomas91310** [comment]
ugh -__-'
Thought there would be a quick answer to this.
I'll close this for now
