### ISSUE TITLE
proposal: suffix all contrib folders with their version

### ISSUE THREAD

**Issue by gbbr** [DataDog/dd-trace-go#544]
We should suffix all contrib version with their version, in order to clarify and clearly differentiate between the versions that they address. Currently this can become confusing. For unstable releases we should use `.v0`.

Slightly described here: https://github.com/DataDog/dd-trace-go/tree/v1/contrib#usage

**Comment by knusbaum** [comment]
I think this will help make things much clearer.

**Comment by knusbaum** [comment]
I have some questions about this. 
How will we manage this with integrations that work across multiple versions? Do we want to avoid preemptively duplicating code when the integration target changes its version unless we *have* to? If the same integration works for `v0.*`, `v1.*`, and `v2.*`, I don't know that we want to copy that code into three directories.

The convention could be that the directory suffix will be the lowest working version, and we add a new directory only when there is a change to the library or the tracer that breaks the integration.

As an example, if an integration works with `v0.*`, `v1.*`, and `v2.*`, but not `.v3.*`, There should be one directory with suffix `.v0`, and one with `.v3`. 

We should also consider how this works with modules, so we can pull in different versions of the target libraries in the different directories. I *think* submodules should work for this, but we should experiment with it.

**Comment by gbbr** [comment]
> The convention could be that the directory suffix will be the lowest working version, and we add a new directory only when there is a change to the library or the tracer that breaks the integration.

Correct.

> As an example, if an integration works with v0.*, v1.*, and v2.*, but not .v3.*, There should be one directory with suffix .v0, and one with .v3.

This is a small likelihood though, given that a new major version usually means a breaking change. But we can definitely apply what you say, if it makes sense.

> We should also consider how this works with modules [...]

Modules are exactly the reason why this change was made. 

> I think submodules should work for this, but we should experiment with it.

We don't want to use submodules because of how much they are advised against and all the problems they can present https://github.com/golang/go/wiki/Modules#faqs--multi-module-repositories

All in all, I still think this plan is solid.

**Comment by knusbaum** [comment]
> We don't want to use submodules because of how much they are advised against and all the problems they can present https://github.com/golang/go/wiki/Modules#should-i-have-multiple-modules-in-a-single-repository

Glad to hear that. I think it's good to avoid if we can.
We need to figure out how we want to deal with multiple versions of dependencies in the same module.
For example, `github.com/DataDog/dd-trace-go/contrib/google.golang.org/grpc.v12` depends on `google.golang.org/grpc@v1.2.0` and  `github.com/DataDog/dd-trace-go/contrib/google.golang.org/grpc` depends on `google.golang.org/grpc@latest`

Does go have a mechanism to support this? I can't see anything that looks useful in the module documentation.

**Comment by darccio** [comment]
Implemented in `v2-dev`.
