### ISSUE TITLE
contrib/gin-gonic/gin: Setting "env" 

### ISSUE THREAD

**Issue by odannyc** [DataDog/dd-trace-go#556]
I can't find a way to add the "env" into my application. I am using the `gin` integration.
version: 1.19.0

**Comment by gbbr** [comment]
One way to set the env is setting `env: my-env` in the Datadog Agent's `datadog.yaml` file. Another way to globally set the env was added in https://github.com/DataDog/dd-trace-go/pull/529 which will be released after the holidays as part of v1.20.0.

If none of these are satisfactory, you could get the span in your handler from the request context and add it as a tag, e.g.
```
if span, ok := req.SpanFromContext(req.Context()); ok {
    span.SetTag(ext.Env, "my-env")
}
```

I hope one of these will do the job 🙂

**Comment by odannyc** [comment]
@gbbr 

Thank you! I'm waiting for 1.20 to be released. Do you have a date on when you are planning to release it

**Comment by gbbr** [comment]
We're planning to do it this week. Thanks for your patience.

**Comment by knusbaum** [comment]
@odannyc 1.20.1 has been released.

**Comment by knusbaum** [comment]
@odannyc Please feel free to re-open this issue if we haven't provided an adequate solution.
