### ISSUE TITLE
contrib/gin-gonic/gin: propsal of configurable operation name

### ISSUE THREAD

**Issue by Armatorix** [DataDog/dd-trace-go#558]
For now `operation name` is statis as value `http.request`. 
IMO it would be nice to make it configurable, so it could be used similarly to `resourceNamer`.

**Comment by gbbr** [comment]
In Datadog, it's most of the time optimal that the "operation name" remains static and does not change across requests. We use the top level operation name as a representative for a service and for calculating statistics. If the operation name were to become variable across requests, the experience in the UI would change on the service page and with regards to the computed stats, which might not be what you expect nor want. You can read more about it here: https://docs.datadoghq.com/tracing/guide/configuring-primary-operation/. 

Knowing this now, do you still feel like you'd want to change it? And why would you like to change it? And what would you change it to? Can you provide an example?

**Comment by Armatorix** [comment]
Yup, I managed to see that `operation name` is static across most of middlewares. 

So IMO it would be still nice to change.
First of all it would be nice to let user change it if he want to (even with function that will return static value, but it will be statis value set by user)

Second (and my case), I don't see any option to aggregate requests by method under specific service in the `Services` tab, so all GET/POST/DELETE of request with the same name would be aggregated under the same endpoint which is not a that great experience.
So I'm using `operation name` as `method` (most probably my bad and there is some other solution).

**Comment by gbbr** [comment]
I see what you're trying to do. I'm 100% you can do that with App Analytics. You don't need to have the operation name changed to obtain the data you want. I think it's just a matter of figuring it out in the product.

Since I have limited knowledge myself, I would recommend you reach out to our support team which will be more than happy to help you obtain the statistics that you are after. Please let me know how it goes...

**Comment by Armatorix** [comment]
I've already done all the aggregations and remappings, so in APM it looks OK, but not on the services tab. But anyway there is also the first case I mentioned which IMO would be nice to have

> First of all it would be nice to let user change it if he want to (even with function that will return static value, but it will be statis value set by user)

**Comment by gbbr** [comment]
We can explore that more if you like, but this is an operation name that we are using product-wide, cross language for HTTP requests. Changing it might have an undesired impact because you might cause the pipeline to drop some computations which you'd normally be getting.

Why would you want to call it something else? It is an HTTP request after all. I'm not against it, I'm just trying to make sure that these decisions will not turn around on us into less of an experience for you.

**Comment by Armatorix** [comment]
Oh, I was not aware of that it's some special value that you depend on.
So it would be nice to explore that topic for sure.

I just ended chat with help support, so:
There is no way to separate endpoints in services by the method with same name
(example:
so for now if I got
PATCH /example/product 
and
POST /example/product
and I'm providing them both with the name `/example/product` so they both appear under the same endpoint, so all metrics like error rate, or latency, etc. means nothing there. 
I would need to add a method to name (which is just a duplication of this property) or separate them by the operation name, which is why I create this ticket in the first place. and use it like `http.request.post`, `http.request.get` or even just `get` or `post`
end of example)

**Comment by gbbr** [comment]
Could you tell the support person to reach out to me with your org id? I would like to take a look at your account because it seems a bit odd to me that you say you can not do that. I think it is definitely possible using "Traces" or "App Analytics"

**Comment by Armatorix** [comment]
Yes, it is possible with these tools, but "Service List" or endpoints under specific http services from services lists are useless

**Comment by gbbr** [comment]
I totally understand what you mean 🙂The "Services" page is how Datadog APM started. At the time we did not have the "Traces" and "App Analytics" sections. These newer sections seem to be offering a lot more value and make it easier to extract the data you are after. 

Never the less, when you go to a service on the services page, you should still see two different entries in resources for "POST /path" and "PATCH /path", that's the part that confused me in your message.

**Comment by Armatorix** [comment]
So I used wrong wording...
I've got traces with following datadog endpoint names and methods:
dd name: /path
endpoint: /path
method: POST

dd name: /path
endpoint: /path
method: PATCH

I was writing that one of the solutions would be to add method in name.

**Comment by gbbr** [comment]
Oh my! I think you've actually discovered a bug here. The resource name should be `GET /path` or `PATCH /path`, but instead, it points to the handler name. I'm fixing this in #574. Until we release that as part of `v1.21.0`, you can work around it by using:

```
r.Use(gintrace.Middlware(gintrace.WithResourceNamer(func(c *gin.Context) string {
    return c.Request.Method + " " + c.FullPath()
}))
```

This should ensure that all resources are named as you would expect them. When you click on the service page, you should see correctly:
* `POST /path`
* `PATCH /path`

Please let me know if this fixes your issue.

**Comment by Armatorix** [comment]
This will fix my issue for sure, but also will double info about method, as it will be in resource name and method field, but yea... will work

**Comment by gbbr** [comment]
This is the standard for all our HTTP integrations. If you are happy with this result, please close the issue.
