### ISSUE TITLE
contrib/labstack/echo: Add filter option to whitelist requests with trace

### ISSUE THREAD

**Issue by rafaeljusto** [DataDog/dd-trace-go#562]
I would like to add an option to the `labstack/echo` middleware so we are able to decide the requests that we are adding trace. This is useful to turn off tracing depending on the environment or request data.

It would be something like:
```go
func Example() {
  filter := func(r *http.Request) bool {
    if r.RequestURI == "/dont/trace/me" || r.URL.Query().Get("notrace") == "true" {
      return false
    }

    return true
  }

  r := echo.New()
  r.Use(echotrace.Middleware(
    echotrace.WithServiceName("my-web-app"),
    echotrace.WithFilter(filter),
  ))

  r.GET("/hello", func(c echo.Context) error {
    return c.String(200, "hello world!")
  })

  r.Start(":8080")
}
```

**Comment by rafaeljusto** [comment]
By the way, I wrongly created the PR before discussing the issue here:
https://github.com/DataDog/dd-trace-go/pull/561

**Comment by gbbr** [comment]
Why would you like to turn off tracing? If you do this, it will affect stats and the values will be wrong in the UI. Maybe a better way to do it would be to simply apply sampling priority 0 to those traces? In your handler, you could do:

```go
if span, ok := tracer.SpanFromContext(ctx); ok {
    span.SetTag(ext.SamplingPriority, ext.UserReject)
}
```

This might be better. In the meantime, we will be adding a rule-based sampler in release v1.21.0 (https://github.com/DataDog/dd-trace-go/pull/546) which will do similar things to what you are trying to accomplish, in a more friendly way.

**Comment by rafaeljusto** [comment]
> Why would you like to turn off tracing?

There're some URI paths and environments (beta, staging) where I'm not interested in adding stats at all.

> This trace will then not show up in the UI, but you will still get stats for it.

Would set sampling priority 0 cost me? 💰

**Comment by gbbr** [comment]
> Would set sampling priority 0 cost me? 💰

It will not cost you anything. Those traces will reach the agent for stats computation and will be dropped there, never to reach the Datadog servers.

**Comment by rafaeljusto** [comment]
Perfect, thanks!

**Comment by gbbr** [comment]
You're welcome! Please feel free to come back if you run into any difficulties.

**Comment by aymericbeaumet** [comment]
`ext.UserReject` no longer seems to be exposed by the [`ext`](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/ext) package.

For those looking for a working solution (as of 2021), I've found that `span.SetTag(ext.ManualDrop, true)` produces a similar result of dropping the spans tagged that way.

**Comment by knusbaum** [comment]
@aymericbeaumet
Sorry, the tag should be `ext.PriorityUserReject`. I've updated the original comment mentioning `ext.UserReject`.
You are correct in pointing out `ext.ManualDrop`. `span.SetTag(ext.ManualDrop, true)` will have the exact same effect.
