### ISSUE TITLE
proposal: export tracer.contextKey

### ISSUE THREAD

**Issue by weisbartb** [DataDog/dd-trace-go#565]
Would it be possible to export `tracer.contextKey` so that it can be used inside of a custom wrapper to avoid having to navigate a linked list of contexts? It doesn't appear that anything would be affected outside of that file and `activeContextKey` would not need to exported. The only visible downside I can currently see is someone potentially miss-implementing the key and breaking their context. There is a guard in place to prevent an catastrophic interaction already.

**Comment by gbbr** [comment]
Hi Brian!

Thanks for your proposal! Let's explore it a bit together to make sure I don't misunderstand what you're after.

I'm not sure if exporting this key will add anything, because the idiom is already implemented: we have both [`SpanFromContext`](https://godoc.org/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer#SpanFromContext) and [`ContextWithSpan`](https://godoc.org/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer#ContextWithSpan) which do exactly as you would with the key itself, for you.

How would having the key help you? If you still think that's not enough, it would help me understand if you could provide actual code of what you are not able to do. For example: code that shows what you are doing now, and what you would like to do if the key were to be exported.

**Comment by weisbartb** [comment]
Hi Gabriel,

Those two methods that you have pointed out do not solve the issue I am trying to target.

Currently in some of our applications we have 10+ context extending items, `context.WithValue` invocations. This causes each `context.Value` lookup to (worst case) iterate through all of them. each time it is called to extract the underlying value. By exporting the struct that you use for the key, a map can be created in the "main" context that contains all of these values. Thus eliminating the iteration each time it is invoked. 

In the case we are looking to implement we would simply allocate the initial span at core context creation. For datadog, this is less important as some of the other injectors which are more frequently called. Other libraries either use a string identifier or export their key structs in order for us to facilitate this already. Some of them also do more complex resolution once inside their context wrapper, which is not the case with datadog. We would just like to standardized this pattern across various libraries we are using if possible. This will more than likely have a negligible performance impact on our application should this be rejected.

We are also hoping that this change will also allow us to track background work more accurately when background worker contexts are created from request contexts (as they are now spawned from the request context). We can then pass the parent span through to the child (or children) it created which will be helpful on some of our fanout requests. Currently this is possible but requires us to pass any context values that `ContextWithSpan` inherited that may not actually be attached to the child context (either they have expired or were re-created).

Please let me know if this better clarifies the initial ask. If not I can work on writing a standalone piece of code to demonstrate this.

**Comment by gbbr** [comment]
Thanks for taking the time to explain, in words, your scenario.

It sounds a bit like all the logic you're planning to introduce around contexts to have faster access might cost more both in terms of CPU and RAM than just leaving it as it is, but I might be missing something. Nevertheless, I'm afraid that we won't be able to take action unless we can describe the problem in code, and bring out actual benchmarks. Would you be willing to spend some time and write the code, here in this issue? We want to see:

1. How you are using this today.
2. How you would be using it if you had the context key.
3. Why one is better than the other, with benchmarks.

It might also be the case that you might not be using `context.Context` optimally or that there is a misunderstanding about its performance. If we can see the code, we can work together and find out.

**Comment by weisbartb** [comment]
Hi Gabriel,

I am going to withdraw this for now and just maintain a fork. The effort to produce what you are asking for is substantially more than just keep a fork that just exports this.

**Comment by gbbr** [comment]
I see. Happy to explore this together if you change your mind later on and find time to narrow it down to some snippets.
