### ISSUE TITLE
Feature request: expose NoopTracer

### ISSUE THREAD

**Issue by skaji** [DataDog/dd-trace-go#567]
## Context

I'm using dd-trace-go in both development and production environments.
While I'm using a "true" tracer in production environment,
I'm using a mocktracer in development environment:

```go
if os.Getenv("ENV") == "production" {
	tracer.Start()
} else {
	mocktracer.Start()
}

// share the same code in both production and development environments
span := tracer.StartSpan("some-resource")
// do something
span.Finish() // actual tracing happens only in production environment
```

Recently I have noticed that the memory usage in development environment was increasing.
This is because mocktracers keep all finished spans in memory.
https://github.com/DataDog/dd-trace-go/blob/1efe3a4d2bf3e760e64ec10a82f54cb4c967b355/ddtrace/mocktracer/mockspan.go#L203

## Feature request

I would like "noop" tracers.
There already exists NoopTracer in the internal package, so how about exposing it?
https://github.com/DataDog/dd-trace-go/blob/1efe3a4d2bf3e760e64ec10a82f54cb4c967b355/ddtrace/internal/globaltracer.go#L44 

Or, it may be better to add an option to mocktracers to disable keeping finished spans.

**Comment by skaji** [comment]
... oh, I just should not have start mocktracers in development environment.

**Comment by gbbr** [comment]
Glad you figured it out. If there is anything we can do better in documentation to make this clearer, please let me know...
