### ISSUE TITLE
ddtrace/mocktracer: mockspan.Finish must be idempotent

### ISSUE THREAD

**Issue by phoenix2x** [DataDog/dd-trace-go#572]
Currently mockspan.Finish is not idempotent while span.Finish is. This prevents us from testing code which invokes Finish multiple times.

**Comment by gbbr** [comment]
I agree that the mocktracer should reflect the behaviour of the tracer. Arguably there should only be one entry in the list of finished spans regardless of the counts to Finish...

I am curious however why you are calling Finish multiple times? It can easily lead to programming errors as code is developer by multiple contributors. Generally the idiom is to factor out instrumented code into its own function and finish in a `defer`. Do you have a use case where this is not possible?
