### ISSUE TITLE
contrib/google.golang.org/grpc: ignore health-check protocol requests from interception

### ISSUE THREAD

**Issue by mathetake** [DataDog/dd-trace-go#576]
With the server interceptor,  currently every request is the target of interception regardless of their services and methods.

[Health-checking-protocol](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) is widely used in grpc. For example, it is used in readinessProbe with [grpc-health-probe](https://github.com/grpc-ecosystem/grpc-health-probe) on k8s.

I would like to prevent the health checking requests from being intercepted and reported to datadog since they are utterly useless. This can be achieved by adding some option like `WithIgnoreHealthChecking`.

If this is acceptable, i am going to work on the patch.

**Comment by gbbr** [comment]
I agree that it would be nice to have a way to ignore those. I am thinking we should have a more generic option though, which would allow ignoring custom endpoints too. Something like:

```go
// WithIgnoredMethods specifies endpoint paths to be ignored. When rx matches the endpoint's method,
// no spans will be created.
func WithIgnoredMethods(rx *regexp.Regexp) Option {
    // ...
}
```
You could then do:
```go
int := grpctrace.StreamClientInterceptor(
    grpctrace.WithServiceName("my-grpc-client"),
    grpctrace.WithIgnoredMethods(regexp.MustCompile("/grpc.health.v1.Health/Check")),
)
```
This should allow people with similar needs to ignore potentially custom health checks.

What do you think?

**Comment by mathetake** [comment]
I agree with your idea to have a more generic option.

But i am not sure it would be better to use regexp when it comes to computational complexity, although golang's regexp package guarantees that all searches run in the liner time of the input which seems reasonably small.

how about having something like:

```golang
// WithIgnoredMethods specifies endpoint paths to be ignored. 
// When an incoming request's endpoint is in es, no spans will be created.
func WithIgnoredMethods(es ...string) Option {
    // ...
}
```

where all the endpoints are supposed to be in a `map[string]struct{}{}` to check whether given method is the target or not in the constant time.

**Comment by gbbr** [comment]
You’re absolutely right. I omitted the fact that a regexp would be expensive on every call. A string is much better. I would be happy with such a change 👍 

Please feel free to open a PR if you wish.

**Comment by mathetake** [comment]
alright, i am going to work on it 👍
