### ISSUE TITLE
opentracer: question about FollowsFrom

### ISSUE THREAD

**Issue by arunpoudel** [DataDog/dd-trace-go#594]
https://github.com/DataDog/dd-trace-go/blob/v2-alpha/ddtrace/opentracer/tracer.go#L50

Here I see that only ChildOfRef is valid as a reference. Do we know why FollowsFromRef is not a valid reference?

**Comment by gbbr** [comment]
Hi Arun!

We do not currently support FollowsFrom at Datadog.

**Comment by arunpoudel** [comment]
Are you going to support it?

**Comment by gbbr** [comment]
We don't have any plans to do so at the moment. I'm going to close this issue as a duplicate of https://github.com/DataDog/dd-trace-go/issues/376. I hope you don't mind. Please feel free to follow that one for updates...
