### ISSUE TITLE
proposal: improve reporting of error type.

### ISSUE THREAD

**Issue by knusbaum** [DataDog/dd-trace-go#612]
Due to the common use of `fmt.Errorf` and `error.New`, the "error.type" that is reported is very often `*errorString`, which doesn't end up being very useful.

We may want to explore options for adding some info to the "error.type", such as the package the error originated in.

**Comment by gbbr** [comment]
Changing this now would be a breaking change. For me, it makes sense that `error.type` displays the error _type_. It is indeed redundant and unnecessary to have it for cases when it is `*errorString`. This is only meant to be useful when that's _not_ the case.

To avoid a breaking change, and if it makes sense, we could additional error metadata. But we should carefully examine whether it makes sense to have a new tag by default, from both performance and usability perspectives…
