### ISSUE TITLE
contrib/gorilla/mux: tracing option to support setting the resource name

### ISSUE THREAD

**Issue by tanordheim** [DataDog/dd-trace-go#618]
Hi,

I'm working on an application where I use a tracer-instrumented Gorilla Mux-handler that uses `PathPrefix` to route all requests to a default handler - which in turn proxies the request to an internal system and relays the response. Something like this:

```go
mux := mux.NewRouter(mux.WithServiceName("my-service"))
mux.PathPrefix("/").HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
  proxyUpstream(w, r)
}))
```

With the current implementation of `contrib/gorilla/mux` this causes all traces from this service to have the resource name `/` which adds very little value to our traces.

The purpose of this application for us is to act as a strangler in front of some legacy systems that - amongst other things - adds some visibility into the traffic hitting those legacy systems via DataDog-instrumentation and the value we get from this is fairly low when we are unable to differentiate between the different types of requests coming in. Adding specific handlers on our router purely for instrumentation purposes like `mux.HandleFunc("/foo/bar/{id}", ...)` (that still calls `proxyUpstream(w, r)`) would be a lot of work and something that's fairly hard to maintain to have parity with the upstream system. In addition, we have no sensitive information being passed around in URLs to these specific systems so we would get huge benefits from the DataDog tracing by simply being able to set the resource names to `r.URL.Path` or something similar.

**Comment by tanordheim** [comment]
I've created a PR for an implementation that lets you pass a resource namer func into the Mux router options in order to override the resource name passed to DataDog - #617.

**Comment by gbbr** [comment]
I see. Thanks for taking the time to explain the use case. This is very helpful to understand why this is needed.

I have to warn you though (might not apply to your case specifically) that using `r.URL.Path` will bring the risk of exposing potentially sensitive information in those paths. That's why we usually use the route pattern instead...

I think your idea and PR should be fine. Please allow me some time to think through whether we can offer a more global way to do this, since it's becoming now repetitive in multiple integrations - as you may have noticed yourself.

**Comment by tanordheim** [comment]
Yeah, we won't _actually_ use `r.URL.Path` but pass it through some internal normalization but that normalization is based off of `r.URL.Path` as an input value :)

**Comment by tanordheim** [comment]
I see it's a feature that is creeping out into different places of the code base but also most of these integrations seems to depend on something very internal to the integration they are providing which are making them hard to generalize I guess.

I don't know the code base very well, but my first gut reaction is:

1. Add support for some generic resource resolver into https://github.com/DataDog/dd-trace-go/blob/v1/contrib/internal/httputil/trace.go#L21 (eg. a `func(*http.Request) string`).
2. Refactor all router integrations and have them support taking in a generic resource resolver - and then pass this resolver + the default/fallback value (eg. mux's matched route pattern) into `httputil.TraceAndServe`.

That would maybe allow all router integrations of providing a generic way of overriding the resource name without each having their own implementation - but it also won't let those custom resource name resolvers access router internals in order to determine those resource names. We wouldn't need that for our usecase, but maybe others would?
