### ISSUE TITLE
Question: How to get current span context?

### ISSUE THREAD

**Issue by gornostal** [DataDog/dd-trace-go#622]
I can't figure out how to get current span so I can get its context.
I'm trying inject it into my carrier to send to another server. Found this example in the [docs](https://godoc.org/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer):
```
req, err := http.NewRequest("GET", "http://example.com", nil)
// ...
err := tracer.Inject(span.Context(), tracer.HTTPHeadersCarrier(req.Header))
``` 

I wish I could see what's behind those `// ...` :)

**Comment by gbbr** [comment]
Hi Aleksandr!

Which span would to like to inject? There is no magical way to get it, you'll have to have a reference to it, if it is a span you've manually created. If it is an integration, it might be that the integration already propagates (injects) the context itself.

Are you using an integration? If so, which one? If not, just use the span you like.

**Comment by gornostal** [comment]
Hi Gabriel
No, I'm not using an integration. I was expecting to see a function `tarce.Span()` or something similar to what dd-trace-js has for retrieving a current span.

> There is no magical way to get it, you'll have to have a reference to it

That answers my question. Thanks!
