### ISSUE TITLE
contrib/gocql/gocql: Update Query.WithContext to work with gocql PR 1228

### ISSUE THREAD

**Issue by ericjster** [DataDog/dd-trace-go#625]
Please update gocql function Query.WithContext to support gocql PR 1228.

The gocql PR 1228 on 25-oct-2018 changed the functionality of its Query.WithContext to make a copy of the Query object and return the new copy. 
https://github.com/gocql/gocql/pull/1228

The current line in Query.WithContext:

	tq.ctx = ctx
	tq.Query.WithContext(ctx)

returns a new Query object and sets the context in the new object, but the original is unaltered.
Therefore clients using gocql on or after 25-oct-2018 cannot set the context. 
A proposed solution is to use the new copied query object:

	tq.ctx = ctx
	tq.Query = tq.Query.WithContext(ctx)

Note that WrapQuery does not propagate the wrapped Query object's context.
The underlying gocql library changed the function names, so if we call Query.Context() it requires clients to use a version of gocql library with that change.

**Comment by gbbr** [comment]
All good, discussed in private and in PR.
