### ISSUE TITLE
contrib/internal/httputil: allow for setting extra tags on the trace

### ISSUE THREAD

**Issue by dialtone** [DataDog/dd-trace-go#631]
The default set of tags is nice but a bit limiting. Just having access to a simple API.

This is a common need as seen here:
https://github.com/DataDog/dd-trace-go/blob/v1/contrib/internal/httputil/trace.go#L68

I can imagine a web layer wanting to add a facet that summarize the response of some APIs as positive and negative beyond the Info/Error response code (for example an API could deny access without necessarily answering with an HTTP error code).

I can imagine a function like:

```golang
func WithOptionSetter(setter func(ddtrace.Span, *http.Request)) RouterOption {
    cfg.optionSetter = setter
}
```

This function would then be called like this:

```golang
trace.WithOptionSetter(func(span ddtrace.Span, r *http.Request) {
    span.SetTag(ext..., getTagValue(r.Context())
})
```

This setup kinda works, the challenge with it is that for the `Context` object would almost always be empty due to the muxtracer being a top level middleware. The ideal would be that this would be called with enough data from context that you could store stuff in it and then populate as many tags as necessary.

**Comment by gbbr** [comment]
This should usually be very easy to do without the option, by doing something like:
```
if span, ok := tracer.SpanFromContext(r.Context()); ok {
    // ... do stuff with span
}
```
Would this not work in your case?

**Comment by dialtone** [comment]
Probably would, for some reason I didn't see this method in the source.

**Comment by gbbr** [comment]
Cool, let me know if not. And if you have any ideas for improving the documentation to see this method more easily, let us know!
