### ISSUE TITLE
proposal: garyburd/redigo allow not to trace some command

### ISSUE THREAD

**Issue by Succo** [DataDog/dd-trace-go#635]
I'd be interested in an option for redigo that would allow some query not to be traced based on the command.

In particular I'd like to not have commands such as PING appear in my apm since they are used as healthchek and skew the latency/counts.

**Comment by gbbr** [comment]
Would you be able to use `ignore_resources` for this in the agent? https://github.com/DataDog/datadog-agent/blob/7.16.0/pkg/config/config_template.yaml#L522-L526. This is what it was meant for.

**Comment by Succo** [comment]
That works, using the env variable I was able to prevent those span.

**Comment by gbbr** [comment]
Glad it helped.
