### ISSUE TITLE
ForeachKey in TextMapReader requires values to be of type string, but not all values are strings

### ISSUE THREAD

**Issue by gornostal** [DataDog/dd-trace-go#638]
I'm working on enabling distributed traces between service in PHP and in Go that communicate via Kafka messages.
With Go I ran into an issue where I get an error when extracting trace info from an incoming message. I get a runtime error because value for `x-datadog-sampling-priority` is of type `number` not `string` but `ForeachKey` [requires it to be a string](https://github.com/DataDog/dd-trace-go/blob/v1.23.1/ddtrace/tracer/textmap.go#L32)

I've found a workaround -- I've implemented `ForeachKey` so it converts everything to strings, but I would expect that either dd-trace-go should allow numbers or dd-trace-php should always send string values.

Any thoughts?

The trace info looks like this:
```
{
    "x-datadog-trace-id": "1667069685082259230",
    "x-datadog-parent-id": "1667069685082259230",
    "x-datadog-sampling-priority": 1,
}
```

In Go i'm using `dd-trace-go` version `1.21.0`, in PHP it's `datadog/dd-trace` version `0.35.0`

**Comment by knusbaum** [comment]
Hi, Alexsandr.

Thanks for filing this issue. Certain carriers, such as the one for HTTP need the data to be in string form, so I would expect these types to stay the same. We should be generous in what we allow for input, though, and convert numbers to strings as necessary.

To help us understand the exact issue, can you share the error you're getting along with the change you made to fix the issue?

**Comment by gornostal** [comment]
Hi @knusbaum 

Here's a workaround that I made to fix the issue:

```
/ DatadogTraceType specifies key-value map of Datadog trace information
type DatadogTraceType map[string]interface{}

// Set implements DatadogTraceType
func (ddt DatadogTraceType) Set(key, val string) {
	ddt[key] = val
}

// ForeachKey implements DatadogTraceType
func (ddt DatadogTraceType) ForeachKey(handler func(key, val string) error) error {
	for k, v := range ddt {
		var value string
		switch t := v.(type) {
		case string:
			value = v.(string)
		case int:
			value = strconv.Itoa(v.(int))
		case float32, float64:
			value = fmt.Sprintf("%.0f", v)
		default:
			log.Warningf("DatadogTraceType: expected type int, bool, or string, but received %T for key %s", t, k)
			continue
		}
		if err := handler(k, value); err != nil {
			return err
		}
	}
	return nil
}
```

As you can see `DatadogTraceType` permits any type of values. I'm creating a structure of this type using `tracer.Extract(tarceInfoThatIReceived)` when I receive a message. 
If I don't convert everything to string like that I receive an error saying that `handler` function expects only strings.
It's difficult for me to reproduce steps now to provide the actual error message, but I hope you see where it comes from.

**Comment by knusbaum** [comment]
`tracer.Extract` ultimately takes a carrier that implements `TextMapReader`. 

We have a number of `TextMapReader` implementations in `dd-trace-go`, but as far as I can tell, all of them correctly handle this case. I don't see where a type error could be occurring in the carriers, but please correct me if I'm missing something.

If the problem you are encountering is in your carrier `DatadogTraceType`, then your solution is correct. It should convert non-string types to strings.

**Comment by gornostal** [comment]
> but as far as I can tell, all of them correctly handle this case

All of them expect only string values, don't they?
The problem I'm having is caused by DD library for PHP that sends numbers in values for some keys.
On which side do you think this issue should be fixed? In `dd-trace-go` or `dd-trace-php`?

**Comment by knusbaum** [comment]
All of them expect only `string` values, but also only iterate over `string` values. I'm not seeing a place where any of them can run into a type error currently.

For example, the `ForeachKey` link you included in the description (https://github.com/DataDog/dd-trace-go/blob/v1.23.1/ddtrace/tracer/textmap.go#L32) iterates over the `HTTPHeadersCarrier`, which is an alias for `http.Header`, which is itself an alias for `map[string][]string`, so iterating over this will always be iteration over strings. All of the other carriers in this repo that I can find have similar properties.

This is why I'm interested in seeing the error you encountered. I'm not sure how the error can happen, so seeing it will help determine what exactly is going wrong and where it is best to fix it.

**Comment by knusbaum** [comment]
@gornostal I'll leave this ticket open for now. Please let me know if you have any more info.

**Comment by knusbaum** [comment]
Closing as stale. Please reopen if you have more info.
