### ISSUE TITLE
contrib/bradfitz/gomemcache: trace the processing keys

### ISSUE THREAD

**Issue by mingrammer** [DataDog/dd-trace-go#640]
Hi.

Currently, the memcached tracer is just creating a span and does not trace anything except `env` tag. So, dashboard shows only `env` variable, and I couldn't find any valuable information such as processing keys.

It would be nice to add the `keys` tag for tracking the used key for each memcached operations. If you agree with this, I can make a PR for this.

**Comment by gbbr** [comment]
Hi @mingrammer!

I'm not sure exactly what you mean here. Can you please try to explain in a different way for me? Maybe post a screenshot of what you're seeing and explain what you're not seeing? Specifically the part where you say:

> does not trace anything except `env` tag. So, dashboard shows only `env` variable

...is unclear to me

**Comment by mingrammer** [comment]
Here are two screenshots, one is for redis, other is for memcached.

## Redis in APM

<img width="889" alt="Screen Shot 2020-04-21 at 7 56 09 PM" src="https://user-images.githubusercontent.com/6178510/79858568-9904f600-840a-11ea-847f-3104e18312a0.png">

It shows various information such as executed command (including used keys), current db and so on.

## Memcached in APM

<img width="893" alt="Screen Shot 2020-04-21 at 7 56 41 PM" src="https://user-images.githubusercontent.com/6178510/79858572-9a362300-840a-11ea-9346-106ce5fc0d60.png">

But the memcached span shows only `env` tag. I want to track keys used in a memcached operation as in the redis span.

**Comment by gbbr** [comment]
Thanks for doing this! That makes complete sense now! I think it should be fine to make this change and add more tags _as long_ as it doesn't reveal any sensitive information!

**Comment by mingrammer** [comment]
Thank you. I’ll send a PR for adding some tags to memcached span.

**Comment by knusbaum** [comment]
Hi, @mingrammer. I have reopened this issue since we had to revert #642. 

We can take another look at this issue and come up with another solution.

**Comment by knusbaum** [comment]
Closing this for now.

Please reopen if we need to revisit this.
