### ISSUE TITLE
contrib/google.golang.org/grpc: trace metadata/request for grpc calls

### ISSUE THREAD

**Issue by mingrammer** [DataDog/dd-trace-go#643]
It would be nice to support tracing the metadata (header for gRPC) and request parameters for gRPC calls. I've already worked for it by building a custom gRPC interceptor, however, I think it would be better if the official package supports this feature.

This is my custom gRPC interceptor tracing the metadata and request parameters.

```go
func UnaryServerInterceptor() grpc.UnaryServerInterceptor {
    return func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
        if span, ok := tracer.SpanFromContext(ctx); ok {
            if md, ok := metadata.FromIncomingContext(ctx); ok {
                for k, v := range md {
                    span.SetTag("grpc.metadata."+k, v)
                }
            }
            m := jsonpb.Marshaler{}
            if p, ok := req.(proto.Message); ok {
                if s, err := m.MarshalToString(p); err == nil {
                    span.SetTag("grpc.request", s)
                }
            }
        }
        resp, err := handler(ctx, req)
        return resp, err
    }
}
```

We can also provide the options can be used to toggle whether trace them or not, like `WithMetadataTags` and `WithRequestTags`.

What do you think about it?

Thank you.

**Comment by gbbr** [comment]
This is very cool. I'm not very familiar with what usually goes into metadata and what the request string looks like, so I'll have to look into it a bit and get back to you.

**Comment by gbbr** [comment]
Ok, let's do this! Please make sure to filter and exclude the metadata added by Datadog context propagation from being added as tags. I think it's `x-datadog-trace-id`, `x-datadog-parent-id` and `x-datadog-sampling-priority`. We should add a test to make sure that this metadata is not added.

**Comment by mingrammer** [comment]
Ok. I'll make a PR for the gRPC request tracer along with a filter for excluding those special tags.
