### ISSUE TITLE
proposal: add host in HTTP tracing

### ISSUE THREAD

**Issue by roopakv** [DataDog/dd-trace-go#646]
We make requests to external services and having the host to which a request is made is helpful, also internally when hitting other service just the URL is not informative enough.

Would like to add Host as an additional tag

**Comment by gbbr** [comment]
Sure! Sounds good to me!

**Comment by xrn** [comment]
@gbbr it could be probably closed :)

**Comment by knusbaum** [comment]
Done. :)

**Comment by tomislater** [comment]
Hey, thanks for doing that! Is there any way to gather this information from metrics? I don't see such option. I want to check the traffic to a specific host/domain, but this is only available from traces, not from metrics 🤔

<img width="900" alt="Screenshot 2022-07-22 at 14 35 03" src="https://user-images.githubusercontent.com/1127164/180440262-e25bb20f-8545-4e94-a0e4-bf612c3f3892.png">
