### ISSUE TITLE
ddtrace/tracer: lost trace due to payload size too large errors

### ISSUE THREAD

**Issue by mingrammer** [DataDog/dd-trace-go#650]
My application throws this error intermittently.

```
2020/05/02 11:30:54 Datadog Tracer v1.20.0 ERROR: lost 1645 traces: payload-too-large
 (Status: Request Entity Too Large), 3 additional messages skipped (first occurrence: 02 May 20 11:2
9 UTC)
...
```

How can I handle this error? Are there any options to adjust the behavior of log flushing?

Thank you.

**Comment by gbbr** [comment]
> How can I handle this error?

Indeed this is an old problem we've been having and have recently started looking into it more 
deeply. I will try to explain the mechanics:

* The Datadog Agent rejects any payloads larger than 10MB with this error.
* The tracer (`dd-trace-go`) buffers complete traces internally and flushes them when [a limit](https://github.com/DataDog/dd-trace-go/blob/3f45f6d1a30653f2616fcb2df7affa978685c887/ddtrace/tracer/tracer.go#L76-L78) is reached. That limit is currently around 4.7MB.

Here is the only scenario I know which can cause this error (numbers are just examples):

1. Some traces finish and the payload size is 4MB. This is safe, we can continue...
2. The next trace finishes and has the size 7MB, which kicks us overboard to 11MB.
3. The agent rejects this.

In this specific scenario a huge trace of 7MB exists. In APM, such a huge trace would need to have hundreds (or thousands) of spans and would technically be useless from an instrumentation and usability point of view, so we generally advise to improve instrumentation to reduce trace size here as we do not have a better solution nor does this provide a good experience. There is almost always a better alternative.

Do you think that you may be creating a ridiculously huge trace somewhere in your application? If so, maybe we can work together to improve that a little bit?

> Are there any options to adjust the behavior of log flushing?

I am not certain that I understand what you mean here. By default, the tracer logs something every minute. You can change this using the environment variable `DD_LOGGING_RATE` which takes a value in seconds. If the value is `0` the tracer will log immediately. It could be a bit disturbing in the general sense but can be useful for debugging.

**Comment by mingrammer** [comment]
I think there is no possibility to create a huge trace in my application 🤔 , However, of course, I'll have to debug my application as well in production to find a root cause for this.

**Comment by gbbr** [comment]
Thanks! If you can confirm that's not the case, then I'd be very interested to discover how this error gets created and have more ideas...

**Comment by mingrammer** [comment]
I turned on the debug option, then these payload sizes were logged. But it is a bit weird. All logging seems were flushed at 2 seconds interval although some payload sizes are larger than [a limit](https://github.com/DataDog/dd-trace-go/blob/3f45f6d1a30653f2616fcb2df7affa978685c887/ddtrace/tracer/tracer.go#L76-L78). 

<img width="1066" alt="Screen Shot 2020-05-07 at 11 36 10 AM" src="https://user-images.githubusercontent.com/6178510/81249759-62f68180-905a-11ea-9a86-a3374c58cec4.png">

I guess size based flushing might be not working properly in this case. And the count of lost traces seen in most logs almost equals to rps of applications (1.7k/s average). (surely, it might be a coincidence)

**Comment by gbbr** [comment]
That limit you've linked to in the constant (`9.5MB`) is intentionally smaller than the actual limit which is [`10MB (10485760 bytes)`](https://github.com/DataDog/datadog-agent/blob/21258fb397db0b495db87f7c775e795fee8fc142/pkg/trace/api/api.go#L48).

We are working in this area actively now. I will keep this issue updated as we progress.

**Comment by mingrammer** [comment]
Thank you!

**Comment by polera** [comment]
I've seen this behavior in the wild as well - is there a branch in progress addressing this?

**Comment by knusbaum** [comment]
@polera
Starting in agent 7.21.0 the max payload is increased in the agent from 10MB to 50MB, which should help. The size is also configurable in the agent via the config `apm_config.max_payload_size` if you want it to accept larger payloads. 
https://github.com/DataDog/datadog-agent/pull/5502

**Comment by andrewsouthard1** [comment]
Hey @polera - were you still experiencing this issue with the latest version of the Datadog Agent? Please feel free to reopen if that is the case.
