### ISSUE TITLE
contrib/gin-gonic/gin: set options of the span created by middleware

### ISSUE THREAD

**Issue by ain-valtin** [DataDog/dd-trace-go#651]
Would be nice if there is a easy way to set common options for all spans created by the middleware. The span can be accessed using `SpanFromContext` but if one wants to add ie common tags for all routes it would be nicer to do it using middleware option. Something like

    func WithStartSpanOptions(cb func(c *gin.Context) []StartSpanOption) Option

which stores the callback to middleware's config and then it is called for each request.

**Comment by gbbr** [comment]
It's not necessary to have a new option to do this. You can simply add more middleware and intercept the span:
```
if span, ok := tracer.SpanFromContext(c.Request.Context()); ok {
    // do stuff with span, like span.SetTag(...)
}
```
Would this not work?

**Comment by ain-valtin** [comment]
Yes, could do it that way too... using middleware option felt nicer but using "middleware handler" is actually more flexible (can add it to only some groups)...

**Comment by gbbr** [comment]
Since this is very easy to add into your own code, using your own custom logic and middleware/handler, I don't see the point of adding it into the library. Is it safe to say that we can close this issue or do you want to discuss it further?

**Comment by ain-valtin** [comment]
I guess it's OK to close it :)
