### ISSUE TITLE
proposal: add additional debug logging to tracer and integrations

### ISSUE THREAD

**Issue by knusbaum** [DataDog/dd-trace-go#653]
Debug logging is useful when diagnosing an issue with an application, and we should consider adding additional information to our logs.

Potentially useful info to include in debug logs:
- [x] complete tracer config on tracer start
- [x] show trace id, span ids, operation name, span tags for each span generated - helps us find out if the tracer generated a specific span
- [ ] log integration configurations when they are successfully attached/started
- [ ] log any integration errors preventing the integration from working (do we want to do this? We already return `error`s when something fails)
- [x] for distributed tracing, have a debug log line if we’ve extracted trace-id.

**Comment by gbbr** [comment]
All of this sounds good to me, except:

> show trace id, span ids, operation name, span tags for each span generated - helps us find out if the tracer generated a specific span

This concerns me a bit, won't it be overkill? In a high throughput system this could be extremely spammy. Do other languages have this too?

**Comment by knusbaum** [comment]
> This concerns me a bit, won't it be overkill? In a high throughput system this could be extremely spammy. Do other languages have this too?

This worries me too, but it looks like the Java, Ruby, .Net, and PHP tracers can all report generated spans:
https://docs.datadoghq.com/tracing/troubleshooting/?tab=php#tracer-debug-logs
Ruby reports spans as they are being written to the send buffer. I'm not sure exactly when the others log them.

That doesn't automatically mean *we* should, but there is precedence.
