### ISSUE TITLE
proposal: add support for richardknop/machinery

### ISSUE THREAD

**Issue by roopakv** [DataDog/dd-trace-go#656]
Would be really cool if we could add support for https://github.com/RichardKnop/machinery

machinery already has support for opentracing, the only thing we have to do is tie it up to DD.

**Comment by gbbr** [comment]
Sure! I think it would be nice to. Feel free to open a PR if you like.

**Comment by gbbr** [comment]
However, I'd prefer it if we would write our own integration, unrelated to Opentracing.

**Comment by roopakv** [comment]
@gbbr I am happy to take a shot at it, would love if you could point me to the best way to test and get started. I feel like there a few approaches that one could take, and I'm not sure I under datadog tracing enough to just go for it.

**Comment by gbbr** [comment]
No worries, we can work on it together. I'll try to provide some guidelines soon.

**Comment by gbbr** [comment]
This looks like a huge project. It will be hard for me to spend the time and figure out a point of integration, but it looks like it has a `tracing` package which uses Opentracing (as you've said yourself). It might be that all we need to do is:

```go
// Start a Datadog tracer, optionally providing a set of options,
// returning an opentracing.Tracer which wraps it.
t := opentracer.New(tracer.WithService("my-service"), ...)
defer tracer.Stop() // important for data integrity (flushes any leftovers)

opentracing.SetGlobalTracer(t)
```

This might work, in which case we don't need an integration. Check out the https://godoc.org/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/opentracer package.

**Comment by knusbaum** [comment]
Closing this as stale without marking it rejected. This is not something there's a lot of interest in doing right now, but we may revisit it at a later date.
