### ISSUE TITLE
internal/globalconfig: wrong mutex type acquired for SetServiceName

### ISSUE THREAD

**Issue by vikpattabi** [DataDog/dd-trace-go#658]
https://github.com/DataDog/dd-trace-go/blob/435545bd358b5032d8e6e66cf1cab16c6a712a4c/internal/globalconfig/globalconfig.go#L50

I would expect the `SetServiceName` function should acquire a write mutex in the above line.  Happy to submit a PR for this if this seems reasonable.

**Comment by gbbr** [comment]
You're right, thanks for catching this!

**Comment by vikpattabi** [comment]
Yup, absolutely! Looks like I might need some permission to put up a PR to fix?

**Comment by gbbr** [comment]
No permissions needed, just fork the repository and open a PR.

**Comment by vikpattabi** [comment]
PR here: https://github.com/DataDog/dd-trace-go/pull/659

**Comment by knusbaum** [comment]
This is fixed in `1.24.0-rc.4` and `1.23.3`
