### ISSUE TITLE
opentracer: not working with contrib

### ISSUE THREAD

**Issue by sheshnathmishra** [DataDog/dd-trace-go#662]
We are facing an issue similar to [this](https://github.com/DataDog/dd-trace-py/issues/1153) where `tracer.StartSpanFromContext` return a new root span even if the context has active opentracing span. The function `ctx.Value(activeSpanKey)` returns `nil` if the active span is opentracing span as a result the parent-child association is getting lost.

**Library version**
dd-trace-go.v1 v1.18.0

**Context:**
We are using Opentracing API's for tracing. We are in process of enabling APM for our Database. Our SQLx library is [jmorion/sqlx](gopkg.in/DataDog/dd-trace-go.v1/contrib/jmoiron/sqlx). Datadog supports tracing for this library. The library uses Datadog tracer, by default. 

Our current application generate Opentracing Span. Starting new Span for Database tracing using the [Datadog jmoiron/sqlx](https://godoc.org/gopkg.in/DataDog/dd-trace-go.v1/contrib/jmoiron/sqlx) results in a completely new root span.

Thanks!

**Comment by gbbr** [comment]
The integrations in the `contrib` folder are designed to work exclusively in conjunction with the `ddtrace/tracer` package. It is not possible to use any of the two interchangeably with the Opentracing tracer. They are two different systems.

Opentracing has their set of dedicated integrations at over https://github.com/opentracing-contrib/. Using the `opentracer` package will give you access to these with Datadog.

**Comment by sheshnathmishra** [comment]
Thanks @gbbr that was helpful.

Also, adding couple of solutions, we evaluated:
a.  [inkbe/opentracing-sql](https://github.com/inkbe/opentracing-sql) is wrapper around database/sql and allows to pass tracer. This is compatible to opentracing. 

b. Converting existing opentracing span by extracting the spancontext and recreating datadog span.

c. Our own custom wrapper, which allows much more flexibility like adding customs tags.
