### ISSUE TITLE
proposal: add helper to get context attached to gorm db

### ISSUE THREAD

**Issue by zhammer** [DataDog/dd-trace-go#666]
i'd like to add a publicly-accessible function that can return the context that ddtrace has attached to a gorm db. it would be the getter-equivalent of [WithContext](https://github.com/DataDog/dd-trace-go/blob/0543fdceec376b43b23031afc121db1bfc037458/contrib/jinzhu/gorm/gorm.go#L73-L82).

this is needed to get the context dd-trace-go has attached to a gorm db in db hooks. simplified example:
```go
// hook
func (m *MyModel) AfterCreate(db *gorm.DB) error {
	ctx := gormtrace.ContextFromDB(db)
        // ...
}

// somewhere else in code
model := &MyModel{}
db := ddtracegorm.WithContext(ctx, db)
db.Create(model)
```

---

logic already exists [here](https://github.com/DataDog/dd-trace-go/blob/0543fdceec376b43b23031afc121db1bfc037458/contrib/jinzhu/gorm/gorm.go#L89-L93). function could look something like:
```go
func ContextFromDB(db *gorm.DB) (context.Context, bool) {
	v, ok := db.Get(gormContextKey)
	if !ok {
		return nil, false
	}
	ctx, ok := v.(context.Context)
	return ctx, ok
}
```

**Comment by gbbr** [comment]
I think something like that makes sense to have, but let's use the same style [as the standard library](https://golang.org/pkg/net/http/#Request.Context) and have this instead:
```go
func (db *gorm.DB) Context() context.Context {
    if v, ok := db.Get(gormContextKey); ok {
        if ctx, ok := v.(context.Context); ok {
            return ctx
        }
    }
    return context.Background()
}
```

**Comment by zhammer** [comment]
@gbbr works for me! need help with a PR or will you put this up?

**Comment by gbbr** [comment]
We could definitely use help with a PR, we won't be able to do it soon otherwise... Feel free to!

**Comment by zhammer** [comment]
PR #667
