### ISSUE TITLE
ddtrace/tracer: WithGlobalTag does not apply to runtime metrics

### ISSUE THREAD

**Issue by DarrenTsung** [DataDog/dd-trace-go#671]
I'm using the tracer library for spans as well as reporting the standard runtime metrics for a Go application, and I thought that `tracer.WithGlobalTag("foo", "bar")` would apply to runtime metrics, but it does not.

It appears that runtime metrics only get the tags defined here:
https://github.com/DataDog/dd-trace-go/blob/66397230038c0b79d932452eba484879c6a40705/ddtrace/tracer/option.go#L138

And that spans specifically get the global tags added to them here:
https://github.com/DataDog/dd-trace-go/blob/66397230038c0b79d932452eba484879c6a40705/ddtrace/tracer/tracer.go#L321

Thanks!

**Comment by gbbr** [comment]
I guess we could add them in there too, I don't see any reason not to. PRs are welcome :)

**Comment by DarrenTsung** [comment]
@gbbr I opened at PR with #673 - seems like it needs a milestone attached to it before the checks run though.
