### ISSUE TITLE
Add support for go-pg integration

### ISSUE THREAD

**Issue by patriczek** [DataDog/dd-trace-go#681]
Hi,  i would like to add new integration for go-pg orm.

https://github.com/go-pg/pg

**Comment by gbbr** [comment]
Hi 👋 Thanks for the offer. I don't see why not! Before starting work, can we go over how we will approach the implementation here? Does this library provide any hooks for tracing?

**Comment by patriczek** [comment]
Hi, 
yes ofc they provide hooks, i have some preview here:
https://github.com/patriczek/dd-trace-go/commit/11a3cc4dd501ecbfe1d39af674fafe54cf64ed1e

**Comment by gbbr** [comment]
I see! Thanks for sharing that! That's no problem at all. The approach looks good to me. You can open a PR if you like. However, I'd leave `Wrap` out of it. Providing only the `Hook` should be enough.

**Comment by patriczek** [comment]
Sorry for delay, can you please check my MR: #686. Probably there must be some changes.

**Comment by gbbr** [comment]
Yup. But please have a green CI.

**Comment by patriczek** [comment]
I don't see which errors are in CI
