### ISSUE TITLE
contrib/jinzhu/gorm: support v2

### ISSUE THREAD

**Issue by jareklupinski** [DataDog/dd-trace-go#684]
The existing GORM module I am using, https://github.com/jinzhu/gorm, will be V2'd under https://github.com/go-gorm/gorm

I am testing a DataDog-enhanced repo for upgradeability to GORM V2, and would like to know if an adapter for the new GORM is in the works? Looking forward to it :) Thanks!

**Comment by gbbr** [comment]
Hi, not in the works, but welcome at `contrib/go-gorm/gorm`.
