### ISSUE TITLE
Injected X-B3-Traceid header may be less then 16 characters long

### ISSUE THREAD

**Issue by sullerandras** [DataDog/dd-trace-go#695]
It seems like the `injectTextMap` function does not add leading zeroes to the traceid when it's emitted in hexadecimal:
https://github.com/DataDog/dd-trace-go/blob/9495abe376f6c458ce6f5c5620d3b1ef17e65d25/ddtrace/tracer/textmap.go#L309-L310

This causes issues in our Ruby app because that assumes the Traceid header will be at least 16 chars long:
https://github.com/twitter/finagle/blob/d2e7485782faeada129d43d7511167c31811df81/finagle-thrift/src/main/ruby/lib/finagle-thrift/trace.rb#L103

Would it be possible to format the traceid in the injected headers to be exactly 16 chars long? E.g. something like `fmt.Sprintf("%016x", ctx.traceID)`

**Comment by knusbaum** [comment]
I don't think that adding this would be a problem.

It's not made crystal-clear, but I think the [B3 specification](https://github.com/openzipkin/b3-propagation#traceid-1) says that these headers should be 16 (or possibly 32 for traceid) characters anyway, so I think we should change this.
