### ISSUE TITLE
proposal: contrib/Shopify/sarama: support sarama.ConsumerGroup

### ISSUE THREAD

**Issue by mingrammer** [DataDog/dd-trace-go#699]
We are using `sarama.ConsumerGroup` of `Shopify/sarama` package, but there are only for `Consumer` and `PartitionConsumer`.

It would be good if the `ConsumerGroup` wrapper also is supported.

Thank you.

**Comment by gbbr** [comment]
Is it easy to add? Would you be interested in doing the work?

**Comment by mingrammer** [comment]
Yap. I'll try to implement it!

**Comment by adw1n** [comment]
It's a duplicate of https://github.com/DataDog/dd-trace-go/issues/552

**Comment by knusbaum** [comment]
Thanks, @adw1n.
Closing this as a duplicate of #552 

@mingrammer we can continue on that ticket.
