### ISSUE TITLE
question: best way to test pre-release versions?

### ISSUE THREAD

**Issue by ryanschneider** [DataDog/dd-trace-go#703]
I'm interested in testing my code w/ the 1.26.0-rc2 prerelease, but haven't figured out the correct way to get that to work in my `go.mod` since the prerelease versions are not available at `gopkg.in`.  

I tried using a replace directive like:

```
replace gopkg.in/DataDog/dd-trace-go.v1 v1.25.0 => github.com/DataDog/dd-trace-go v1.26.0-rc2
```

But that generates the error:

> `go: gopkg.in/DataDog/dd-trace-go.v1@v1.25.0: reading github.com/DataDog/dd-trace-go/go.mod at revision v1.26.0-rc2: unknown revision v1.26.0-rc2`

Is there an easy way to point to prerelease versions w/o changing all my imports to github.com instead of gopkg.in?

Thanks!

**Comment by knusbaum** [comment]
Release candidates should work from gopkg.in without trouble. 

I think the trouble you are having is due to your tag. The tag for the second release candidate for 1.26 is `v1.26.0-rc.2` rather than `v1.26.0-rc2`.

**Comment by ryanschneider** [comment]
I see, the correct syntax is:

> `go get gopkg.in/DataDog/dd-trace-go.v1/...@v1.26.0-rc.2`

I originally tried it without the `/...` and got:

```
$ go get gopkg.in/DataDog/dd-trace-go.v1@v1.26.0-rc.2
go get gopkg.in/DataDog/dd-trace-go.v1@v1.26.0-rc.2: no Go source files
```
