### ISSUE TITLE
Module path in go.mod seems to be incorrect

### ISSUE THREAD

**Issue by vatine** [DataDog/dd-trace-go#704]
Trying to download github.com/DataDog/dd-trace-go v1.25.0 fails with an error message indicating a skew between the path used to grab it and the name declared in the go.mod file. Example output:

```
$ go mod download github.com/DataDog/dd-trace-go@v1.25.0
go: github.com/DataDog/dd-trace-go@v1.25.0: parsing go.mod:
	module declares its path as: gopkg.in/DataDog/dd-trace-go.v1
	        but was required as: github.com/DataDog/dd-trace-go
```

The same error is seen with a `go get` rather than a `go mod download`.

Fixing this should be as easy as dropping the `.v1` off the name in the go.mod file.

**Comment by gbbr** [comment]
The canonical path for this repository is `gopkg.in/DataDog/dd-trace-go.v1` not `github.com/DataDog/dd-trace-go@v1.25.0`, as described in our [installation notes](https://github.com/DataDog/dd-trace-go#installing). I'm closing it, but feel free to re-open or comment if you feel that there is more to discuss.

**Comment by vatine** [comment]
With Go 1.14, trying to do a `go get github.com/DataDog/dd-trace-go.v1@v1.25.0` fails with `go get github.com/DataDog/dd-trace-go.v1@v1.25.0: github.com/DataDog/dd-trace-go.v1@v1.25.0: invalid version: unknown revision v1.25.0` and simply  dropping the version number gives:
```
$ go get github.com/DataDog/dd-trace-go.v1       
go get github.com/DataDog/dd-trace-go.v1: module github.com/DataDog/dd-trace-go.v1: git ls-remote -q origin in /go/pkg/mod/cache/vcs/96ac2e56e9a62a72af576fac4aa7b7b5b0b06cad49f7461598a5d6e02935e362: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
```

These tests have been done from inside the `golang:1.14-buster` docker image,

**Comment by gbbr** [comment]
Why are you using the github path again? The correct command is:
```
$ go get gopkg.in/DataDog/dd-trace-go.v1/...@v1.25.0
```
Or, you can selectively get less packages if you don't need all of them.
