### ISSUE TITLE
Opentracing example is incorrect

### ISSUE THREAD

**Issue by goodspark** [DataDog/dd-trace-go#708]
https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/ddtrace?tab=doc#example-package-Opentracing

```go
t := opentracer.New(tracer.WithAgentAddr("host:port"))
defer tracer.Stop()

opentracing.SetGlobalTracer(t)
```

The tracer object returned by `opentracer.New` does not have a `Stop` function.

**Comment by gbbr** [comment]
> The tracer object returned by opentracer.New does not have a Stop function.

True, but in the example, that's `t`, and `Stop` is called on `tracer`, not on `t`, which exists in the `tracer` package: https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer?tab=doc#Stop
