### ISSUE TITLE
contrib/jinzhu/gorm: package import is broken and not backward compatible

### ISSUE THREAD

**Issue by patronmike** [DataDog/dd-trace-go#712]
`github.com/jinzhu/gorm` was moved and all go files in the default branch were deleted, so `go get github.com/jinzhu/gorm` fails.  The package import should be updated to `gopkg.in/jinzhu/gorm.v1` to be able to still use the old package.

Edit: I have a PR ready.

**Comment by gbbr** [comment]
Thanks! Please feel free to do that. We will have to keep both paths though.
