### ISSUE TITLE
proposal: Support github.com/go-gorm/gorm

### ISSUE THREAD

**Issue by knusbaum** [DataDog/dd-trace-go#714]
The `github.com/jinzhu/gorm` package has moved to `github.com/go-gorm/gorm` for v2.
We should look at support for that.

Related to #712

**Comment by mingrammer** [comment]
Gorm v2 uses its own dialector interface which opens the `sql.DB` internally. So I think we should wrap or implement the gorm's new dialector interface. 

[This](https://github.com/go-gorm/postgres) is an official dialector implementation for PostgreSQL.

```go
func (dialector Dialector) Initialize(db *gorm.DB) (err error) {
	// register callbacks
	callbacks.RegisterDefaultCallbacks(db, &callbacks.Config{
		WithReturning: true,
	})

	if dialector.Conn != nil {
		db.ConnPool = dialector.Conn
	} else if dialector.DriverName != "" {
		db.ConnPool, err = sql.Open(dialector.DriverName, dialector.Config.DSN)
	} else {
		var config *pgx.ConnConfig

		config, err = pgx.ParseConfig(dialector.Config.DSN)
		if err != nil {
			return
		}
		if dialector.Config.PreferSimpleProtocol {
			config.PreferSimpleProtocol = true
		}
		result := regexp.MustCompile("(time_zone|TimeZone)=(.*)($|&| )").FindStringSubmatch(dialector.Config.DSN)
		if len(result) > 2 {
			config.RuntimeParams["timezone"] = result[2]
		}
		db.ConnPool = stdlib.OpenDB(*config)
	}
	return
}
```

**Comment by knusbaum** [comment]
@mingrammer I think implementing a [`Plugin`](https://pkg.go.dev/gorm.io/gorm?tab=doc#Plugin) would allow us to use the `Callback()` api to instrument gorm v2 the same way we do v1. Then to instrument a gorm db, you would just do something like
```
db.Use(gormtrace.Plugin())
```

Would implementing the`Dialector` interface allow us to trace the library better, or is a `Plugin` sufficient?

**Comment by mingrammer** [comment]
I think both ways are good options to achieve tracing purposes. But using `Plugin` and `Callback` could be a more general and extendible approach than implementing dialectors for all kinds of drivers.

**Comment by knusbaum** [comment]
I think we should go with the `Plugin` approach for now. It should let us mostly reuse the existing gorm integration, meaning the v2 integration should be mostly the same as v1.

We may even be able to reuse the code in v1 directly rather that copy/pasting it, although I haven't looked into that.

**Comment by knusbaum** [comment]
Done!
