### ISSUE TITLE
proposal: contrib/jinzhu/gorm: Add custom tags.

### ISSUE THREAD

**Issue by cube2222** [DataDog/dd-trace-go#716]
Currently the gorm tracer only adds the query to the trace. It'd be very useful to have other tags like rows affected or the SQL query variable values used.

However, I suppose anything useful in this regard can be modelled as a function on *gorm.Scope which is available to the Callback. So I'd propose a new option, WithCustomTag, which receives a tag name, as well as a function which evaluates to the value for this tag based on the given gorm.Scope.

I went ahead and implemented it for our internal use already: https://github.com/spacelift-io/dd-trace-go/commit/c12cc11cb0aa9f5e4e8b7607e6466e4f7d6ccdbf

I'd love if we could get this, or a variation thereof, upstreamed.

**Comment by gbbr** [comment]
I think this sounds like a great feature! Feel free to go ahead and add it! Thanks!
