### ISSUE TITLE
contrib/go-redis/redis: Support tracing of client.Pipelined and client.TxPipelined

### ISSUE THREAD

**Issue by JDiPierro** [DataDog/dd-trace-go#720]
I'm using the `TxPipelined(fn func(Pipeliner) error) ([]Cmder, error) ` function of `go-redis` but not receiving traces for any of the calls made through the pipeline. 

I was able to get these calls traced by adding the following code to the `contrib/go-redis/redis/redis.go` file:

```
func (c *Client) Pipelined(fn func(redis.Pipeliner) error) ([]redis.Cmder, error) {
	return c.Pipeline().Pipelined(fn)
}

func (c *Client) TxPipelined(fn func(redis.Pipeliner) error) ([]redis.Cmder, error) {
	return c.TxPipeline().Pipelined(fn)
}

func (c *Client) TxPipeline() redis.Pipeliner {
	return &Pipeliner{c.Client.TxPipeline(), c.params, c.Client.Context()}
}

func (c *Pipeliner) Pipelined(fn func(redis.Pipeliner) error) ([]redis.Cmder, error) {
	if err := fn(c); err != nil {
		return nil, err
	}
	cmds, err := c.Exec()
	_ = c.Close()
	return cmds, err
}
```

If that looks good I'd be happy to write a test and open a PR for it :)

**Comment by gbbr** [comment]
Looks good to me! Please go ahead! And sorry for the late response.
