### ISSUE TITLE
contrib/twitchtv/twirp: ServerHooks incompatible with twirp.ChainHooks

### ISSUE THREAD

**Issue by mickeyreiss** [DataDog/dd-trace-go#725]
It seems that the twirp ServerHooks returned by `twirp.NewServerHooks` is incompatible with `twirp.ChainHooks` when another hook that runs after this one starts a new span.

This means that `tracer.SpanFromContext` returns a different span in `responseSentHook` than the one that was started in `requestRoutedHook`. This results in a span that leaks without ever finishing because the wrong span is `.Finish()`ed on line 205:

https://github.com/DataDog/dd-trace-go/blob/498a4553f2152eccca152064c4929332a66b98f3/contrib/twitchtv/twirp/twirp.go#L195-L207

This could be addressed fixed by explicitly retaining a reference to the request span, rather than relying on the global span (`tracer.SpanFromContext`) in `responseSentHook`.

cc/ @cgilmour @gbbr

**Comment by gbbr** [comment]
@cgilmour would you mind taking a look?
