### ISSUE TITLE
contrib/net/http: Handler sends stack trace even if http.NoDebugStack is passed

### ISSUE THREAD

**Issue by StefanoVarotti** [DataDog/dd-trace-go#744]
Wrapping a http.Handler or using ServeMux with the `http.NoStackTrace` option does not disable stack traces on http requests that failed.
This is due to the httputil.ResponseWriter wrapper calling SetTag directly instead of sending the error through `span.Finish`.
IMO the handler wrapper [should send the error using `span.Finish`](https://github.com/DataDog/dd-trace-go/compare/v1...StefanoVarotti:fix-http-error-stacktrace)
Another option would be refactor Span to use supplied options when calling SetTag.

**Comment by knusbaum** [comment]
@StefanoVarotti Which option are you trying to use to disable stack traces? 
Please have a look at #809 and see if this will fix the issue.

This will work with [`tracer.WithDebugStack(bool)`](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer#WithDebugStack). If that is not sufficient, we could potentially add another `StartSpanOption`.

**Comment by gbbr** [comment]
@StefanoVarotti since you've not responded in a while, I'm going to go ahead and close this issue and assume that this isn't longer an issue for you. If that assumption is false, please feel free to re-open or leave another message and we're happy to look into it for you.
