### ISSUE TITLE
Tag v1.27.0 as a release

### ISSUE THREAD

**Issue by xrn** [DataDog/dd-trace-go#750]
Hi,

Via tags, I see that we have new version v1.27.0 - https://github.com/DataDog/dd-trace-go/releases/tag/v1.27.0 also milestone is closed https://github.com/DataDog/dd-trace-go/milestone/48 but it is not visible on releases dashboard https://github.com/DataDog/dd-trace-go/releases

**Comment by knusbaum** [comment]
Hi, @xrn.
We were just finalizing the release notes.
It should be available now under releases here: https://github.com/DataDog/dd-trace-go/releases/tag/v1.27.0
