### ISSUE TITLE
proposal: contrib/cloud.google.com/go/pubsub should support custom service names

### ISSUE THREAD

**Issue by mickeyreiss** [DataDog/dd-trace-go#752]
It is useful to be able to configure span options, such as a default service name, but `pubsubtrace.WrapReceiveHandler` does not allow this override.

In particular, this signature:

```go
func WrapReceiveHandler(s *pubsub.Subscription, f func(context.Context, *pubsub.Message)) func(context.Context, *pubsub.Message)
```

doesn't allow one to set the service name.

Maybe it should be something like this:

```go
func WrapReceiveHandler(s *pubsub.Subscription, f func(context.Context, *pubsub.Message), , opts ...ReceiveOption) func(context.Context, *pubsub.Message)
```

Here's sql trace, for comparison, which does allow overrides via the third parameter on:

```go
func Register(driverName string, driver driver.Driver, opts ...RegisterOption)
```

**Comment by knusbaum** [comment]
Enabling users to specify things like the service name is ideal.

I think 'WrapReceiveHandler` could just take a variadic list of [StartSpanOption](https://godoc.org/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer#StartSpanOption), and we can add those to a list of the existing options.

We *do* want to maintain backwards-compatibility, so we should give this function a new name, and have `WrapReceiveHandler` call the new function with no additional arguments.
