### ISSUE TITLE
proposal: database/sql: should trace also the time spent connecting

### ISSUE THREAD

**Issue by CAFxX** [DataDog/dd-trace-go#760]
It seems like currently the database/sql tracing [does not create a span for time spent establishing connections to the database](https://github.com/DataDog/dd-trace-go/blob/54b73b3e126a7489ed774c98aadd301488e44123/contrib/database/sql/sql.go#L108-L147), and this time is not included in the time reported in query spans.

This can lead to confusion, as establishing a connection can be surprisingly expensive depending, among other things, on latency, authentication scheme and transport security.

Note that this is done already in the datadog libraries for PHP, that e.g. separately traces calls to PDO.__construct (that is responsible for opening a database connection). Moreover, where in PHP it's quite likely that all requests will open a connection to the database as there's no connection pool by default, in Go by default database/sql internally implements a connection pool and therefore most connections will not incur the cost of opening a connection, and only a few will do. Being able to tell these two cases apart is pretty important.

In decreasing order of preference, the database/sql integration should:

1. create a child span representing the connection opening of the query span when a query requires to create a new connection
2. create a peer span when a query requires to create a new connection
3. include the connection time in the query span

To hopefully clarify, if this is the current situation:

```
...----------------------... parent span
            |----------|     query span (connection open is not traced)

      ^^^^^^ connection open happens here
```

The 3 cases above would be:

```
(1 - ideal)
...----------------------... parent span
     |-----------------|     query span
     |-----|                 connection open span

(2 - like PHP tracing)
...----------------------... parent span
     |-----||----------|     connection open span, query span
 
(3 - less favorite)
...----------------------... parent span
     |-----------------|     query span including connection open time
 
```

**Comment by gbbr** [comment]
Hi Carlo!

I think this is nice to have. I also think we should align ourselves with our other tracers, likely going for option number 2, which makes most sense to me. Would you be interested in doing this change?

**Comment by CAFxX** [comment]
Hard for me to commit right away. This will stay on my radar, but I'm not sure when I will be able to get to work on it, so if anybody is interested or has the spare cycles... please go right ahead.
