### ISSUE TITLE
Support opentelemetry tracing APIs

### ISSUE THREAD

**Issue by HowJMay** [DataDog/dd-trace-go#765]
Now Datadog dd-trace-go lacks support of [Opentelemetry](https://github.com/open-telemetry/opentelemetry-go) tracing APIs. This is such a critical issue, since both Opencencus and Opentracing are merged into Opentelemetry. A lack of such tracing API supporting, it would be such a barrier for golang projects which need to conduct tracing.

Is there a way to connect to Datadog with Openetelemetry at this moment?

**Comment by mhamrah** [comment]
Upvote

**Comment by andrewsouthard1** [comment]
Hey all! We currently have support for the Opentelemetry Collector today: https://docs.datadoghq.com/tracing/setup_overview/open_standards/#opentelemetry-collector-datadog-exporter. 

If you are using the Collector, you can send traces to Datadog. The Collector today however can only receive traces from OTel SDKs. 

If you are not using the Collector, we are evaluating support next quarter for using `dd-trace-go` and OTel SDKs, similar to one of our [language exporters](https://docs.datadoghq.com/tracing/setup_overview/open_standards/#opentelemetry-collector-datadog-exporter) built for Ruby, Node, or Python, or expanding our Collector Exporter to ingest tracing from `dd-trace-go`.

**Comment by mhamrah** [comment]
Either of those would be great. I was able to get k8sprocessor to tag trace
data with Kubernetes info, however, I can’t figure out container Id
handling to see container metrics in system view of APM.

**Comment by knusbaum** [comment]
Closing as rejected. 

Datadog supports OTel today through our OTel exporter and collectors. Please feel free to open a new proposal if there's something specific dd-trace-go can improve with respect to OTel.
