### ISSUE TITLE
contrib/gin-gonic/gin: support globalconfig.ServiceName()

### ISSUE THREAD

**Issue by marcind** [DataDog/dd-trace-go#767]
Right now the gin trace middleware requires passing in a service name and it does not reference `globalconfig.ServiceName()`. Consider adding support for using the value of `globalconfig.ServiceName()` if the serviceName value passed into the middleware factory function is `""`. This will allow callers to opt into using the global service name without requiring a new overload to the middleware factory.

I can send a PR if this is something worth considering.

Also, consider changing the middleware factory signature and behavior to match that of other server tracer wrappers for a potential `v2`.

**Comment by gbbr** [comment]
I'd be happy if you were to open a PR for this. And yes, I agree with you that the signature of `Middleware` could be better.
