### ISSUE TITLE
Propagate HTTP Server Trace to HTTP Client Trace *Without* Cancellation

### ISSUE THREAD

**Issue by SamProtas** [DataDog/dd-trace-go#774]
We have a use case with an HTTP server that occasionally issues "fire and forget" HTTP requests to another service.

We'd like to attach these traces for visibility into the system, but we purposely do _not_ want to link the lifetime/deadline of the inbound HTTP Request handler to the outbound HTTP request due to latency concerns.

My understanding of the context API seems to indicate there's no way to "unlink" a context from its parent's cancellation/deadline. My understanding of this library's API is there's no way to propagate a trace other than via the context.

Is there some way to accomplish this task?

For reference, we have several services written in nodejs using dd-trace-js that do this (trace "fire and forget" requests that outlive the server handler's lifetime).

**Comment by knusbaum** [comment]
It's true that we use go's context package to propagate traces. If you want to "unlink" everything from the downstream http call except the trace, you could simply attach the active span to a new `context.Background()` like so:
```
func Handle(w ResponseWriter, r *Request){
	// Start handling request
	// ...
	// Time for "fire and forget"
	span, _ := tracer.SpanFromContext(r.Context())
	newCtx := tracer.ContextWithSpan(context.Background(), span)
	fire_and_forget(newCtx)
	// Continue handling the request
}
```
If I understand your case correctly, I think this will do what you want. The `newCtx` deadline, etc will be totally disassociated from the original `Request`'s, but the trace will propagate to the `fire_and_forget` request through the new context.

**Comment by SamProtas** [comment]
This looks like exactly what I needed. Thank you!

**Comment by knusbaum** [comment]
Fantastic, I'll close this then. Feel free to reopen if needed.
