### ISSUE TITLE
Support for extracting b3 propagation trace id with 128 bits

### ISSUE THREAD

**Issue by stroem** [DataDog/dd-trace-go#779]
When I try to extract a b3 tracing id of len 32 (128 bits) it fails to parse it.
https://github.com/DataDog/dd-trace-go/blob/a2e9dddb51db578b503d570ce3127d18b8fb93ce/ddtrace/tracer/textmap.go#L337

Reading the specification for the headers it states that the X-B3-TraceId header is encoded as 32 or 16 lower-hex characters.
https://github.com/openzipkin/b3-propagation#identifiers

Would be nice if you can support b3 tracing id with 128 bits

**Comment by knusbaum** [comment]
Related to #695

**Comment by gbbr** [comment]
I guess we can close now.

**Comment by stroem** [comment]
Added support for B3 extract for dd-lambda-wrapper: https://github.com/DataDog/datadog-lambda-go/issues/50
(@gbbr, would you like to take a look at it?)
