### ISSUE TITLE
proposal: make DD_TAGS space separated

### ISSUE THREAD

**Issue by alainstoffels** [DataDog/dd-trace-go#783]
We have a AWS ECS cluster which runs the Datadog agent and our services which are monitored with Datadog. We're using the `DD_TAGS` environment variable to set a couple of tags. We want these tags on the infrastructure hosts (which are set by the agent) and on all of our traces (which are set by this dd-trace-go package).

[The agent requires these tags to be space separated](https://docs.datadoghq.com/agent/docker/?tab=standard#global-options) but [dd-trace-go requires them to be comma separated](https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/tracer/option.go#L140). I suggest making this consistent and thus making `DD_TAGS` space separated.

In our case it's quite cumbersome to pass a different `DD_TAGS` value to different containers within ECS so we would just like to use the same `DD_TAGS` variable across all our containers.

Removing comma separation would be a breaking change so it would probably be wise to keep supporting that and split both on commas and spaces

**Comment by knusbaum** [comment]
We have this in our work queue.

**Comment by katiehockman** [comment]
@knusbaum the PR for this was closed, so should we mark this proposal as rejected, or do you still feel it's worth doing?

**Comment by knusbaum** [comment]
Completed in #837
