### ISSUE TITLE
proposal: Add finalizer to help debug spans left open

### ISSUE THREAD

**Issue by ryanschneider** [DataDog/dd-trace-go#785]
I've been debugging an app that seems to have a leak because one or more spans aren't being closed, I think it'd help debugging if Span had an debug option to use https://golang.org/pkg/runtime/#SetFinalizer to set a finalizer that reports the stack trace for any spans that are left open.

For example go-cloud uses this to warn about forgetting to call `.Close` on a blob: https://github.com/google/go-cloud/blob/613a96d7995b2ddd0edc273655180e93678bee33/blob/blob.go#L829

**Comment by gbbr** [comment]
While that would be interesting, I'm afraid we don't want to do that because even though I see the small benefit in your specific scenario, finalizers are not something we want to start adding into the code. 

From https://golang.org/pkg/runtime/#SetFinalizer:

> The finalizer is scheduled to run at some arbitrary time after the program can no longer reach the object to which obj points. There is no guarantee that finalizers will run before a program exits, so typically they are useful only for releasing non-memory resources associated with an object during a long-running program [...]

I also recommend reading https://crawshaw.io/blog/tragedy-of-finalizers

**Comment by ryanschneider** [comment]
It's a large code base and the leak has only happened once in the last year. Basically what I'm proposing is what he proposes as the one good use of finalizers in his follow-up blog post: https://crawshaw.io/blog/sharp-edged-finalizers

(Though of course I would argue a panic is way too severe for a package.) But yes we can add the finalizer locally, I'll take a stab at it next week time permitting.

**Comment by gbbr** [comment]
Thanks for understanding. If you wish, feel free to share how that investigation goes, perhaps we can make use of it in the future when similar situations arise...

**Comment by knusbaum** [comment]
Closing after rejection. Feel free to reopen if we need to revisit this topic.
