### ISSUE TITLE
contrib/gorilla/mux: skip tracing for some requests

### ISSUE THREAD

**Issue by stroem** [DataDog/dd-trace-go#790]
Would be nice to skip creating spans for some of the requests.
Like e.g health-endpoints. 

ochttp solves it this way (https://github.com/census-instrumentation/opencensus-go/blob/master/plugin/ochttp/server.go#L74):
```go
svr = &http.Server{
    Addr: ":8080",
    Handler: &ochttp.Handler{
	    Handler:          s.mux,
	    IsPublicEndpoint: true,
	    IsHealthEndpoint: func(req *http.Request) bool {
		    switch req.URL.Path {
		    case "/health", "/health/":
			    return true
		    default:
			    return false
		    }
	    },
    },
  }
```

**Comment by gbbr** [comment]
This sounds good to me, and the PR is close to what we want. I'd like to suggest playing with the naming a bit, perhaps bringing it closer to what we have in the [gRPC integration](https://github.com/DataDog/dd-trace-go/blob/b29d64bc922324ea53a42a80bd8f3e2abb76b7fc/contrib/google.golang.org/grpc/option.go#L139-L149) for similar functionality. How about `WithIgnoreRequest` ?
