### ISSUE TITLE
ddtrace/tracer/writer: metadata doesn't support newlines

### ISSUE THREAD

**Issue by stroem** [DataDog/dd-trace-go#791]
When running dd-lambda-go with FLUSH_TO_LOGS enabled and have metadata values which contains newlines
the writer outputs every newline as a new log entry.

Would be nice if this could be looked at

**Comment by jreyeshdez** [comment]
I am also experiencing similar issues using latest `datadog-lambda-go` [release](https://github.com/DataDog/datadog-lambda-go/releases/tag/v0.9.0), specially when trying to also trace SQL queries from Postgres, when the SQL query is long and has newlines, the writer outputs every newline as a new log entry, and for some reason there are no traces at all. What is more, Datadog interprets some of the log entries as actual errors. See attached images:

![dd_lambda_logs](https://user-images.githubusercontent.com/2760399/102384792-016d9c80-3fc5-11eb-97ec-c91f368f3405.png)

![dd_lambda_logs_error](https://user-images.githubusercontent.com/2760399/102384811-0599ba00-3fc5-11eb-8fab-38d3a67a4a82.png)

You can see that the writer outputs newlines in the SQL query as a new log entry and interpreting an error in some of them when there is not actual error, the lambda did the work without errors.
