### ISSUE TITLE
ddtrace/tracer: span.SetTag() should check if value implements `String()`

### ISSUE THREAD

**Issue by pierrre** [DataDog/dd-trace-go#798]
`span.SetTag` currently checks if the value is an error/bool/string/number.
Then if the value's type is not managed, it calls `fmt.Sprint()`.

I think it should also check if the value implements `.String()`, and call it.
It would avoid to call `fmt.Sprint()`, which uses reflection, and consumes a lot of CPU.

I did a CPU profiling of my application, and the CPU time spent calling `fmt.Sprint()` is not small.
WDYT ?

**Comment by pierrre** [comment]
If it's OK I can submit a PR.

**Comment by knusbaum** [comment]
@pierrre, This sounds like it could be a good change.

`fmt.Sprintf()` will use the `.String()` method anyway, meaning the values won't change, so if checking for a `.String()` method improves performance noticeably, we can do it.

Please include benchmarks in your PR demonstrating the performance gain. We prefer [`benchcmp`](https://pkg.go.dev/golang.org/x/tools/cmd/benchcmp) for comparisons.

**Comment by pierrre** [comment]
https://github.com/DataDog/dd-trace-go/pull/799
