### ISSUE TITLE
contrib/go-redis/redis.v8: support wrapping a go-redis v8 client

### ISSUE THREAD

**Issue by seancaffery** [DataDog/dd-trace-go#803]
The current [redis-go v8 integration](https://github.com/DataDog/dd-trace-go/blob/75d7e5311c7df567073593d6a0f197564f468d5e/contrib/go-redis/redis.v8/redis.go#L40) only supports a regular Redis client. I'd like to add support for adding a hook to an existing `UniversalClient` so I can add a tracing hook to a `FailOverClient`.

The API would be similar to the one provided for the [previous redis-go integration](https://github.com/DataDog/dd-trace-go/blob/75d7e5311c7df567073593d6a0f197564f468d5e/contrib/go-redis/redis/redis.go#L61). Something like:

```go
func WrapClient(c redis.UniversalClient, opts ...ClientOption) redis.UniversalClient {
  // set up client
  // add hook
  // return client
}
```

We can likely share much of the code from `NewClient`.

An alternative could be to change `NewClient` to accept `redis.UniversalOptions` but that would be a breaking change and I imagine would be more difficult to roll out.

**Comment by knusbaum** [comment]
👍  This looks like something we want to support.

We should be careful to consider any differences (things worth making into tags, etc.) between the `UniversalClient` compared to the regular `Client`.

**Comment by seancaffery** [comment]
I've created https://github.com/DataDog/dd-trace-go/pull/808. It'd be great to get your thoughts on how we should handle tags for each kind of client.
