### ISSUE TITLE
tracer: issues with span.buffer

### ISSUE THREAD

**Issue by chibimi** [DataDog/dd-trace-go#83]
Hello
I have the following error "no span buffer" since the recent changes to the lib.
I create childs across services by sending parent info (tradeid, parentid, spanid...) in HTTP headers. (see https://github.com/gchaincl/dd-go-opentracing)
Today the parent's buffer is required to create a child but since it's a private fields it is inaccessible.
Do you think it is possible to add a nil check before span.buffer = parent.bufer in the NewChildSpan func ?

**Comment by fromz** [comment]
This just bit me now. Did you find a workaround?

**Comment by chibimi** [comment]
No we haven't put much work into this, we locked the dependency to the commit before the change.

**Comment by palazzem** [comment]
hello @chibimi! something we can do on our side to help you? By the way, we're going to officially support OpenTracing API in this core library, so the API will be different from what we have now.

**Comment by gbbr** [comment]
@chibimi @fromz I'd love to get your help on fixing this issue. Are you still encountering this issue?
 If yes, can you help me better understand the problem? I'm new to the project but I can see that we've recently added OpenTracing support. Does the problem still occur when you use our implementation of it?

If yes, I'd be more than happy to work together and fix this. It would be nice if I'd be able to write a test to start with. Can you give me more detail on how to reproduce the issue?

**Comment by chibimi** [comment]
Hello. Your open tracing implementation did the trick for us.

**Comment by gbbr** [comment]
Good to hear! In that case I'm closing this one.
