### ISSUE TITLE
undefined statsd NoOpClient

### ISSUE THREAD

**Issue by fuadajip** [DataDog/dd-trace-go#834]
Hi i'm experiencing this issue with v1.28
pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.28.0/ddtrace/tracer/option.go:207:16: undefined: statsd.NoOpClient
pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.28.0/profiler/options.go:100:19: undefined: statsd.NoOpClient

How to reproduce
```
go get gopkg.in/DataDog/dd-trace-go.v1/...
```

Env
go version go1.15.7 darwin/amd64
Apple M1

Do i miss something? i think this need to revisit and fix

**Comment by fuadajip** [comment]
Update: now i'm using v1.26 and it works fine but still not sure v1.28 show errors above

**Comment by alebabai** [comment]
Hi,

I have the same problem, but v1.26 also doesn't work for me.

**Comment by gbbr** [comment]
Thanks for reporting this and sorry for the long response time. This is likely because you are using an older version of github.com/DataDog/datadog-go which is required by v1.28. Are you able to update it? I think you need at least v3.1.0 (latest being v4.4.0)

**Comment by alebabai** [comment]
I tried to `go get -u github.com/DataDog/datadog-go` and `github.com/DataDog/datadog-go v4.4.0+incompatible // indirect` appears in my `go.mod`. It fixes issue on my local setup but still fails on CI.

**Comment by gbbr** [comment]
I guess this is the one other dependency we should be adding to our `go.mod`.

**Comment by alebabai** [comment]
I tried to use `gopkg.in/DataDog/dd-trace-go.v1 v1.29.0-alpha.1.0.20210216140755-2d091eca40bb`  but the issue still remains.
