### ISSUE TITLE
proposal: contrib/confluentinc/confluent-kafka-go/kafka wrappers doesn't fullfil public interface

### ISSUE THREAD

**Issue by alebabai** [DataDog/dd-trace-go#846]
Hi.
There are some problems with using this integration.
Wrapper types don't fully match the public interfaces of Consumer/Producer, so it can't seamlessly replace origin one.
For example `func (c *Consumer) ReadMessage(timeout time.Duration) (*Message, error)` is missing in the wrapper.

**Comment by gbbr** [comment]
Thanks for reporting. Would you be interested at all at resolving it?

**Comment by alebabai** [comment]
Yep, I can try to resolve it in PR. And yes, it applied to to all versions.

**Comment by gbbr** [comment]
Great! Thank you!

**Comment by alebabai** [comment]
After some investigate I come to mind that do we need to override public methods at all, because we have `wrapped.traceEventsChannel(c.Events())` and `wrapped.traceProduceChannel(p.ProduceChannel())` that used to trace all events from Consumer/Producer. Wrapping public methods produce duplicates in the code and in spans and alos to full-fill interface it's need to wrap all methods that seems to be redundant.
