### ISSUE TITLE
proposal: move away from gopkg.in as the canonical import path

### ISSUE THREAD

**Issue by gbbr** [DataDog/dd-trace-go#848]
Given the fact that we've now switched to modules, it should no longer be necessary to use `gopkg.in` for import paths as a dependency and we can leave it at `github.com`

**Comment by roccoblues** [comment]
@felixge @knusbaum this issue and the duplicate #867 are both closed. Is this still actively tracked somewhere? We're currently experiencing issues because `gopkg.in` is not available. Thanks!

**Comment by felixge** [comment]
This issue is still open I think? Sorry to hear about the `gopkg.in` issue. We'll discuss bumping the priority on this. We've been hesitant to make a move because it's going to be disruptive to our entire user base, but we'll have to rethink that if the reliability problems continue.

**Comment by felixge** [comment]
My colleague @ajgajg1134 just pointed out that this might also be related to https://github.com/golang/go/issues/57185

**Comment by roccoblues** [comment]
> This issue is still open I think?

Sorry, you're right. I must have confused the issues.

**Comment by roccoblues** [comment]
> My colleague @ajgajg1134 just pointed out that this might also be related to https://github.com/golang/go/issues/57185

Thanks! Yes that was probably it. I was trying to update `dd-trace-go` and immediately went down the `gopkg.in` route finding this issues.

**Comment by darccio** [comment]
Fixed in #2300 (for v2, not released yet)
