### ISSUE TITLE
proposal: add support for go-redis v7

### ISSUE THREAD

**Issue by xamenyap** [DataDog/dd-trace-go#857]
`go-redis` v6 and v8 is supported but v7 is not. I have a few dependencies on v7 so I want to add support for it. Please share what you think.
Discussion on v7 was originally in #606

**Comment by gbbr** [comment]
It looks like the person who closed the previous issue (#606) was suggesting that the v8 package would work with v7 too. Have you tried that? If it doesn't, we should and are happy to implement it.
