### ISSUE TITLE
proposal: support aws-sdk-go-v2

### ISSUE THREAD

**Issue by speza** [DataDog/dd-trace-go#869]
proposal: support aws-sdk-go-v2

Add support for tracing of aws-sdk-go-v2.

**Comment by speza** [comment]
Is it cool if I pick this one up? I have already implemented most of this outside of the contrib package.

**Comment by gbbr** [comment]
Hi Sam! Yes, absolutely. You're more than welcome to!

**Comment by william20111** [comment]
Any ETA on this being released? Would be incredibly useful for new project im working on using v2 sdk

**Comment by speza** [comment]
> Any ETA on this being released? Would be incredibly useful for new project im working on using v2 sdk

I'm currently away at the moment. I've been using very similar code from this but directly in a project with no issues thus far. I can look to potentially tidy any final bits up next week.

**Comment by william20111** [comment]
Thanks for the quick reply! Thats awesome no pressure, been playing dynamo v2 sdk and would be awesome to get DD apm with it.

**Comment by william20111** [comment]
@gbbr is the new PR good to get merged for this?

**Comment by william20111** [comment]
Any progress on getting the above merged? Would be great to get it in 1.31

**Comment by knusbaum** [comment]
@william20111 
We're reviewing the PR currently.

**Comment by william20111** [comment]
Now this is merged...is it possible to cut a release with this feature? 🤞

**Comment by xrn** [comment]
@knusbaum @gbbr will be great if it can be released - thanks in advance
