### ISSUE TITLE
proposal: adds contrib/go-chi/chi.v5

### ISSUE THREAD

**Issue by jpfaria** [DataDog/dd-trace-go#877]
it would be interesting to have the integration with chi v5 (github.com/go-chi/chi/v5)

**Comment by gbbr** [comment]
Absolutely! Is this something you'd like Datadog to add or are you opening the issue with the intention to contribute?

**Comment by jpfaria** [comment]
I can add. I've already done it, basically just rename the package.

**Comment by vadimi** [comment]
I'm also interested in this change. By the way there is already another PR open to add chi v5 support: https://github.com/DataDog/dd-trace-go/pull/858

**Comment by gbbr** [comment]
@vadimi thanks for that. I missed that one. Let's give that one a day and see if we get a response. It is only fair that it gets priority since it came first.
