### ISSUE TITLE
contrib/net/http: add a getter to retrieve original round tripper

### ISSUE THREAD

**Issue by bullgare** [DataDog/dd-trace-go#902]
I'm having an http client library that has options system.
One of the options is to force ipv4 for http.Transport by updating `http.Transport.DialContext`.

If I add options in this order, it works fine:
```
mylib.New(
&http.Client{},
...
mylib.WithIPv4Dialer(ipv4Resolver),
mylib.WithDDTracingRoundTripper(), // it is just c.client.Transport = httptrace.WrapRoundTripper()
)
```
as I can get the exact type like this - `if trans, ok := c.client.Transport.(*http.Transport); ok {`.

But if I change the order of options:

```
mylib.New(
&http.Client{},
...
mylib.WithDDTracingRoundTripper(), // it is just c.client.Transport = httptrace.WrapRoundTripper()
mylib.WithIPv4Dialer(ipv4Resolver),
)
```
it is failing as there is no way to get the original `http.RoundTripper` as dd library hides it completely and only returns a private struct implementing an interface.

So I was thinking about adding a getter that will let everyone retrieve the original transport with
`if trans, ok := c.client.Transport.(interface{Unwrap() http.RoundTripper}); ok {`.

**Comment by gbbr** [comment]
I think that should be fine, but let's call it `Unwrap`. I think that'd be a better name. What do you think?

**Comment by bullgare** [comment]
Makes sense

**Comment by bullgare** [comment]
Updated the issue description and the implementation.

**Comment by gbbr** [comment]
Thanks. We'll be releasing this soon. Probably next week.

**Comment by bullgare** [comment]
Thank you, @gbbr !

**Comment by gbbr** [comment]
You're welcome and thank you too for contributing
