### ISSUE TITLE
question: opentracing: is the chi middleware compatible with opentracing? 

### ISSUE THREAD

**Issue by KarthikNayak** [DataDog/dd-trace-go#904]
Hello, 

I'm facing a weird problem. I'm trying to use the `chi` middleware with opentracing, although the middleware injects the span into the request ctx, consequent middlewares are not getting the span. 

So in my main, I initiate the tracer as such:

```go
t := opentracer.New(
        tracer.WithAgentAddr(net.JoinHostPort(
	        cfg.DataDogConfig.AgentHost,
	        cfg.DataDogConfig.TraceAgentPort,
        )),
        tracer.WithService(cfg.DataDogConfig.Service),
        tracer.WithEnv(cfg.DataDogConfig.Env),
        tracer.WithServiceVersion(cfg.DataDogConfig.Version),
        tracer.WithRuntimeMetrics(),
        tracer.WithGlobalTag("commit", commitHash),
)

opentracing.SetGlobalTracer(t)
```

I add the chi middleware as so 

```go
router.Route("/api/v5", func(r chi.Router) {
r.Use(
	chitrace.Middleware(chitrace.WithServiceName("http.server")),
....
```

and in subsequent middlewares I try obtaining the span as so 
```
span := opentracing.SpanFromContext(ctx)
span.SetTag("request_type", v)
```

But this errors out as span is nil. Seems to be because of using opentracing and chi.middleware together. What am I doing wrong?

**Comment by gbbr** [comment]
While there have been some efforts to try and get this to work, not much success happened until today. This is also written in our (arguably not so easy to find) [README.md](https://github.com/DataDog/dd-trace-go/blob/v1/contrib/README.md) file of our integrations.

> These libraries are not built to be used with Opentracing. Opentracing integrations can be found in [their own organisation](https://github.com/opentracing-contrib).

Unfortunately when using Opentracing, one is limited to their own integrations: https://github.com/opentracing-contrib.

**Comment by KarthikNayak** [comment]
@gbbr I see that https://github.com/DataDog/dd-trace-go/pull/855 will help with this regards. Any timeline for 1.30.0? So I can plan this accordingly?

**Comment by gbbr** [comment]
Indeed! That might help. I'm planning to release 1.30.0 very soon. Unfortunately we haven't heard from the author of that PR. I might pick it up myself and take it across the finish line.

**Comment by gbbr** [comment]
Would it make sense in that case to close this in favour of #813 and consider it a duplicate?
