### ISSUE TITLE
question: getting the full root module throws grpc v0.1.2 error messages

### ISSUE THREAD

**Issue by peters95** [DataDog/dd-trace-go#911]
Issue running:

`go get gopkg.in/DataDog/dd-trace-go.v1/...`

Fails both locally as well as ubuntu docker image.

#14 222.0 # gopkg.in/DataDog/dd-trace-go.v1/contrib/google.golang.org/grpc.v12
#14 222.0 root/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.31.0/contrib/google.golang.org/grpc.v12/grpc.go:61:11: undefined: metadata.FromContext
#14 222.0 root/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.31.0/contrib/google.golang.org/grpc.v12/grpc.go:92:13: undefined: metadata.FromContext
#14 222.0 root/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.31.0/contrib/google.golang.org/grpc.v12/grpc.go:97:9: undefined: metadata.NewContext

Dockerfile example:
```

FROM ubuntu:18.04

# Install components
RUN apt-get update && apt-get install unzip wget git curl jq iputils-ping build-essential -y

# Install golang 1.16
RUN wget https://golang.org/dl/go1.16.3.linux-amd64.tar.gz && \
    tar -xvf go1.16.3.linux-amd64.tar.gz && \
    mv go /usr/local/go-1.16

ENV GOROOT=/usr/local/go-1.16
ENV PATH=$GOROOT/bin:$PATH

RUN mkdir -p /sample_module && cd /sample_module && go get gopkg.in/DataDog/dd-trace-go.v1/...
```

**Comment by felixge** [comment]
@peters95 hey, sorry you ran into this. @gbbr can probably provide more details, but afaik this is a [known](https://github.com/DataDog/dd-trace-go#testing) [issue](https://github.com/DataDog/dd-trace-go/issues/444).

For now you could you try to use `go get gopkg.in/DataDog/dd-trace-go.v1/ddtrace`?

That being said, we should definitely try to figure out how to make the error for `go get gopkg.in/DataDog/dd-trace-go.v1/...` go away or adjust the [install instructions](https://github.com/DataDog/dd-trace-go#installing).

**Comment by peters95** [comment]
New command works thanks! I think if you updated the README this would be super helpful for others in the future.

**Comment by gbbr** [comment]
@felixge is right. Unfortunately because we have to provide support for multiple versions of the `grpc` package, getting that on your system will throw that error. For that reason, it is best to only get the modules/packages you need. I'm glad it worked out. We should maybe update our README. Before doing that, I'd like to make sure about something: are you sure that this fails on your system? As far as I know, the command (`go get`) should still get the package, even if you see the error messages. The error messages should not interrupt the retrieval of the module.

**Comment by felixge** [comment]
@gbbr I just did some [testing](https://gist.github.com/felixge/22790a88ac9ae3a2a51862b09c04f1db)  using different versions of Go (1.14, 1.15, 1.16) and want to summarize the [results](https://drive.google.com/file/d/101CywX_tS9uJH5RVvhjMTMmlX5HKKErU/view?usp=sharing) here:

- `go get gopkg.in/DataDog/dd-trace-go.v1/...`
  - All versions print warnings about: `../go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.31.0/contrib/google.golang.org/grpc.v12/grpc.go:61:11: undefined: metadata.FromContext`
  - Go 1.14 and Go 1.15 still update the go.mod file based on the packages that were successfully installed. [A lot of stuff](https://gist.github.com/felixge/6d09e911e0524b03ea8fccb4c3ee891b) gets added to go.mod as a result.
  - Go 1.16 no longer updates the go.mod file, so arguably the install instructions there are completely broken.
- `go get gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer`
  - This works consistently across all Go versions and updates the go.mod file with [minimal dependencies](https://gist.github.com/felixge/3e2ad209345a13c6255248f15832aeb2).

Based on this I think we should change the instructions in the README and anywhere else to:

```
go get gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer
```

I'll send a PR.

I've also done some testing on the [profiler docs](https://docs.datadoghq.com/tracing/profiler/getting_started/?code-lang=go), they are currently also incorrect for all go versions. I'll fix that in the docs repo separately.

**Comment by felixge** [comment]
I was going to keep this issue open because I still think this problem isn't fully solved yet. The README fix should cover most users, but contributors will still run into issues. Should I open a new issue for that?

See https://github.com/DataDog/dd-trace-go/pull/917
