### ISSUE TITLE
proposal: gorm.io/gorm.v1 - Ignore some errors like record not found

### ISSUE THREAD

**Issue by vmlellis** [DataDog/dd-trace-go#915]
I wish ignore errors such as "record not found",  that is unnecessary to classify as error.

It is the same suggestion to jinzhu/gorm (https://github.com/DataDog/dd-trace-go/issues/805), it's interesting to keep the same option in case the jinzhu/gorm be upgraded to gorm.io/gorm.v1 .

As suggested in the issue of jinzhu/gorm, I also suggest adding an option that can ignore some type of errors like below:

``` golang
WithErrorFilter(func(err error) bool{
    if errors.Is(err, gorm.ErrRecordNotFound) {
        return false
    }
    return true
})
```

If you agree about it, I will make a PR.

**Comment by knusbaum** [comment]
+1 This suggestion looks acceptable to me.
