### ISSUE TITLE
mocktracer does not call `String()` on tag values

### ISSUE THREAD

**Issue by CAFxX** [DataDog/dd-trace-go#931]
`mocktracer` does not call `String()` on tag values, whereas the normal tracer does. This disparity can make it look like, during tests when `mocktracer` is used, that everything is fine - just to have the program do something different (e.g. panic) when the regular tracer is used. Don't ask how we found out. 🤣 

It would be maybe enough to have `mocktracer` call `String()` internally (and discard the resulting string) when `SetTag` is called. This would allow to exercise the same paths that the regular tracer would use.

Ideally, we should subject the value provided to the same mangling (at least from the perspective of the side effects) that is done by `SetTag` in the regular tracer:

https://github.com/DataDog/dd-trace-go/blob/434d62f26cb10c27ddb2f730e4ef1ded56bd8614/ddtrace/tracer/span.go#L112-L129

**Comment by knusbaum** [comment]
+1

The mock spans should execute the same mangling logic (and as much of the same logic in general as possible).

I'm guessing you found out similarly to this:
https://github.com/DataDog/dd-trace-go/issues/928

**Comment by knusbaum** [comment]
I spent some time looking at this. The purpose of `mockspan` is basically to record the calls made to a `Span` to make sure those are correct, rather than to validate `tracer.span`'s internal behavior. 

We already use real spans to test the behavior of spans, and the bug you encountered was the result of a lack of test coverage, which is corrected (here)[https://github.com/DataDog/dd-trace-go/pull/932/files#diff-381615e375fdd430d5010e45fd621cc648e91568874236a34ac6b446cdc60138R279-R288], not because mockspan doesn't performing mangling.

Whenever we're testing internal span behavior we should be using real spans and nothing in the way mockspan behaves today prevents us from writing tests to cover the cases that caused this bug.

@CAFxX what do you think?

**Comment by CAFxX** [comment]
Not sure I understand entirely what you mean by this:

> Whenever we're testing internal span behavior we should be using real spans and nothing in the way mockspan behaves today prevents us from writing tests to cover the cases that caused this bug.

While the check for nil would have covered the specific case we encountered, it would not have caught a related but slightly different case: that of a panicking Stringer (consider the case in which a non-nil Stringer can panic, or otherwise return incorrect/unexpected results, depending on its internal state. 

Note that while the Stringer could originate from our application code, it could also originate from third-party packages (this was indeed the case when we noticed the problem that prompted us to open this issue). Furthermore, because SetTag accepts an interface{}, changes in the packages that implements the value passed to SetTag could eventually end up panicking (e.g. if a value that previously did not implement Stringer, suddenly starts implementing it after a dependency update). 

Until mocktracer starts at least emulating (i.e. performing and then discarding) the mangling that the real tracer does, there's always going to be the potential for this sort of event to happen.

**Comment by CAFxX** [comment]
> I don't think having mockspan perform and throw away mangling would cause problems, but I don't think it would have caught this problem either.

Maybe I am missing something. The reason why I say we would have caught it is because our tests use mocktracer, and the reason our tests did not catch it is because mocktracer did not call String() on a Stringer value that originated from a third-party package and that we used as an argument to SetTag. If mocktracer had called String() on that Stringer value, it would have panicked, the panic would have caused our test to fail, and we would have noticed.

**Comment by knusbaum** [comment]
@CAFxX I see. I think I was missing something too. 
You are using mock tracer in your code for testing which is why this was not caught.

I see what you mean.

**Comment by darccio** [comment]
Solved in `v2-dev`.
