### ISSUE TITLE
proposal: ddtrace/tracer: Support injecting span context into JSON-formatted logs.

### ISSUE THREAD

**Issue by knusbaum** [DataDog/dd-trace-go#936]
Other tracers support injecting span context into logs in JSON format. (See Python https://docs.datadoghq.com/tracing/connect_logs_and_traces/python#without-standard-library-logging)

dd-trace-go currently only supports plain-text injection via the `%v` formatting verb of the `tracer.span` type. (https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/tracer/span.go#L448-L475)

Potential solutions:
 * We can provide an API to produce a map containing the relevant keys/values
 * Add a formatting directive that produces a json string

We want this method to be useful generally for json logging, and also for use with [github.com/sirupsen/logrus](https://pkg.go.dev/github.com/sirupsen/logrus) and potentially other logging libraries.

I expect that any log-library-specific code will live inside a `contrib/` package, but we should look at common logging libraries when deciding on the API to make sure we can integrate with them easily.

See also: #853

**Comment by ellisonleao** [comment]
Any updates on this?

**Comment by knusbaum** [comment]
@ellisonleao I'm working on setting an appropriate priority on this.
This will get picked up and have some response or PR in the near-term.

**Comment by ajgajg1134** [comment]
Now that we have direct support for `sirupsen/logrus` is there still value / need for this feature?

**Comment by ellisonleao** [comment]
IMHO it can be closed
