### ISSUE TITLE
contrib/confluentinc/confluent-kafka-go Can't pass context per message when producing

### ISSUE THREAD

**Issue by hexa00** [DataDog/dd-trace-go#941]
The context used when producing kafka messages can't be set on a per message basis since it's 
using the context from the cfg.ctx member variable of the producer.

See : https://github.com/DataDog/dd-trace-go/blob/11d96fd8c742ad50503212dced147833dd1712ff/contrib/confluentinc/confluent-kafka-go/kafka/kafka.go#L109 

This makes it impossible to pass a relevant parent span as the context of a message being produced.

Example in pseudo code:

```
App() {
   producer = KafkaProducer(context.background())
}
ProcessMessages() {
   processSpan, ctx = tracer.StartSpanFromContext(ctx)
   producer.Produce(message) /// Here the context used will be context.background()
   processSpan.Finish()
}
```

to be able to pass the proper context one would need for example:

```
processSpan, ctx = tracer.StartSpanFromContext(ctx)
carrier := NewMessageCarrier(msg)
tracer.Inject(sprocessSpan.Context(), carrier)
producer.Produce(msg)
```

This is how the samara implementation is done for example:
https://github.com/DataDog/dd-trace-go/blob/11d96fd8c742ad50503212dced147833dd1712ff/contrib/Shopify/sarama/sarama.go#L265

I think the confluent version should do the same ?

**Comment by knusbaum** [comment]
This looks sensible to me.

**Comment by hexa00** [comment]
@knusbaum great thank you!

Let me know if there's anything I need to do...
