### ISSUE TITLE
Datadog tracer configuration log level is incorrect in datadog

### ISSUE THREAD

**Issue by rafi-fisker** [DataDog/dd-trace-go#945]
These logs are being incorrectly marked as error level in datadog logging even though it says `INFO`

```
2021/06/03 21:39:36 Datadog Tracer v1.29.1 INFO: DATADOG TRACER CONFIGURATION {"date":"2021-06-03T21:39:36Z","os_name":"Linux (Unknown Distribution)","os_version":"unknown","version":"v1.29.1","lang":"Go","lang_version":"go1.16.4","env":"","service":"myservice","agent_url":"http://xxx.xxx.xxx.xxx:8126/v0.4/traces","agent_error":"","debug":false,"analytics_enabled":false,"sample_rate":"NaN","sampling_rules":null,"sampling_rules_error":"","tags":{"runtime-id":"d14c7f55-3464-4e17-b7a2-7917d9bc05cd"},"runtime_metrics_enabled":false,"health_metrics_enabled":false,"dd_version":"4871b2ec","architecture":"amd64","global_service":"","lambda_mode":"false"}
```

![image](https://user-images.githubusercontent.com/72412693/120719706-92570800-c47f-11eb-850e-b971ba8ca994.png)

![image](https://user-images.githubusercontent.com/72412693/120719734-a3a01480-c47f-11eb-868e-fa0ea2aecbaa.png)

![image](https://user-images.githubusercontent.com/72412693/120719897-efeb5480-c47f-11eb-814f-641a7503a0f4.png)

**Comment by felixge** [comment]
@rafi-fisker it seems like you might have to [configure a parser](https://docs.datadoghq.com/logs/faq/why-do-my-logs-show-up-with-an-info-status-even-for-warnings-or-errors/) to get the right status.

@knusbaum is there anything we can do on our end to make sure tracer log levels are automatically picked up by the logs product? Maybe use JSON output?

**Comment by rafi-fisker** [comment]
I think it may have to do with when the tracer is initialized. We are writing all logs to JSON format, but that logger might be getting initialized after the tracer...

**Comment by knusbaum** [comment]
Hi @rafi-fisker. Sorry that you're encountering issues.

I would reach out to customer support. It's possible we need to change something, but we'll want to coordinate with the logs team to figure out what's happening, and we can better handle that case through support.

**Comment by knusbaum** [comment]
I'm closing this issue since it's been moved to customer support.
Please re-open it if necessary.
