### ISSUE TITLE
proposal: Support for DD_TRACE_ENABLED environment variable 

### ISSUE THREAD

**Issue by rliebz** [DataDog/dd-trace-go#946]
Many of the DataDog clients support the `DD_TRACE_ENABLED` environment variable. For example:
- Java: https://docs.datadoghq.com/tracing/setup_overview/setup/java/?tab=containers
- Node: https://docs.datadoghq.com/tracing/setup_overview/setup/nodejs/?tab=containers
- Python: https://ddtrace.readthedocs.io/en/stable/configuration.html
- Go Lambdas: https://github.com/DataDog/datadog-lambda-go

It would be nice if this library supported it in the same manner so that consumers could leverage the built-in configuration environment variables to toggle tracing on and off, as opposed to having to instrument custom logic within the application to control it.

**Comment by omh1280** [comment]
+1

**Comment by omh1280** [comment]
Yep, that’s right.

**Comment by knusbaum** [comment]
Good, I think this implementation will work.
