### ISSUE TITLE
proposal: contrib/net/http: skip tracing for some endpoints

### ISSUE THREAD

**Issue by prasad-marne** [DataDog/dd-trace-go#947]
I think gorilla mux already has this feature implemented and would be nice to support the same in "net/http" as well.
https://github.com/DataDog/dd-trace-go/issues/790

If it's ok I can make PR for the same. Thank you.

**Comment by knusbaum** [comment]
@prasad-marne This feature looks appropriate. Please feel free to open a PR.

**Comment by prasad-marne** [comment]
Thank you. i will create a PR

**Comment by prasad-marne** [comment]
@knusbaum i created PR https://github.com/DataDog/dd-trace-go/pull/950. can you review it?
