### ISSUE TITLE
proposal: Decrease target coverage to 90%

### ISSUE THREAD

**Issue by knusbaum** [DataDog/dd-trace-go#954]
Based on what other Datadog teams are doing (all teams have target line coverage of >=90%), and [recommendations from industry leaders like Google](https://testing.googleblog.com/2020/08/code-coverage-best-practices.html) which says an "exemplary" target for coverage of patches is ~90%, we should adjust our coverage requirement to 90%.

**Comment by gbbr** [comment]
Do it!

**Comment by felixge** [comment]
What's the purpose of the configured target right now? Prevent merges? Act as a warning light?

**Comment by knusbaum** [comment]
@felixge The target needs to be met for any code changes before PR's can be merged. I think 100% was just a number we started with in #882

**Comment by felixge** [comment]
Does the percentage apply to the new code being added, or the whole code base?

Also, how did we get anything merged before? As far as I can tell current coverage is < 80%?

<img width="1159" alt="2021-06-23 Google Chrome Codecov - 11-47-28" src="https://user-images.githubusercontent.com/15000/123075763-ce471280-d418-11eb-9bdc-035a75ce5d42.png">

**Comment by knusbaum** [comment]
@felixge These requirements are new, so coverage was not measured or required before now. 

The code coverage requirement is for new/changed code. So PR's should achieve a code coverage of >=90%. 

The current coverage for the repo is < 80%, but that should hopefully climb over time as more PRs cover more code.

LMK if this causes any issues. We can adjust things as necessary.

**Comment by felixge** [comment]
I'm okay to try this for a bit.

But I'm a bit worried that this will cause more problems than it solves. For example, this makes it impossible to touch/refactor existing code without adding new test code and/or abstractions to achieve coverage.

Generally speaking it'd be nice if we could have some discussions before adding new quality control checks to our CI pipeline or processes.

**Comment by gbbr** [comment]
The patch coverage on a PR is just guidance/informative, it's not a blocker to PRs.

**Comment by felixge** [comment]
@gbbr if that's the case, I'm happy : ). I just thought @knusbaum was saying it's a required blocker for PRs. Thanks for adding this!

**Comment by knusbaum** [comment]
@gbbr @felixge 

This *will* prevent a PR's CI pipeline from being green unless the code coverage is >= 90%. Merging can still be done by override from a repo administrator, but I don't like that as a general policy, and we likely need to disable admin override soon by company policy.

For now merging should still be possible. Let's discuss here and figure out what we want the requirement to be.

**Comment by knusbaum** [comment]
We can start another discussion about target coverage elsewhere. For now this is done.
