### ISSUE TITLE
proposal: contrib/google.golang.org/grpc: support WithRequestTags in StreamServerInterceptor

### ISSUE THREAD

**Issue by isbang** [DataDog/dd-trace-go#957]
# What I did

```go
server := grpc.NewServer(
	// ...
	grpc.StreamInterceptor(
		grpc_middleware.ChainStreamServer(
			grpctrace.StreamServerInterceptor(
				grpctrace.WithServiceName(serviceName),
				grpctrace.NonErrorCodes(codes.Canceled),
				grpctrace.WithIgnoredMethods(
					"/grpc.health.v1.Health/Check",
					"/grpc.health.v1.Health/Watch",
				),
				grpctrace.WithRequestTags(),
			),
		),
	),
	// ...
)
```

# What I expected

APM with a request tag

# What is the result

APM without a request tag

<img width="698" alt="스크린샷 2021-06-28 12 12 05" src="https://user-images.githubusercontent.com/11886612/123574136-4abb6600-d80a-11eb-887e-d708d7492699.png">

**Comment by isbang** [comment]
@gbbr Would you help me with this?

**Comment by knusbaum** [comment]
@isbang I will take a look at this.

**Comment by knusbaum** [comment]
@isbang It looks like `WithRequestTags` is only implemented for the 'UnaryServerInterceptor':
https://github.com/DataDog/dd-trace-go/blob/d62beaae492db2d8d56277e2fa97533e9f2e142e/contrib/google.golang.org/grpc/server.go#L149-L156

If this can be implemented for the streaming server (it's not clear from the types), we would have to add it here:
https://github.com/DataDog/dd-trace-go/blob/d62beaae492db2d8d56277e2fa97533e9f2e142e/contrib/google.golang.org/grpc/server.go#L39-L53

We might try to implement metadata tags while we're at it.

**Comment by isbang** [comment]
Thanks @knusbaum!

**Comment by radykal-com** [comment]
@katiehockman do you think someone will have some spare time to review the PR #1632 ? we are really missing this feature
