### ISSUE TITLE
Profiler doesn't stop cleanly if uploads are failing

### ISSUE THREAD

**Issue by maebeam** [DataDog/dd-trace-go#960]
Calling `profiler.Stop()` if the profiler is unable to submit profiles hangs the shutdown process

**Comment by felixge** [comment]
@maebeam thanks for reporting this. Do you have a good way to reproduce this?

**Comment by maebeam** [comment]
Should be fairly easy to reproduce. Just a simple `main` that starts a profiler but doesn't have a dd-agent to talk to. Trap CTRL+C, call `Stop()`, and the process should hang. Let me know if this is not reproducible as this issue is a few months old

**Comment by felixge** [comment]
@maebeam sorry, hit close on accident. Trying to reproduce this now. Do you remember which version of dd-trace-go you were using?

**Comment by felixge** [comment]
@maebeam I'm able to reproduce this, see below. I'll try to fix this ASAP. Thanks again for reporting.

```go
package main

import (
	"log"
	"os"
	"os/signal"

	"gopkg.in/DataDog/dd-trace-go.v1/profiler"
)

func main() {
	log.Printf("Starting profiler")
	if err := profiler.Start(profiler.WithService("gh-960")); err != nil {
		panic(err)
	}

	log.Printf("Waiting for interrupt")
	ch := make(chan os.Signal, 1)
	signal.Notify(ch, os.Interrupt)
	<-ch

	log.Printf("Received for interrupt, shutting down")
	profiler.Stop()

	log.Printf("Shutdown complete")
}
```

```
2021/07/05 18:08:08 Starting profiler
2021/07/05 18:08:08 Waiting for interrupt
2021/07/05 18:10:23 Datadog Tracer v1.32.0 ERROR: Uploading profile failed: Post "http://localhost:8126/profiling/v1/input": dial tcp [::1]:8126: connect: connection refused. Trying again in 11.94777941s..., 1 additional messages skipped (first occurrence: 05 Jul 21 18:09 CEST)
2021/07/05 18:10:23 Datadog Tracer v1.32.0 ERROR: Failed to upload profile: failed after 2 retries, last error was: Post "http://localhost:8126/profiling/v1/input": dial tcp [::1]:8126: connect: connection refused (occurred: 05 Jul 21 18:10 CEST)
^C2021/07/05 18:10:42 Received for interrupt, shutting down
<program hangs>
```

**Comment by felixge** [comment]
@maebeam quick follow-up question: What do you expect `Stop()` to do? Assuming normal operations, the profiler could be in several different states, e.g.:

1. Recording a CPU Profile
2. Uploading the current profile
3. Idle

A graceful shutdown of the profiler would probably wait for 1/2 to complete before shutting down, but this could be perceived as "hanging" for several seconds (e.g. 15s for the CPU profile to finish in the worst case by default).

The other option is to cancel everything that is going on as I've sketched out in this PR: https://github.com/DataDog/dd-trace-go/pull/961

Please let me know what you think.

**Comment by maebeam** [comment]
In my opinion everything should be cancelled but I don't feel strongly either way

**Comment by felixge** [comment]
Fixed by https://github.com/DataDog/dd-trace-go/pull/961. Will be in the next release.
