### ISSUE TITLE
proposal: contrib/urfave/negroni: add support for another goland web framework: negroni

### ISSUE THREAD

**Issue by nzin-appdirect** [DataDog/dd-trace-go#969]
I am not using chi or gin, but negroni (https://github.com/urfave/negroni).

I would like to contribute, and add support for the negroni framework
Do you mind if I create a PR from https://github.com/nzin-appdirect/dd-trace-go/tree/negroni_support ?

**Comment by knusbaum** [comment]
@nzin-appdirect Thanks for this.

From a quick look, your integration seems to follow the style of our other http integrations.
I think we can go forward with a PR and review.

**Comment by nzin-appdirect** [comment]
Wonderful @knusbaum .

I created https://github.com/DataDog/dd-trace-go/pull/974

**Comment by nzin-appdirect** [comment]
can you tell me how to set the milestone in my PR?

**Comment by knusbaum** [comment]
@nzin-appdirect Sorry, I think that's controlled by maintainers. I've set it for you. We'll start reviewing your PR.

**Comment by nzin-appdirect** [comment]
cool!
Thank you
