### ISSUE TITLE
proposal: contrib/gofiber/fiber.v2: improve error handling

### ISSUE THREAD

**Issue by dubonzi** [DataDog/dd-trace-go#978]
Right now the fiber integration doesn't set the error information on the spans, like it's done for echo. Instead of seeing the actual error info, the span is only marked with a status code error. Is there some specific reason for it or could it be improved? I'd be happy to work on a PR if possible :)

Echo: https://github.com/DataDog/dd-trace-go/blob/v1/contrib/labstack/echo.v4/echotrace.go#L55
Fiber: https://github.com/DataDog/dd-trace-go/blob/v1/contrib/gofiber/fiber.v2/fiber.go#L69

**Comment by knusbaum** [comment]
@dubonzi 
I don't see a reason why we shouldn't be capturing the error from the `Next` call here: https://github.com/DataDog/dd-trace-go/blob/v1/contrib/gofiber/fiber.v2/fiber.go#L56

If you would like to put up a PR for that we'd be happy to review it.

**Comment by dubonzi** [comment]
Thanks for taking a look @knusbaum!

> Will that work for your use case?

It will! I'll open a PR soon for it.
