### ISSUE TITLE
proposal: contrib/olivere/elastic: Allow http.RoundTripper interface instead off *http.Transport

### ISSUE THREAD

**Issue by bboyrankingz** [DataDog/dd-trace-go#980]
Hello,

Just want to know if I could PR for this update ?

# Code
```go
// WithTransport sets the given transport as an http.Transport for the client.
func WithTransport(t http.RoundTripper) ClientOption {
	return func(cfg *clientConfig) {
		cfg.transport = t
	}
}
```

# exemple usage
```go
c := http.Client{Transport: myTransportWithInterceptors()}
httpClient := elastictrace.NewHTTPClient(elastictrace.WithTransport(c.Transport))
```

And it should still work with a classic http.Transport

Thank you

**Comment by gbbr** [comment]
Hi there 👋🏻 Thanks for opening an issue to discuss. Would the below code not have the exact same outcome?

```go
ttpClient := elastictrace.NewHTTPClient(http.Client{Transport: myTransportWithInterceptors()})
```
(adapted from your example)

**Comment by gbbr** [comment]
Would you not be able to simply wrap the returned `http.Client` and augment it as you wish? This integration replaces the `Transport` in the client so it would be misleading to offer the illusion that one could use a custom one (at least as far as the `RoundTrip` method goes).

**Comment by bboyrankingz** [comment]
thanks for the quuick response. I will think about it later

**Comment by knusbaum** [comment]
I am going to close this as stale. 
Please reopen if we can help, or open a new issue.
