### ISSUE TITLE
contrib/confluentinc/confluent-kafka-go: Set producerServiceName if svc is set

### ISSUE THREAD

**Issue by omh1280** [DataDog/dd-trace-go#982]
When using the Kafka tracer, one expects `DD_SERVICE` environment variable to set both the Kafka Consumer and Producer tracer `serviceName` properly.

Instead, only the Consumer service name is set.

**Comment by knusbaum** [comment]
We do not want to set global service name on client integrations. We only do this for server integrations (see: https://github.com/DataDog/dd-trace-go/pull/970#pullrequestreview-733632696) 
https://github.com/DataDog/dd-trace-go/blob/c0f4b736808a09e0716171201f968927c232da5e/internal/globalconfig/globalconfig.go#L45

Please note you can set the integration's service name for both consumer and producer with the [`WithServiceName` option](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1@v1.31.0/contrib/confluentinc/confluent-kafka-go/kafka#WithServiceName)
If this solution is not sufficient for your use case, we can discuss other methods for setting the service name for the integration. For example, I'm open to considering integration-specific environment variables like the [ones used for analytics](https://github.com/DataDog/dd-trace-go/blob/d62beaae492db2d8d56277e2fa97533e9f2e142e/contrib/emicklei/go-restful/option.go#L22)

**Comment by omh1280** [comment]
Thanks for the explanation! I don't entirely get the reasoning for `ServiceName` to be only for non-client integrations, but that's a different issue. Wouldn't a generic `grpc.client` service defeat the purpose of tracing since it wouldn't be clear what the client is?

I'll close this issue & PR.

**Comment by basoko** [comment]
@knusbaum I'm curious about why is considered the producer a client integration and the consumer not? I think I might be missing something here, but what would be the way to differentiate multiple services producing to the same topic in DataDog? 

Also, when looking the traces in the UI, generated by the producers and consumers in the same service, is weird to see them with a different service value.

Any clarification to try to understand the difference is more very welcome, thanks!
