### ISSUE TITLE
proposal: “resource namer” for `net/http` wrapper

### ISSUE THREAD

**Issue by MrDOS** [DataDog/dd-trace-go#983]
I've instrumented my application for Datadog tracing using the `net/http` wrapper from `gopkg.in/DataDog/dd-trace-go.v1/contrib/net/http`. None of the more specific tracers work for us, and wrapping the `http.Handler` like this means I can start tracing each request very early in its lifecycle. It's convenient, minimally-invasive, and really easy to implement. The most significant drawback is that it only supports one resource name. It's not clear from the examples, but I think the intent of the generic wrapper is that each individual handler function would be wrapped while configuring routing, rather than wrapping the router itself. In my mind, this significantly detracts from the versatility of this wrapper, because it means it needs to be more deeply-intertwined with the application code.

To overcome this, I added a [variant of the wrapper function](https://github.com/DataDog/dd-trace-go/compare/v1...therounds-contrib:feature/add-net-http-wrapper-with-resource-namer) which, instead of a constant resource name, uses a callback function – a “resource namer” – to generate a resource name for each request (presumably based on its method and URL). Then in my application code, I use [this function](https://gist.github.com/MrDOS/ebdc448a795643b447750b213add38d2) to generate the names. This allows me to configure and hook Datadog tracing near to the rest of my application configuration, and without deeply involving the router.

Would there be any interest in upstreaming this feature?

**Comment by knusbaum** [comment]
Thanks for the proposal, @MrDOS.

This looks very useful and would be a good addition. However, I think we should change how we're incorporating the resource namer. Rather than having a separate function it would be good to implement this as an `Option` like we do in other integrations, for example the [gin integration](https://github.com/DataDog/dd-trace-go/blob/d326bfb295a7c76347e5866bb349b9fb8e6fe7b1/contrib/gin-gonic/gin/option.go#L68-L74)

This *does* create a wart on the API, since `resource` is a required argument to `WrapHandler`. The options I see for that are:
1. create a new function identical to `WrapHandler` but without a resource argument, which has a `defaultResourceNamer`, again like [gin](https://github.com/DataDog/dd-trace-go/blob/d326bfb295a7c76347e5866bb349b9fb8e6fe7b1/contrib/gin-gonic/gin/option.go#L76-L88), then deprecate the original `WrapHandler`
2. Document that the `WithResourceNamer` overrides the `resource` argument and live with the inconsistency.

I'm also open to other suggestions I haven't thought of.

**Comment by MrDOS** [comment]
Digging back in my memory to when I implemented this, the Gin integration was certainly my inspiration. I'm trying to remember, but I'm fairly certain the reason I chose not to make the resource namer an `Option` was because of this exact problem with the existing argument to `WrapHandler`. And also because `ServeHTTP` gets the resource name from the mux configuration, so customizing the resource name didn't seem necessary there.

For sake of argument, one third option comes to mind, but I don't like it much: remove the `resource` argument from `WrapHandler`, change the type of `opts` to `interface{}`, and type switch over each option to determine whether it should be treated as the resource name or an option function. I.e.,

```go
// WrapHandler wraps an http.Handler with tracing using the given service and
// options. Each of the options may be an Option function or, for backwards
// compatibility, the name of the resource as a string.
//
// For example, to let the wrapper automatically generate a resource name for
// each request based on the method and URL:
//
//     handler = WrapHandler(handler, "myapp")
//
// To supply your own resource namer:
//
//     handler = WrapHandler(handler, "myapp", WithResourceNamer(myNamer))
//
// To use a constant resource name for all requests:
//
//     handler = WrapHandler(handler, "myapp", WithResourceName("myresource"))
//
// In older versions of the integration, this would have been expressed as:
//
//     handler = WrapHandler(handler, "myapp", "myresource")
func WrapHandler(h http.Handler, service string, opts ...interface{}) http.Handler {
	cfg := new(config)
	defaults(cfg)
	for _, opt := range opts {
		switch o := opt.(type) {
		case string:
			WithResourceName("o")(cfg)
		case Option:
			o(cfg)
		}
	}
	// ...
}
```

This has the upshot of being a drop-in replacement that will not affect existing API consumers. However, it comes at the terrible cost of type safety. O for sum types, eh?

Overall, I think I prefer the first option. It would be an opportunity to go a step further and remove the `service` argument, too, in favour of sharing the `WithServiceName` option with `NewServeMux`. The wrapping function could be called `WrapHandlerWithOptions` or something.

**Comment by MrDOS** [comment]
As far as the ID replacement patterns are concerned: Datadog RUM does something similar to try to generalize URLs into resources. Do you happen to know if those patterns are documented somewhere? It would probably be ideal to match that behaviour if possible.

**Comment by knusbaum** [comment]
Quantizing the URLs looks attractive. I'm not aware that RUM's behavior is documented anywhere.

Our existing integrations rely on the router to tell us what the generic route is, like Gin's [FullPath](https://pkg.go.dev/github.com/gin-gonic/gin#Context.FullPath) and Gorilla Mux's [GetPathTemplate](https://pkg.go.dev/github.com/gorilla/mux#Route.GetPathTemplate)

**Comment by MrDOS** [comment]
> I don't want an API that accepts `interface {}`.

I agree. As an API user, I'm pretty uncomfortable when I come across that.

When I can find the time, I'll start working what I already had into PR-able form, including a default implementation of a resource namer. If we get any further recommendations – on the API names, on patterns to mask in URLs, or on anything else – I'll be happy to incorporate them.

**Comment by knusbaum** [comment]
I keep going back and forth on quantization and defaults. I've spoken to other teams internally and some try to quantize but others don't.

We're also running into this issue in the new negroni integration (see here: https://github.com/DataDog/dd-trace-go/pull/974#discussion_r698827861)

It would be great to be able to put this quantization logic into some common place if we are in fact going to use it.
The `ResourceNamer` is likewise becoming common enough we may want to standardize it.

**Comment by ytakaya** [comment]
@knusbaum @MrDOS 
I too am eagerly awaiting the introduction of this feature.
I'm curious about your progress since then, what is the status of this issue now?

**Comment by MrDOS** [comment]
Thanks for the interest, @ytakaya. I haven't gotten any further since then.

FWIW, if you're chomping at the bit to use this functionality, you can get it from [this fork](https://github.com/therounds-contrib/dd-trace-go/tree/feature/add-net-http-wrapper-with-resource-namer). I would recommend _not_ using that fork directly, as the feature branch may be rebased (force-pushed) or moved. Also, it will go away once this functionality is present upstream (here). Instead, make your own fork of _this_ repo, and pull in the feature branch from my clone:

```
$ git clone ssh://git@github.com/ytakaya/dd-trace-go.git
Cloning into 'dd-trace-go'...
(...)
Resolving deltas: 100% (7942/7942), done.
$ cd dd-trace-go/
$ git remote add therounds-contrib ssh://git@github.com/therounds-contrib/dd-trace-go.git
$ git fetch therounds-contrib
remote: Enumerating objects: 108, done.
(...)
 * [new tag]         v1.35.0-rc.3                                                -> v1.35.0-rc.3
$ git checkout feature/add-net-http-wrapper-with-resource-namer
$ git push --set-upstream origin feature/add-net-http-wrapper-with-resource-namer
```

Then use a [`replace` directive](https://go.dev/doc/modules/gomod-ref#replace) in your project's `go.mod` file to reference your fork instead of the upstream:

```
replace gopkg.in/DataDog/dd-trace-go.v1 => github.com/ytakaya/dd-trace-go v1.34.1-0.20211213205710-8bd9b6950275
```

**Comment by ytakaya** [comment]
@MrDOS 
Thanks for responding!
Also, thanks for the useful information about using replace in go.mod!
Until this great feature is added to the mainstream, I will try to use that way.

**Comment by jcogilvie** [comment]
I have a fork built on 1.33 that does this with an Option of static/dynamic namer.  

I guess this is just a long-winded +1, unless somebody sees [my variant](https://github.com/DataDog/dd-trace-go/compare/v1...GetTerminus:add-resource-namer-1.33) and thinks it's worth running with.

**Comment by knusbaum** [comment]
Update here: This work is not scheduled at the moment, but we are happy to accept a PR for the work.

About the quantization, we'd prefer not to implement the URL quantization for resource names. There's too many problems associated with doing that, no matter how good the logic is.

**Comment by MrDOS** [comment]
> There's too many problems associated with doing that, no matter how good the logic is.

That does simplify the implementation of a default resource namer purely based on the request method and URL path (like @jcogilvie has provided). But it also seems like a somewhat odd take, given that Datadog has a first-party product offering – RUM – which does implement quantization, and magic black box quantization at that. I was really hoping this could be an opportunity to uncover not only a clear explanation of the rules used by the RUM quantization, but also a parallel implementation of those rules for APM. A hurdle for another day, I guess.

**Comment by knusbaum** [comment]
@MrDOS 
I also have not looked into RUM quantization, but I'll bring this up with some others internally.

Ideally all of this would be consistent and comprehensible across the entire product. Seeing as the product is so large and managed by so many teams, there are bound to be discrepancies, but we resolve them as we are able.

Please also reach out to support about this. That sometimes helps get multi-team issues/questions moving more quickly.

**Comment by MrDOS** [comment]
That's a great suggestion, and something I should've done long ago. Thank you!

**Comment by ytakaya** [comment]
@jcogilvie 
Do you plan to put up a PR?
If not, can I create a PR on your behalf? I would like to contribute to this project.

**Comment by jcogilvie** [comment]
@ytakaya I just created a PR.  The branch is out of date, though, as it's built on 1.33.

**Comment by ytakaya** [comment]
@jcogilvie Thanks for creating the PR!
