### ISSUE TITLE
proposal contrib/net/http: add StartSpanOption to RoundTripperOption 

### ISSUE THREAD

**Issue by afarbos** [DataDog/dd-trace-go#984]
When wrapping a `http.Client` or `http.RoundTripper`, we cannot any additional provide start span options.
This block the use of some functions, for example `Tag.Measured()`.

Example:
```
c = WrapClient(c, WithStartSpanOptions(Tag.Measured()))
```

**Comment by knusbaum** [comment]
This seems OK. We would just need to add a `RoundTripperOption` for span options similar to the one already there for the server integration: https://github.com/DataDog/dd-trace-go/blob/d326bfb295a7c76347e5866bb349b9fb8e6fe7b1/contrib/net/http/option.go#L90-L96

**Comment by afarbos** [comment]
Exactly and it got me confused at the beginning since I was looking for it.
I am guessing in this case it would be something like: `RTWithSpanOptions`.
