### ISSUE TITLE
proposal: default connection to agent via UDS

### ISSUE THREAD

**Issue by knusbaum** [DataDog/dd-trace-go#985]
Per the internal RFC here: (https://github.com/DataDog/architecture/blob/master/rfcs/trace-autodetect-agent-config/rfc.md)

## Goal
We want to connect to the agent via unix domain sockets when they are available. This is designed to reduce onboarding configuration by auto-connecting to a local agent without the need for configuring host and port, or relying on the agent to be listening on the default ports.

## Details
For traces, we need to connect to `/var/run/datadog/apm.socket` if present.
For statsd, we need to connect to `/var/run/datadog/dsd.socket` if present.
As a fallback for statsd, we want to use the `/info` endpoint of the trace agent to get the statsd host/port configuration.

Both of these fall back to the existing behavior, where the tracer tries to connect to `localhost:8126` and the statsd client tries to connect to `localhost:8125`.

All of this behavior is overridden by any user-provided configuration for the trace agent or statsd addresses.

## Solutions
In order to create an http client that will communicate over UDS, we need a custom `net.Dialer` that will dial the appropriate unix socket. We already do this for the trace client with the [`WithUDS`](https://github.com/DataDog/dd-trace-go/blob/d326bfb295a7c76347e5866bb349b9fb8e6fe7b1/ddtrace/tracer/option.go#L402) option. We will need to add something similar for the statsd client.

Unfortunately, this is slightly complicated by the configuration options we expose to users. Users may provide their own http clients, which could conflict with the UDS-capable client we provide. The only simple solution to this I see is to configure UDS only when no user-provided HTTP client is present.

We can achieve this by checking if the user provided an HTTP client or agent address and if not, checking for the existence of the unix socket and when present calling [`WithUDS`](https://github.com/DataDog/dd-trace-go/blob/d326bfb295a7c76347e5866bb349b9fb8e6fe7b1/ddtrace/tracer/option.go#L402) on the config object. This will configure UDS by default but will allow any user-configured HTTP client to override that default.

## Pseudocode:
```
func newConfig(opts ...StartOption) *config {
	c := new(config)
	...
	// after running all user configuration...
	if !userProvidedAgentAddress && c.httpClient == nil {
		if os.Exists("/var/run/datadog/apm.socket") {
			WithUDS("/var/run/datadog/apm.socket")(c)
		}
	}
	if !userProvidedStatsdAddress && c.statsd == nil {
		if os.Exists("/var/run/datadog/dsd.socket") {
			WithStatsdUDS("/var/run/datadog/dsd.socket")(c)
		} else {
			statsdAddress := getStatsdInfo(c.transport)
			configureStatsd(c, statsdAddress)
		}
	}
}
```

**Comment by felixge** [comment]
@knusbaum I don't see any issues with this proposal. The only suggestion I have is to consider logging a warning when `!userProvidedAgentAddress && c.httpClient != nil` saying that we're not defaulting to UDS because a custom http client has been configured or something like that. But we can hash out details like this in the PR.

**Comment by gbbr** [comment]
The only issue here is that we do not have any guarantee on the [receiver socket path](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml#L835-L839) that the user will choose. Assuming that he is using UDS based on a file path will not be a very good approach.

Instead, the right way to do this is to add this information to the discovery endpoint (`/info`) of the trace-agent. If this is discovered, then the tracer can switch to UDS. IMHO this is the correct approach, the downside being that a minimum agent version will be needed (one which reports this).

**Comment by gbbr** [comment]
P.S. I'm not sure we should religiously follow an RFC which was merged in a PR labelled as `draft` that has 0 reviews.

**Comment by felixge** [comment]
> Instead, the right way to do this is to add this information to the discovery endpoint (/info) of the trace-agent. If this is discovered, then the tracer can switch to UDS. 

@gbbr I thought the main goal of this proposal is to reduce issues with connecting to the agent to begin with? If you're already able to hit the `/info` endpoint from the tracer, switching to UDS doesn't seem to be a big win anymore?

**Comment by gbbr** [comment]
My bad. I TL;DR-ed (is this an expression?) through the RFC. In that case, when there is no way to connect, I think that attempting this is definitely a good approach.

**Comment by knusbaum** [comment]
@felixge @gbbr To be clear, the proposed method is:
1. For the tracer:
a. Use any user-provided configuration
b. Try UDS at `/var/run/datadog/apm.socket`
c. Fall back to current default of `localhost:8126`
1. For the statsd client:
a. Use any user-provided configuration
b. (After the tracer connection is configured) - Attempt to configure via the `/info` endpoint.
c. Try UDS at `/var/run/datadog/dsd.socket`
d. Fall back to current default of `localhost:8125`

**Comment by gbbr** [comment]
@felixge @knusbaum if you'd like to take a look, I've put up a PR (#1048)
