### ISSUE TITLE
proposal: contrib/twitchtv/twirp: serviceName should be read from global config

### ISSUE THREAD

**Issue by prasad-marne** [DataDog/dd-trace-go#989]
https://github.com/DataDog/dd-trace-go/blob/v1/contrib/twitchtv/twirp/option.go#L32

add a check to see if global config ServiceName is not empty before assigning the default serviceName.
I can create a PR if the proposal is accepted.

**Comment by knusbaum** [comment]
This looks correct to me. Server integrations should take the global service name if it's defined.

**Comment by prasad-marne** [comment]
PR: https://github.com/DataDog/dd-trace-go/pull/1008
