### ISSUE TITLE
proposal: contrib/gofiber/fiber.v2: reference to initial middleware span/context

### ISSUE THREAD

**Issue by JamesChung** [DataDog/dd-trace-go#990]
As far as I can tell the middleware currently is throwing away the context from the initial `tracer.StartSpanFromContext` here: 

https://github.com/DataDog/dd-trace-go/blob/4cc670944564d33a6bca2cefa21226de0ef800f1/contrib/gofiber/fiber.v2/fiber.go#L44

As a result the subsequent trace isn't linked to the initial request so you end up with one trace `http.request GET /` and another disjointed trace in DataDog.

<img width="687" alt="Screen Shot 2021-08-27 at 1 51 46 PM" src="https://user-images.githubusercontent.com/6498467/131175472-52474514-b0d1-45c6-b13c-26c6ba049314.png">

I propose using fiber's `SetUserContext()` like...
```go
span, ctx := tracer.StartSpanFromContext(c.Context(), "http.request", opts...)
// reference to link resulting spans to request
c.SetUserContext(ctx)
```

which you can then reference with `c.UserContext()` like...

```go
app.Get("/", func(c *fiber.Ctx) error {
	value := levelOne(c.UserContext(), "some values...")
})
```

When applying this fix locally I am able to see this in DataDog

<img width="375" alt="datadog" src="https://user-images.githubusercontent.com/6498467/131150804-96db8004-d312-4016-821f-50264b1af9e1.png">

I can submit a PR with my changes if everything looks fine on your end.

**Comment by knusbaum** [comment]
Hi, @JamesChung. Thanks for the report.

I would go so far as to consider this a bug. Your fix looks good and we'd be happy to accept a PR for it.
