### ISSUE TITLE
contrib/go.mongodb.org/mongo-driver/mongo: tag "db.statement" containing sensitive data

### ISSUE THREAD

**Issue by dubonzi** [DataDog/dd-trace-go#995]
The mongo integration adds a "db.statement" tag which contains the entire query being executed. This leads to a problem since the data isn't obfuscated and sensitive data ends up being sent to datadog.

https://github.com/DataDog/dd-trace-go/blob/v1/contrib/go.mongodb.org/mongo-driver/mongo/mongo.go#L47

Could we maybe make it so it can be disabled or find a way to hide the data inside the query?

**Comment by knusbaum** [comment]
Absolutely, yes.
This has been in the queue for a little while.

**Comment by dubonzi** [comment]
Great, thanks @knusbaum!
