### ISSUE TITLE
proposal: ddtrace/opentracer: implementation should return errors specified in opentracing-go

### ISSUE THREAD

**Issue by krosen040** [DataDog/dd-trace-go#998]
[opentracing-go defines some errors](https://github.com/opentracing/opentracing-go/blob/bdbb7cc3a1c08db5cc8b3296ec4447544fb43fe3/propagation.go#L12-L35) that are meant to be returned by implementations, but the Datadog OT implementation returns [errors specified in dd-trace-go](https://github.com/DataDog/dd-trace-go/blob/d62beaae492db2d8d56277e2fa97533e9f2e142e/ddtrace/tracer/propagator.go#L42-L57).

For example, the Datadog implementation of `opentracing.Tracer.Extract` returns `propagator.ErrSpanContextNotFound ` instead of `opentracing.ErrSpanContextNotFound`. If you're using the OT APIs, you expect the OT errors to be returned, not the Datadog ones.

I believe the OT implementation should map any Datadog errors to the OT equivalent before returning to the caller.

**Comment by knusbaum** [comment]
Thanks @krosen040.
This seems like a reasonable suggestion. We would just need to map certain known datadog errors to known opentracing errors here: 
https://github.com/DataDog/dd-trace-go/blob/178ecf4f0e396cf4709e6b04290bc6e72718541d/ddtrace/opentracer/tracer.go#L68-L90

I don't see any other error-returning functions in `ddtrace/opentracer` that would need to convert the errors, do you?

**Comment by krosen040** [comment]
> I don't see any other error-returning functions in ddtrace/opentracer that would need to convert the errors, do you?

No, I believe `Extract`/`Inject` are the only ones. If you think this seems reasonable I might be able to submit a PR.

**Comment by krosen040** [comment]
> I don't see any other error-returning functions in `ddtrace/opentracer` that would need to convert the errors, do you?

I don't see any other error-returning functions in ddtrace/opentracer that would need to convert the errors, do you?

**Comment by knusbaum** [comment]
@krosen040 A PR would be very welcome, thanks.
